src/core/mavsdk_impl.cpp
src/core/tcp_connection.cpp
src/mavsdk_server/src/core/core_service_impl.h

* Do not throw SIGPIPE when TCP connection ends (ignore and retry instead)
* Ignore send_message() while TCP connection is off
* mavsdk_server: send connection state when system gets disconnected
* mavsdk_server: send connection state on subscribe (instead of having to wait for an update)

Do not throw SIGPIPE when TCP connection is closed

---

.github/workflows/main.yml

Add linux-armv6-musl build

---

src/plugins/mission/mission_impl.cpp

Currently, they return an error, which is counter-intuitive. Cancelling a non-existing transfer is equivalent to doing nothing, so it's always a success.

Mission transfer (upload or download) should succeed if there is nothing to cancel

---

.github/workflows/main.yml

It got merged into dockcross, we can now start using it :tada:.

Add android-x86 and android-x86_64 to CI

---

src/core/CMakeLists.txt

Compilation failed on raspberry pi (#1296). Adding the atomic library in case we are on armv6 or amrv7 fixes the issue

cmake: include atomic library for armv6 and armv7

---

src/integration_tests/gimbal.cpp

This makes the tests fail a bit more gracefully if no system is connected.

integration_tests: check systems before accessing

---

src/plugins/ftp/ftp_impl.cpp

This way we match the implementation in PX4 and ArduPilot, and are consistent with
https://pubs.opengroup.org/onlinepubs/9699919799/functions/creat.html
Also see discussion in https://github.com/mavlink/mavlink-devguide/issues/301

ftp: add O_TRUNC flag if file is created

---

src/core/cli_arg.cpp
src/core/cli_arg_test.cpp

This change makes sure that the parser complains if parses a number only which is likely meant as a port.
So ths makes sure that udp://14540 fails while udp://:14540 passes.
Fixes #1299.

core: prevent confusions between path and port

---

src/integration_tests/gimbal.cpp
src/mavsdk_server/src/generated/gimbal/gimbal.grpc.pb.cc
src/mavsdk_server/src/generated/gimbal/gimbal.grpc.pb.h
src/mavsdk_server/src/generated/gimbal/gimbal.pb.cc
src/mavsdk_server/src/generated/gimbal/gimbal.pb.h
src/mavsdk_server/src/plugins/gimbal/gimbal_service_impl.h
src/plugins/gimbal/gimbal.cpp
src/plugins/gimbal/gimbal_impl.cpp
src/plugins/gimbal/gimbal_impl.h
src/plugins/gimbal/gimbal_protocol_base.h
src/plugins/gimbal/gimbal_protocol_v1.cpp
src/plugins/gimbal/gimbal_protocol_v1.h
src/plugins/gimbal/gimbal_protocol_v2.cpp
src/plugins/gimbal/gimbal_protocol_v2.h
src/plugins/gimbal/include/plugins/gimbal/gimbal.h

This adds the API for angular rates around the pitch and yaw axes. This API is unsupported if the gimbal v1 protocol is used though.

gimbal: implement angular rate setpoints

---

src/plugins/camera/camera_impl.cpp

There is a deadlock (trying to double-lock) in the camera plugin for the video stream information.

Fix video stream info

---

src/plugins/failure/CMakeLists.txt
src/plugins/manual_control/CMakeLists.txt

I recently tried to build the mavsdk library in a yocto Bitbake environment, where it failed with a qa issue. the problem where that the plugins 'failure' and 'manual_control' don't provide a versioned so file. This patch fixed the issue. 
Feel free to reject this PR if you left out the version in these two plugins by purpose.

fixed library versioning

---

src/core/mavlink_commands.cpp
src/core/mavlink_commands.h
src/core/system_impl.cpp
src/core/system_impl.h

This PR is just 2 commits extracted from #1322.
Credit goes mostly to @TSC21.

Improve CommandReceiver API

---

src/mavsdk_server/src/generated/camera/camera.grpc.pb.cc
src/mavsdk_server/src/generated/camera/camera.grpc.pb.h
src/mavsdk_server/src/generated/camera/camera.pb.cc
src/mavsdk_server/src/generated/camera/camera.pb.h
src/mavsdk_server/src/plugins/camera/camera_service_impl.h
src/plugins/camera/camera.cpp
src/plugins/camera/camera_impl.cpp
src/plugins/camera/camera_impl.h
src/plugins/camera/include/plugins/camera/camera.h
src/plugins/camera/mocks/camera_mock.h
src/plugins/gimbal/gimbal_protocol_v2.h

Add a way to list photos either since the moment MAVSDK connected to the drone, or all the photos on the sdcard.
The camera plugin caches the information on the pictures that are taken, meaning that for getting the images SINCE_CONNECTION, it should mostly be in the cache. However, if an image is missing, MAVSDK will retrieve it.
When fetching all the images on the sdcard, it may take longer depending on how many images are there. The way it works is that it requests the "captured" message for the next photo, and waits until a (not necessarily this one) "captured" message is received. This way it does not take all the bandwidth by e.g. sending 2000 requests at once.
There are two mechanisms to avoid deadlocks:
1. If a "captured" message is not received 1 second after the request message …

Add support for list_photos()

---

examples/takeoff_land/takeoff_and_land.cpp

In order to connect in a more robust way we should always check to actually connect to the autopilot and not e.g. to another ground station.

examples: rewrite discovery for main example

---

src/plugins/failure/CMakeLists.txt
src/plugins/manual_control/CMakeLists.txt

Got merged into `master` by mistake, cherry-picking it into `develop`

Fix library versioning

---

src/mavsdk_server/src/generated/camera/camera.pb.cc
src/mavsdk_server/src/generated/camera/camera.pb.h
src/mavsdk_server/src/plugins/camera/camera_service_impl.h
src/plugins/camera/camera.cpp
src/plugins/camera/camera_impl.cpp
src/plugins/camera/camera_impl.h
src/plugins/camera/include/plugins/camera/camera.h

[old]
This PR adds support to subscribe to subscribe to VIDEO_STREAM_STATUS messages from the camera. https://mavlink.io/en/messages/common.html#VIDEO_STREAM_STATUS
[new]
after discussions, we decided to not duplicate the redundant mavlink messages VIDEO_STREAM_STATUS and VIDEO_STREAM_INFORMATION. Instead, we extend the current structure, and update it whenever data from either of these messages arrives.
The PR depends on https://github.com/mavlink/MAVSDK-Proto/pull/207. Once merged, I'll update the submodule here.

Added FOV and video stream light spectrum enum to Camera class

---

src/mavsdk_server/src/mavsdk_server_bin.cpp

It was not very intuitive if the server does not work when you start it without an optional argument. I prefer this way where the default is sane and gets you started.

mavsdk_server: use default port 50051

---

src/plugins/tracking_server/tracking_server_impl.cpp

Typo in checking the result of is_command_sender_ok method prevented tracking commands from being executed.
Also removed duplicated log output.

TrackingServer - Fixed is_command_sender_ok result checking

---

.github/workflows/main.yml
src/plugins/gimbal/gimbal_protocol_v1.cpp
third_party/openssl/CMakeLists.txt
tools/ios.toolchain.cmake

Could potentially help adding support for M1 and Catalyst, see https://github.com/mavlink/MAVSDK-Swift/issues/190 and https://github.com/mavlink/MAVSDK-Python/issues/319.
Important note: this adds the ios toolchain to the cache key, such that when the toolchain file changes, the third_party deps are rebuilt with that new toolchain.

Update ios toolchain

---

.github/workflows/main.yml
src/core/system_impl.cpp
src/integration_tests/log_files.cpp
src/plugins/log_files/CMakeLists.txt
src/plugins/log_files/log_files_impl.cpp
src/plugins/log_files/log_files_impl.h

This is checking if the target log file is not a directory and if it does not already exist. It errors with an InvalidArgument error if the argument is not appropriate.
This hopes to improve issues like https://github.com/mavlink/MAVSDK-Python/issues/323 and https://github.com/mavlink/MAVSDK-Python/issues/312 where it was not clear how to use the arguments.

Logfiles: test if target is an unexisting file before download

---

src/core/mavsdk_impl.cpp

Fix iterator not in same container bug when compiling with MSVC2019.
Resolves #1357.
Same as #1361 but pushed onto develop. Also recommend applying this change to the master branch as the master is labeled as "latest stable build" on the website, a lot of people (including me) were to use the master branch by default.

Fix "iterator not in same container" build error when compiling with MSVC2019

---

src/core/mavlink_commands.cpp
src/core/mavlink_commands.h
src/core/mavlink_mission_transfer.cpp
src/core/mavlink_mission_transfer.h
src/core/mavlink_mission_transfer_test.cpp
src/core/mavlink_parameters.cpp
src/core/mavlink_parameters.h
src/core/mavsdk.cpp
src/core/mavsdk.h
src/core/mavsdk_impl.h
src/core/system_impl.cpp
src/core/system_impl.h

This extracts the hard-coded timeouts of 0.5 seconds into MavsdkImpl and exposes it in Mavsdk for the user to adapt based on whether MAVSDK is communicating just over localhost or over a high latency radio link.
Should fix #617.

core: make timeout configurable

---

src/core/system_impl.cpp

This prevents the error "Error: UUID changed" that we saw when connecting to a system with multiple components if the heartbeat of one of the components other than the autopilot would arrive first.
We now leave the uid to 0 as long we have no autopilot discovered. We set it to the MAVLink system ID if the autopilot does not send the autopilot_version message or has autopilot_version.uid set to 0.

core: only use UID from autopilot

---

src/integration_tests/log_files.cpp
src/mavsdk_server/src/generated/log_files/log_files.pb.cc
src/mavsdk_server/src/generated/log_files/log_files.pb.h
src/mavsdk_server/src/plugins/log_files/log_files_service_impl.h
src/plugins/log_files/include/plugins/log_files/log_files.h
src/plugins/log_files/log_files.cpp
src/plugins/log_files/log_files_impl.cpp
src/plugins/log_files/log_files_impl.h
templates/mavsdk_server/stream.j2

Also generate temporary file names with `std::tmpnam(nullptr)` in integration tests instead of hardcoding them.
Should help for issues like https://github.com/mavlink/MAVSDK-Python/issues/323 and https://github.com/mavlink/MAVSDK-Python/issues/312.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/218.

Add dependency on get_entries to force its use before downloading a log

---

src/integration_tests/log_files.cpp

Because it expects a system, I think it's nicer to stop with a failing assert than with an exception when it's not the case.

Fix exception in integration test if no system is available

---

third_party/absl/CMakeLists.txt
third_party/curl/CMakeLists.txt
third_party/jsoncpp/CMakeLists.txt
third_party/zlib/CMakeLists.txt

Cmake from version 3.18 tries to apply the patch every time anything in cmake files changed and it triggers a reconfigure. This then leads to "patch does not apply" errors. By checking out cleanly we can avoid this.

third_party: fix patch does not apply

---

src/core/filesystem_include.h
src/integration_tests/log_files.cpp
src/plugins/log_files/log_files_impl.cpp

This removes the warning about tmpnam that I get at linking, and it means I can actually see and check the files that I downloaded.

Remove tmpnam

---

src/core/tcp_connection.cpp

This resolves a build failure on macOS 10.15. Without it, attempting to build MAVSDK v0.38.0 produces the following error:
```
/tmp/mavsdk-20210325-1418-1sgyr7x/src/core/tcp_connection.cpp:164:18: error: use of undeclared identifier 'MSG_NOSIGNAL'
auto flags = MSG_NOSIGNAL;
^
1 error generated.
```
Related: https://github.com/Homebrew/homebrew-core/pull/73923

Check for MSG_NOSIGNAL instead of WINDOWS

---

src/integration_tests/CMakeLists.txt
src/integration_tests/action_hold.cpp
src/mavsdk_server/src/generated/action/action.grpc.pb.cc
src/mavsdk_server/src/generated/action/action.grpc.pb.h
src/mavsdk_server/src/generated/action/action.pb.cc
src/mavsdk_server/src/generated/action/action.pb.h
src/mavsdk_server/src/plugins/action/action_service_impl.h
src/plugins/action/action.cpp
src/plugins/action/action_impl.cpp
src/plugins/action/action_impl.h
src/plugins/action/include/plugins/action/action.h
src/plugins/action/mocks/action_mock.h

Follow-up to https://github.com/mavlink/MAVSDK-Proto/pull/221.

plugins: action: add API to change to Hold mode (loiter)

---

.github/workflows/main.yml

Seems like `-j2` may be better? Also I'm not sure if it makes sense at all in the configure step, does it? :thinking: 
The reason for that change is that some CI checks (seems like ubuntu 18.04 updated to cmake 3.20 recently) give the following kind of error at configure time:
```
Run cmake -DCMAKE_BUILD_TYPE=Release -DSUPERBUILD=OFF -DWERROR=OFF -j 2 -Bbuild/release -H.
CMake Error: Unknown argument -j
CMake Error: Run 'cmake --help' for all supported options.
```

Fix CI build for cmake 3.20 regarding -j 2

---

src/core/mavlink_statustext_handler.cpp
src/core/mavlink_statustext_handler.h

Just a small optimization for the statustext handler.

core: remove unneeded private data

---

README.md

I believe this should be the link, correct? https://mavsdk.mavlink.io/main/en/cpp/guide/build.html
EDIT: Here's another link :thinking:  https://mavsdk.mavlink.io/develop/en/contributing/build.html

Update README: link to build guide moved

---

CMakeLists.txt

This allows to specify the version when using MAVSDK, e.g.:
find_package(MAVSDK 0.38.2 REQUIRED)

cmake: add version information to package

---

tools/run-docker.sh

On Ubuntu 20.04, it seems that `command -v podman &> /dev/null` works with bash, but not with sh. This way works for both.

Fix run-docker.sh for `sh`

---

src/integration_tests/follow_me.cpp
src/plugins/follow_me/follow_me_impl.cpp

We changed the behavior of add_call_every a while ago. It now triggeres immedately as well as later. This means that the manual immediate trigger is no longer necessary. Otherwise, this leads to weird double bursts.

follow_me: fix double sending of location

---

src/core/system.cpp
src/core/system.h
src/core/system_impl.cpp
src/core/system_impl.h

This was a leftover typedef that is now consistent with the rest.

system: use new way to define callback type

---

src/core/mavsdk_impl.cpp
src/core/system.cpp
src/core/system.h
src/core/system_impl.cpp
src/core/system_impl.h

A system should not be discovered before the object is created, otherwise we end up with race conditions. Instead a system should be constructed first, and then started

Fix race in System initialization

---

tools/run-docker.sh

tools: don't display command not found

---

src/plugins/follow_me/follow_me_impl.cpp

The velocity fields of the follow-me mavlink message is currently hard-coded to `NAN`. With this PR mavsdk will send the actual values instead.
@julianoes sorry it took me so long.

follow_me: send velocity array

---

src/plugins/camera/camera_impl.cpp
src/plugins/camera/camera_impl.h

Currently, the event loop freezes while the camera definition is being downloaded, resulting in a lot of timeouts. Moreover, it keeps trying indefinitely if the download fails.
This PR makes the download run in a separate thread, and gives up after it fails downloading 3 times.

Do not freeze event loop while downloading camera definition

---

src/mavsdk_server/src/plugins/calibration/calibration_service_impl.h
src/mavsdk_server/src/plugins/camera/camera_service_impl.h
src/mavsdk_server/src/plugins/ftp/ftp_service_impl.h
src/mavsdk_server/src/plugins/gimbal/gimbal_service_impl.h
src/mavsdk_server/src/plugins/log_files/log_files_service_impl.h
src/mavsdk_server/src/plugins/mission/mission_service_impl.h
src/mavsdk_server/src/plugins/mission_raw/mission_raw_service_impl.h
src/mavsdk_server/src/plugins/shell/shell_service_impl.h
src/mavsdk_server/src/plugins/telemetry/telemetry_service_impl.h
src/mavsdk_server/src/plugins/tracking_server/tracking_server_service_impl.h
src/mavsdk_server/src/plugins/transponder/transponder_service_impl.h
templates/mavsdk_server/stream.j2

The problem right now is that a callback can still be active after the grpc server is stopped and before Mavsdk is deleted.
Could be reproduced by adding some delay when stopping the server:
```c++
void mavsdk_server_stop(MavsdkServer* mavsdk_server)
{
mavsdk_server->stop();
+    std::this_thread::sleep_for(std::chrono::milliseconds(500));
delete mavsdk_server;
}
```

Fix race condition when stopping mavsdk_server

---

src/core/mavsdk_impl.cpp
src/core/mavsdk_impl.h
src/core/system_impl.cpp

When a system was lost and re-discovered we would yet again start to send heartbeats but never actually stop the call_every. This leads to more and more traffic, memory, and CPU used.
Manually tested in normal configuration where heartbeats stop, and onboard configuration where heartbeats are always sent.

core: fix ever increasing heartbeats

---

tools/generate_from_protos.sh

The problem is that BSD (non GNU) sed on macOS does not support case conversions. Hence we need to implement the snake_case to camelCase conversion in awk.

tools: fix snake_case_to_camel_case for macOS

---

src/core/mavsdk_impl.cpp
src/core/mavsdk_impl.h

When a new system is added we expect it to be added to the end of the `systems()` vector. This can easily be accomplished by using a std::vector for the systems instead of a std::unordered_map.
For a small number of systems using a vector for that sort of lookup should be faster anyway than a map, according to common advice.
Fixes #1425.

core: use vector for systems

---

.github/workflows/main.yml
src/core/mavsdk_impl.cpp
src/core/system_impl.cpp
src/integration_tests/CMakeLists.txt
src/integration_tests/connection.cpp
src/integration_tests/ftp.cpp

This PR adds a way for MAVSDK to initiate a UDP connection, as follows:
* `udp://:14540` stays the same, it means that MAVSDK listens for heartbeats on 14540
* `udp://0.0.0.0:14540` explicitly states that MAVSDK should be have as a server (like above) and listen for heartbeats on 14540
* `udp://192.168.1.12:14540` says that MAVSDK should send heartbeats to `192.168.1.12:14540`, and therefore initiate the connection. __This is the new feature.__
It should not break any workflow, because if somebody used the format `udp://192.168.1.12:14540` before, that was probably not what they wanted to do (the behavior then was filtering the network interface, but nobody ever does that with MAVSDK as far as I know).
While implementing integration tests to test the feature, I encountered two bugs:
1. …

Initiate UDP connection from MAVSDK

---

src/mavsdk_server/src/generated/info/info.pb.cc
src/mavsdk_server/src/generated/info/info.pb.h
src/mavsdk_server/src/plugins/info/info_service_impl.h
src/plugins/info/include/plugins/info/info.h
src/plugins/info/info.cpp
src/plugins/info/info_impl.cpp

This is for backwards compatibility.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/227.
Contains #1165.

info: add legacy uid (uid1)

---

src/plugins/mission/mission_impl.cpp
src/plugins/mission/mission_impl.h

When using gimbal v2 commands in a mission we need to acquire control before setting the gimbal the first time, and release it again when the mission is done.

mission: add gimbal v2 control/release

---

tools/generate_from_protos.sh

In Homebrew, we build MAVSDK with our own gRPC and Protobuf. [1]
However, since our Protobuf is often newer than the one you vendor, we
need to regenerate some source files using `generate_from_protos.sh`
before actually building MAVSDK.
This patch allows us to do so using our gRPC and Protobuf without having
to patch `generate_from_protos.sh` or otherwise create symlinks.
[1] https://github.com/Homebrew/homebrew-core/blob/65afeec88bc6b899b1ce9a4bf12d658bbc1f3570/Formula/mavsdk.rb

Fall back to tools found in PATH in `generate_from_protos.sh`

---

src/mavsdk_server/test/camera_service_impl_test.cpp
src/mavsdk_server/test/telemetry_service_impl_test.cpp

This is suggested by latest GCC 11.

mavsdk_server: use references, not copy in tests

---

src/integration_tests/mission.cpp
src/integration_tests/mission_change_speed.cpp
src/integration_tests/mission_transfer_lossy.cpp
src/mavsdk_server/src/generated/mission/mission.pb.cc
src/mavsdk_server/src/generated/mission/mission.pb.h
src/mavsdk_server/src/plugins/mission/mission_service_impl.h
src/plugins/mission/include/plugins/mission/mission.h
src/plugins/mission/mission.cpp
src/plugins/mission/mission_impl.cpp

Appears this added in a previous PR but disappeared during a refactor. It's a useful option to have as sometimes the defaults are causing some items to never be achieved in our SITL testing (We've now swapped to MissionRaw)
Happy to update the factory funcs + proto to include this, unless there's a reason it was removed :)

Add acceptance_radius back to MissionItem

---

third_party/tinyxml2/CMakeLists.txt
third_party/tinyxml2/cmake-3.10.2.patch

This uses the upstream repo instead of my fork. Because they don't have interest in supporting Ubuntu 18.04 (the opinion there is that users should update CMake, but I disagree), this uses a patch :see_no_evil:

Patch tinyxml to run on stock Ubuntu 18.04 (with cmake 3.10.2)

---

tools/generate_markdown_from_doxygen_xml.py

This allows the docs to be built on recent Ubuntu builds, which have Python3 rather than Python. However I am not sure it is "right" fix.

Identify docs generator script as Python3

---

src/core/mavlink_commands.cpp

Because the target sysid:compid is saved in the payload of a message, it has to be filtered out after the message has been decoded. In this case, receiving an ACK targeted to another component results in a warning ("Command ack not matching our current command"), which is confusing.
This PR transparently filters out such messages.

Filter out command acks not targeted to us

---

src/plugins/camera/camera_impl.cpp

Some MAVLink systems happen to send the STORAGE_INFORMATION message to indicate that the camera has a slot for a storage even if there is no way to know anything about that storage (e.g. whether or not there is an sdcard in the slot).
In this PR I consider that a total capacity of 0 means that this is such a message, and I don't expect MAVSDK users to leverage it, which is why it is ignored.
I have already seen two MAVSDK-based apps that were failing because of that message, I think it is time we ignored it.

Ignore ghost storage_information message

---

src/core/mavsdk_impl.cpp
src/core/mavsdk_impl.h

This adds some MAVLink message debugging which can be turned on using the MAVSDK_MESSAGE_DEBUGGING env variable.

core: add message debugging

---

src/core/mavsdk_impl.cpp
src/core/mavsdk_impl.h

It turns out that the fields target_system and target_component can be trimmed if they are zero. In that case we need to assume zero instead of e.g. reading into the CRC of the MAVLink message.
Found together with @JonasVautherin.

core: fix invalid sysid/compid on trimmed messages

---

src/core/udp_connection.cpp

Remove assumption on sysids per udp packet

---

src/core/mavlink_commands.cpp
src/core/mavlink_commands.h
src/core/mavlink_mission_transfer.cpp
src/plugins/action/action_impl.cpp
src/plugins/action/action_impl.h
src/plugins/telemetry/telemetry_impl.cpp

- ACKs from Ardupilot weren't received after https://github.com/mavlink/MAVSDK/pull/1455
- Ardupilot doesn't have CAL_* params, removed requesting them from Telemetry
- some actions (e.g. Action::takeoff) caused Ardupilot to crash because of all command_long params set to NaN by default
- Action::takeoff was denied because no positive altitude was sent
- Mission uploading wasn't working because Ardupilot sends MISSION_REQUEST instead of MISSION_REQUEST_INT
Unfortunately I didn't find a good way to determine if a system is Ardupilot to apply this in real time, so I just used a macro ARDUPILOT set at compilation time. It is probably ok because it's highly unlikely that somebody will use different autopilots at the same time

Few compatibility improvements for Ardupilot

---

src/core/call_every_handler.cpp
src/plugins/camera/camera_impl.cpp

It's not fixing a bug I have, but I came across this while reading the code. I believe that if one subscribes twice in a row without unsubscribing, then the first subscription is never cancelled (which is therefore a leak).
The only way to cancel a subscription is by calling `subscribe_` again with `nullptr`, but I think it should support being replaced by another one.
@julianoes maybe to get your opinion on that, as it would probably affect all the subscriptions, and at that point I would maybe look into supporting multiple subscriptions? Not sure.

Cancel call_every when subscribing a second time

---

src/core/mavlink_commands.cpp
src/core/mavlink_commands.h

Currently, the commands are stored in a queue and sent serially. Only when the first command of the queue is done (i.e. it was acked or it timed out) can the next command be sent. This is fine when we do not send too many commands and when they do not time out (or are not slow).
With the Auterion cloud simulator, we hit the problem that the commands are executed slower than the command queue grows, which makes the whole command microservice implode. This PR seems to solve this problem by running the commands in parallel.
More specifically, here are the changes:
* We keep the sending queue, but it is only used by `do_work()`. Once a command has been sent, it is saved in a map.
* The map of sent commands uses the command id as the key. This means that only one command of each id can be run …

Run commands in parallel

---

src/core/mavlink_mission_transfer.cpp
src/core/mavlink_mission_transfer.h
src/core/mavlink_mission_transfer_test.cpp
src/core/mavsdk.cpp
src/core/mavsdk.h
src/core/mavsdk_impl.cpp
src/core/mavsdk_impl.h
src/core/system.cpp
src/core/system.h
src/core/system_impl.cpp
src/core/system_impl.h
src/debug_helpers/drop_debug_main.cpp
src/integration_tests/action_hold.cpp
src/integration_tests/action_hover_sync.cpp
src/integration_tests/action_transition_multicopter_fixedwing.cpp
src/integration_tests/integration_test_helper.h
src/integration_tests/path_checker.h
src/plugins/geofence/geofence_impl.cpp
src/plugins/mission/mission_impl.cpp
src/plugins/mission_raw/mission_raw_impl.cpp
tools/stop_px4_sitl.sh

This removes the old UUID stuff which has been marked deprecated for a while. The new way to access the uid is using the Info plugin.

core: remove deprecated UID methods

---

.github/workflows/main.yml

This is an attempt to prevent the coveralls error:
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
More ideas here: https://github.com/coverallsapp/github-action/issues/31

workflows: prevent coveralls JS out of memory

---

src/integration_tests/telemetry_async.cpp
src/mavsdk_server/src/generated/telemetry/telemetry.pb.cc
src/mavsdk_server/src/generated/telemetry/telemetry.pb.h
src/mavsdk_server/src/plugins/telemetry/telemetry_service_impl.h
src/mavsdk_server/test/telemetry_service_impl_test.cpp
src/plugins/telemetry/include/plugins/telemetry/telemetry.h
src/plugins/telemetry/telemetry.cpp
src/plugins/telemetry/telemetry_impl.cpp
src/plugins/telemetry/telemetry_impl.h

Requires https://github.com/mavlink/MAVSDK-Proto/pull/239
Adds support for multiple batteries, by handling BATTERY_STATUS message.
If no BATTERY_STATUS message is received, battery.id will default to 0, and SYS_STATUS values will be used.
Closes #1365

Add support for multiple batteries

---

.github/workflows/main.yml
docker/Dockerfile-Ubuntu-20.04-PX4-SITL-v1.12
docker/build_and_push_docker_images.sh

This adds the latest PX4 v1.12 release to the docker images and CI.

docker/workflows: add PX4 v1.12 release to CI

---

src/core/mavlink_mission_transfer.cpp
src/core/mavlink_mission_transfer.h
src/core/mavlink_mission_transfer_test.cpp
src/core/mocks/sender_mock.h
src/core/system_impl.cpp
src/core/system_impl.h

It turns out that SystemImpl did not properly implement the Sender class and therefore own sysid and compid were always 0.
This refactoring fixes that by using methods instead of variable references of variables that are not set and these abstract methods then need to be implemented, otherwise the compiler would complain.
I also had to remove on check in the unit tests, why is a mystery to me.

core: fix own sysid/compid in mission transfer

---

src/core/mavsdk_impl.cpp
src/core/mavsdk_impl.h
src/core/system_impl.cpp
src/plugins/mission_raw_server/mission_raw_server_impl.cpp
src/plugins/mission_raw_server/mission_raw_server_impl.h

Found by AppleClang:
```
/Users/julianoes/src/MAVSDK/src/core/system_impl.cpp:1384:66: warning: self-comparison always evaluates to true [-Wtautological-compare]
return _parent.get_base_mode() & (MAV_MODE_FLAG_SAFETY_ARMED == MAV_MODE_FLAG_SAFETY_ARMED);
```
And GCC:
```
/home/julianoes/src/MAVSDK/src/plugins/mission_raw_server/mission_raw_server_impl.cpp:315:26: warning: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<mavsdk::MAVLinkMissionTransfer::ItemInt>::size_type’ {aka ‘long unsigned int’} [-Wsign-compare]
315 |     if (_current_seq + 1 == _current_mission.size()) {
|         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
```

Fix two warnings recently introduced

---

src/plugins/camera/camera_impl.cpp

Whenever a command result is received that says that the storage was successfully formatted, MAVSDK should clear its own list of photos.

Clear photo list when storage is formatted

---

src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.cc
src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.h
src/mavsdk_server/src/generated/telemetry/telemetry.pb.cc
src/mavsdk_server/src/generated/telemetry/telemetry.pb.h
src/mavsdk_server/src/generated/telemetry_server/telemetry_server.pb.cc
src/mavsdk_server/src/generated/telemetry_server/telemetry_server.pb.h
src/mavsdk_server/src/plugins/telemetry/telemetry_service_impl.h
src/mavsdk_server/src/plugins/telemetry_server/telemetry_server_service_impl.h
src/plugins/telemetry/include/plugins/telemetry/telemetry.h
src/plugins/telemetry/mocks/telemetry_mock.h
src/plugins/telemetry/telemetry.cpp
src/plugins/telemetry/telemetry_impl.cpp
src/plugins/telemetry/telemetry_impl.h
src/plugins/telemetry_server/include/plugins/telemetry_server/telemetry_server.h
src/plugins/telemetry_server/telemetry_server.cpp
src/plugins/telemetry_server/telemetry_server_impl.cpp
src/plugins/telemetry_server/telemetry_server_impl.h

https://github.com/mavlink/MAVSDK-Proto/pull/246
We are not parsing or providing the heading value in the `global_position_int` message used in telemetry plugins. This add that functionality.

Add heading to global_position telemetry plugins

---

src/core/mavlink_parameters.cpp
src/core/mavlink_parameters.h

Missed the ability to set parameters clientside when I added the `param_server` plugin. 
Handles `param_set` requests and returns the value to confirm if successful.
Fills that gap :)

Add `param_set` handling

---

src/plugins/mission/mission_impl.cpp

It should just be ignored when downloading because that's an implementation detail as far as the Mission plugin is concerned. It will be added back when uploading, if I understand the code correctly :+1:.

mission: add support for DO_GIMBAL_MANAGER_CONFIGURE in mission download

---

src/mavsdk_server/src/generated/action_server/action_server.grpc.pb.cc
src/mavsdk_server/src/generated/action_server/action_server.grpc.pb.h
src/mavsdk_server/src/generated/action_server/action_server.pb.cc
src/mavsdk_server/src/generated/action_server/action_server.pb.h
src/mavsdk_server/src/generated/mission_raw_server/mission_raw_server.pb.cc
src/mavsdk_server/src/generated/mission_raw_server/mission_raw_server.pb.h
src/mavsdk_server/src/generated/param_server/param_server.pb.cc
src/mavsdk_server/src/generated/param_server/param_server.pb.h
src/mavsdk_server/src/plugins/action_server/action_server_service_impl.h
src/mavsdk_server/src/plugins/mission_raw_server/mission_raw_server_service_impl.h
src/plugins/action_server/action_server.cpp
src/plugins/action_server/include/plugins/action_server/action_server.h
src/plugins/mission_raw_server/include/plugins/mission_raw_server/mission_raw_server.h
src/plugins/mission_raw_server/mission_raw_server.cpp

Goes with https://github.com/mavlink/MAVSDK-Proto/pull/254
As can be seen, it does not modify anything regarding MAVSDK's API. It just renames some implementation details (which is needed for MAVSDK-Java).

Update proto submodule

---

src/core/mavsdk_impl.cpp
src/core/system_impl.cpp
src/core/udp_connection.cpp
src/mavsdk_server/src/mavsdk_server.cpp
src/mavsdk_server/src/mavsdk_server.h
src/mavsdk_server/src/mavsdk_server_api.cpp

* Discover the remote system before starting the grpc server
* Do not call notify_on_discover when the sysid is 0 (which means that MAVSDK is connecting to a remote, and therefore a system has not actually been discovered)
* Improve connection logging (stuff like "discovered 0 components" is a bit confusing IMO)

Improve connection and corresponding logging

---

src/mavsdk_server/src/connection_initiator.h
src/mavsdk_server/src/mavsdk_server.cpp
src/mavsdk_server/src/mavsdk_server.h
src/mavsdk_server/src/mavsdk_server_api.cpp
src/mavsdk_server/src/mavsdk_server_api.h
src/mavsdk_server/src/mavsdk_server_bin.cpp

Now that mavsdk_server.run() blocks until a system is discovered, mavsdk_server.stop() must cancel it.

Fix stop in mavsdk_server

---

src/plugins/mission/mission_impl.cpp

-1 is used for the current item value internally, but it should not be exposed to the users because it has no meaning...

Do not report -1 as a current mission item

---

src/core/mavlink_commands.cpp
src/core/mavlink_commands.h

This changes the command queue, so that:
- Only one queue is required instead of a queue and a sent map
- SET_MESSAGE_INTERVAL (511) and REQUEST_MESSAGE (512) commands are only denied if also param1 (msgid) match, otherwise they are kept in the queue until later. This should help with initial requests of messages.

core: refactor MAVLink command queue

---

src/mavsdk_server/src/CMakeLists.txt

my yocto build environment raised an QA error on the mavsdk_server library naming. This patch fixed it. if you find this useful, too feel free to accept this PR.

fixed mavsdk_server library versioning

---

src/plugins/camera/camera_definition.cpp
src/plugins/camera/camera_definition_test.cpp
src/plugins/camera/camera_impl.cpp

Currently, parameters are refreshed when they are changed. If the camera definition defines an "update" dependency (not sure when that's done), then a parameter that is modified triggers a refresh in those update dependencies.
However, what is currently missing is a way to refresh parameters that were excluded. Let's have a look using the python [`examples/camera_params.py`](https://github.com/mavlink/MAVSDK-Python/blob/main/examples/camera_params.py) example.
Without this PR, say the camera is in VIDEO mode, with exposure set to "Aperture Priority". The output will be:
```
=== Current settings ===
* CAM_MODE: PHOTO
* CAM_FOCUSMODE: Focus Mode
-> Infinity
* CAM_EXPMODE: Exposure Mode
-> Aperture Priority
* CAM_WBMODE: White Balance
-> Auto
* CAM_EV: Exposure Compensation
-> 0
* …
```

Fix possible setting options list when camera uses exclusions

---

src/plugins/telemetry/telemetry_impl.cpp
src/plugins/telemetry/telemetry_impl.h

For the Ardupilot branch the following is done to set health:
1) Checks calibration of the magnetometer, gyro and accelerometer by checking the corresponding offset values. If any offset is zero then the calibration is not complete.
2) Requests the home position. The currently home position is sent only on startup for Ardupilot so we need to ask for it here in case we have missed it.

Add health support for ardupilot

---

src/core/system.cpp
src/core/system.h
src/core/system_impl.cpp
src/core/system_impl.h

I think this might be handy to debug https://github.com/mavlink/MAVSDK/issues/1507.

core: add API to get MAVLink component IDs

---

.github/workflows/main.yml

It should already be in the docker image anyway.

docker: remove perl dependency

---

src/core/mavlink_commands.cpp

Seems to me that the lack of `break` here ends up crashing MAVSDK when there is a timeout. At least I had that issue, and this fixed it.
At the same time I fixed some unused `temp_callback`, I think.

Fix some scope issues in mavlink_commands.cpp

---

src/core/ardupilot_custom_mode.h
src/core/system_impl.cpp
src/core/system_impl.h
src/plugins/mission_raw/mission_raw_impl.cpp
src/plugins/mission_raw/mission_raw_impl.h

Adds support to mission_raw to upload, start missions and clear missions when the autopilot is ArduPilot.
Further adds support to grab the vehicle type from the HEARTBEAT message, and to use this to determine what the correct mode command is for a ArduPilot vehicle, since this depends on the type.

Ardupilot mission handling and vehicle type checking

---

src/plugins/camera/camera_impl.cpp

* Don't get stuck in busy mode: when returning an error, set `is_fetching_photos` back to `false`
* Don't notify for old photos: if `last_advertised_image_index == -1` (i.e. the camera plugin is not fully initialized), don't notify for `CAMERA_IMAGE_CAPTURED` message because it may come from QGC listing old photos.
* Clear image storage when formatting, otherwise the image metadata stay for the deleted images and we end up requesting them for nothing

Fix list_photos

---

src/mavsdk_server/src/generated/camera/camera.grpc.pb.cc
src/mavsdk_server/src/generated/camera/camera.grpc.pb.h
src/mavsdk_server/src/generated/camera/camera.pb.cc
src/mavsdk_server/src/generated/camera/camera.pb.h
src/mavsdk_server/src/plugins/camera/camera_service_impl.h
src/plugins/camera/camera.cpp
src/plugins/camera/camera_impl.cpp
src/plugins/camera/camera_impl.h
src/plugins/camera/include/plugins/camera/camera.h
src/plugins/camera/mocks/camera_mock.h

Depends on https://github.com/mavlink/MAVSDK-Proto/pull/255
The new `prepare()` function tries to fetch the camera definition and returns `Success` or `Error`. In case of `Error`, calling `prepare()` again will try again.

Add prepare() function to initialize camera plugin

---

src/plugins/ftp/CMakeLists.txt

This is not required, at least not anymore.
Fixes #1561.

ftp: remove mavlink header install

---

examples/CMakeLists.txt
examples/autopilot_server/CMakeLists.txt
examples/autopilot_server/autopilot_server.cpp
src/plugins/action_server/action_server_impl.cpp
src/plugins/action_server/action_server_impl.h

Adds an `autopilot_server` example, using `*server` plugins
Also adds `subscribe_takeoff` implementation to `action_server` for completeness :)

Add `autopilot_server` example, utilising server plugins

---

src/core/mavlink_parameters.cpp
src/core/mavlink_parameters.h
src/plugins/camera/camera_impl.cpp

This fixes two timeouts and fixes some results where we displayed "Timeout" when it was not actually a timeout.

MAVLink param improvements

---

src/plugins/camera/camera_impl.cpp

This should fix the case where the camera_captured_image callback is not called after the storage has been formatted.

camera: fix callback not called after formatting

---

src/integration_tests/CMakeLists.txt
src/integration_tests/camera_capture_info.cpp
src/plugins/camera/camera_impl.cpp
src/plugins/camera/camera_impl.h

This should fix holes when displaying all images that have been captured in a mission.

camera: request dropped IMAGE_CAPTURED messages

---

src/plugins/camera/camera_impl.cpp
src/plugins/camera/camera_impl.h

Currently, MAVSDK expects all cameras to have a camera definition URI and the Prepare method of the camera plugin will fail after 3 tries to fetch the file.
However the spec says this is optional, so an empty string should be allowed and should avoid the error.
This adds a check for the empty string to `should_fetch_camera_definition()` to handle this case.
Fixes #1603

camera: handle empty camera definition URI

---

src/core/mavsdk.cpp
src/core/mavsdk.h
src/core/mavsdk_impl.cpp
src/core/mavsdk_impl.h

This adds a new default configuration to support running MAVSDK as a camera.
A CameraServer plugin will be added later to fully support this use case.

mavsdk: add camera configuration

---

src/plugins/manual_control/manual_control_impl.cpp
src/plugins/shell/shell_impl.cpp

This is needed to get `MAV_CMD_SET_STORAGE_USAGE` for a complete camera server implementation.
Also fix breakage due to update.

mavlink: update submodule

---

src/plugins/camera/camera_impl.cpp

If we don't add unsuccessful images to the list, then we might keep requesting them and ultimately time out.

camera: prevent timeout with failed images

---

src/core/system_impl.cpp
src/core/system_impl.h
src/plugins/action_server/action_server_impl.cpp
src/plugins/telemetry_server/telemetry_server_impl.cpp

This adds a `make_command_ack_message()` method to reduce boilerplate code for responding to commands.

core: add SystemImpl::make_command_ack_message() method

---

.github/workflows/main.yml

Most of the time SITL failures are independent from the PR, so it seems interesting to always run all of them (instead of cancelling all the matrix when one job fails).

Do not cancel SITL jobs in CI, even if another one failed

---

examples/offboard/offboard.cpp
src/mavsdk_server/src/generated/offboard/offboard.grpc.pb.cc
src/mavsdk_server/src/generated/offboard/offboard.grpc.pb.h
src/mavsdk_server/src/generated/offboard/offboard.pb.cc
src/mavsdk_server/src/generated/offboard/offboard.pb.h
src/mavsdk_server/src/plugins/offboard/offboard_service_impl.h
src/mavsdk_server/test/offboard_service_impl_test.cpp
src/plugins/offboard/include/plugins/offboard/offboard.h
src/plugins/offboard/mocks/offboard_mock.h
src/plugins/offboard/offboard.cpp
src/plugins/offboard/offboard_impl.cpp
src/plugins/offboard/offboard_impl.h

Offboard global position control using [SET_POSITION_TARGET_GLOBAL_INT](https://mavlink.io/en/messages/common.html#SET_POSITION_TARGET_GLOBAL_INT), (latitude, longitude, altitude relative from home, and yaw).
Tested successfully in [sih](https://docs.px4.io/v1.12/en/simulation/simulation-in-hardware.html) simulator with a quad and a fw.
Proto is in [PR-264](https://github.com/mavlink/MAVSDK-Proto/pull/264)
Resolves #939

Offboard pos global

---

src/plugins/telemetry/telemetry_impl.cpp

Battery voltage is reported as 3.x volt on a 4S battery. This is typically one cell only.  Sum the voltage of all cells to obtain the total battery voltage.

Fix battery voltage

---

src/mavsdk_server/cmake/MacOSXFrameworkInfo.plist.in

We keep getting these errors (inconsistently) in the CI:
```
2021-11-17T22:59:29.0090500Z Copying OS X content src/mavsdk_server/src/mavsdk_server.framework/Versions/903813c0.903813c0.903813c0/Headers/mavsdk_server_api.h
2021-11-17T22:59:29.0307080Z Copying OS X content src/mavsdk_server/src/mavsdk_server.framework/Versions/903813c0.903813c0.903813c0/Modules/module.modulemap
2021-11-17T22:59:41.4030010Z [ 97%] Linking CXX shared library mavsdk_server.framework/mavsdk_server
2021-11-17T22:59:41.4355590Z ld: malformed 32-bit x.y.z version number: 903813.0.0
```
903813 is the beginning of the hash of that commit. Purely guessing, but I'm hoping that this has to do with the plist file.

Set CFBundleShortVersionString correctly

---

src/core/system_impl.cpp

This adds a check to only request the autopilot version on connection if the connection is actually an autopilot. This message fails, e.g. when connecting to a ground control station, which causes extra noise in the logs and extra mavlink messages that are just one more thing that has to be filtered out when debugging other problems.

core: only request autopilot version if autopilot

---

src/plugins/mission/mission_impl.cpp

These two breaks were missing. If an item is unsupported we have to exit the parsing and return the result instead of continuing.

mission: fail if mission item is unsupported

---

src/mavsdk_server/src/mavsdk_server_bin.cpp

This allows to start the mavsdk_server using arguments for sysid and compid.

mavsdk_server_bin: parse sysid and compid from CLI

---

src/core/mavsdk_impl.cpp

This fixes an issue where a new configuration is not applied in certain cases.

core: always apply configuration

---

src/core/system_impl.cpp
src/core/system_impl.h
src/plugins/action_server/action_server_impl.cpp

If MAVSDK is run on the companion side this will confuse the ground stations and they will say that the version of PX4 is "not supported".

core: don't send AUTOPILOT_VERSION by default

---

src/plugins/mission_raw_server/mission_raw_server_impl.cpp

Previously I was erroneously resetting mission current to zero on completion, this resulted in strange double publishing of mission current.
Correct path is to publish mission current N at the end of a mission and not reset. Mission upload will reset current to 0.

Publish mission current N on mission completion

---

examples/ftp_client/ftp_client.cpp

```Server component id is for example 1 for autopilot or 240 for companion computer.```
This sentence was misleading, as Mavsdk::Configuration::UsageType::CompanionComputer in ftp_server results in a component ID of 195 (MAV_COMP_ID_PATHPLANNER).
So I ended up trying component ID 191 (MAV_COMP_ID_ONBOARD_COMPUTER) and component ID 240 (as the comment suggests), which both did not work.
Does it make sense to invent new names for component IDs though? Why not stick to the same names as in mavlink and have a nice 1-to-1 relationship (OnboardComputer = MAV_COMP_ID_ONBOARD_COMPUTER, etc.)

ftp_client: fix component ID comment

---

src/mavsdk/plugins/calibration/calibration_impl.cpp

Gimbal calibration is implemented in the "right" way with a long running command. This allows us to close the stream when we receive the final ACCEPTED ack.
FYI @potaito.

calibration: handle ack for gimbal calibration

---

src/mavsdk/core/system_impl.cpp

I'm sure this is the last bug MAVSDK will ever have...

Enable surface boat rover modes in Ardupilot

---

.github/workflows/main.yml
tools/create_packages.sh

Without the arch argument, fpm seems to use amd64 instead which is wrong for the arch packages.
Hopefully resolves #1673.

tools/workflows: fix packages for arm

---

docker/Dockerfile.dockcross-linux-arm64-custom
docker/Dockerfile.dockcross-linux-armv6-custom
docker/Dockerfile.dockcross-linux-armv7-custom

This means we depend on older glibc v2.27 rather than v2.34 which should work on Debian Buster and Ubuntu 20.04.

docker: use arm lts images

---

src/mavsdk_server/src/mavsdk_server_api.h

Fixed XCode warning: "declaration of "Struct MavsdkServer" will not be visible outside of this function"

Fixed XCode warning

---

examples/ftp_client/ftp_client.cpp

Fixes divide by zero when uploading / downloading a zero-length file with the ftp client example.

example-ftp: Do not divide by zero on zero-bytes file

---

src/mavsdk/plugins/ftp/ftp_impl.cpp

Since https://github.com/PX4/PX4-Autopilot/pull/18704, sending a 0 length on download does not make PX4 send any data. 
The download gets stuck then.
This just always requests the maximum number of bytes, except for the last packet.

FTP: Set size in message on read

---

src/mavsdk/plugins/mission_raw_server/mission_raw_server_impl.cpp

Escaping bounds of the mission items at the end of a mission.
This fixes that.

Fix end of mission crash with mission server

---

src/mavsdk/core/include/mavsdk/mavsdk.h
src/mavsdk/core/mavsdk.cpp

It turns out that we sent out MAV_TYPE_GENERIC for UsageType::Custom if we manually set sysid and compid. However, when we use the usual ground station compid, we would probably expect that the normal MAV_TYPE_GCS.
This fixes mavsdk_server were sysid and compid is set manually and therefore the MAV_TYPE was suddenly wrong.
Fixes https://github.com/mavlink/MAVSDK-Python/issues/448.

core: fix MAV_TYPE of mavsdk_server

---

src/mavsdk/plugins/calibration/calibration.cpp
src/mavsdk/plugins/calibration/calibration_impl.cpp
src/mavsdk/plugins/calibration/include/plugins/calibration/calibration.h
src/mavsdk_server/src/generated/calibration/calibration.pb.cc
src/mavsdk_server/src/generated/calibration/calibration.pb.h
src/mavsdk_server/src/plugins/calibration/calibration_service_impl.h

This is practical to notify of functionality that is not expected to work yet.

calibration: add unsupported result

---

src/mavsdk/plugins/mocap/include/plugins/mocap/mocap.h
src/mavsdk/plugins/mocap/mocap.cpp
src/mavsdk_server/src/generated/mocap/mocap.pb.cc
src/mavsdk_server/src/generated/mocap/mocap.pb.h
src/mavsdk_server/src/plugins/mocap/mocap_service_impl.h

This is helpful to signal early if something is not available.

mocap: add unsupported result

---

src/mavsdk/core/CMakeLists.txt

Trying a fix for https://github.com/mavlink/MAVSDK/issues/1688
Resolves #1688

Set RUNTIME DESTINATION to fix Windows install

---

src/integration_tests/action_goto.cpp
src/mavsdk/plugins/action/action.cpp
src/mavsdk/plugins/action/action_impl.cpp
src/mavsdk/plugins/action/action_impl.h
src/mavsdk/plugins/action/include/plugins/action/action.h
src/mavsdk/plugins/action/mocks/action_mock.h
src/mavsdk_server/src/generated/action/action.grpc.pb.cc
src/mavsdk_server/src/generated/action/action.grpc.pb.h
src/mavsdk_server/src/generated/action/action.pb.cc
src/mavsdk_server/src/generated/action/action.pb.h
src/mavsdk_server/src/plugins/action/action_service_impl.h

This is an API that allows to temporarily set the speed of the drone, e.g. for mission mode or in goto/reposition mode.
FYI @reedev

action: add API to set current speed

---

src/mavsdk/core/lazy_plugin.h

I think this should fix https://github.com/mavlink/MAVSDK-Python/issues/460.

Make LazyPlugin thread-safe

---

src/mavsdk/core/system_impl.cpp

core: fix uninitialized command

---

src/integration_tests/param.cpp
src/mavsdk/core/mavlink_parameters.cpp
src/mavsdk/core/mavlink_parameters.h
src/mavsdk/core/system_impl.cpp
src/mavsdk/core/system_impl.h
src/mavsdk/plugins/param/param_impl.cpp
src/mavsdk/plugins/param/param_impl.h

This pull request contains the minimal necessary changes needed in the MAVSDK to make param set/get work with Ardupilot. Following the discussion from https://github.com/mavlink/MAVSDK/issues/1683, I decided to try the suggestion B from @julianoes 
> B) Always download all params on startup to then have the type cached when the function is used. This would take longer but make the API easier. What do you think?
I had to, however create a different function to deal with the param set for APM
```bash
float MAVLinkParameters::ParamValue::get_4_float_bytes() const
float MAVLinkParameters::ParamValue::get_4_float_bytes_apm() const
```
As mentioned before, Ardupilot likes to have direct cast to float instead of the re-interpret cast used in MAVSDK for PX4 param set. More details can be found in …

param: changes for making param set/get work with ArduPilot

---

src/mavsdk/plugins/camera/camera_impl.cpp

I just realized that [select_camera()](https://github.com/mavlink/MAVSDK/blob/10181c60148ace1229565cbb2e04531122d529d0/src/mavsdk/plugins/camera/camera_impl.cpp#L263) will [update the component id for the camera message handlers](https://github.com/mavlink/MAVSDK/blob/10181c60148ace1229565cbb2e04531122d529d0/src/mavsdk/plugins/camera/camera_impl.cpp#L229-L248), but if `select_camera()` is never called (the default), then that filtering is not set (and hence I believe that the camera instance will receive those messages even if they come from a different component id).
This just sets the compid at `init()` time, to be consistent.

camera: filter by compid at init time

---

src/mavsdk/core/mavlink_parameters.cpp
src/mavsdk/core/mavlink_parameters.h
src/mavsdk/core/system_impl.cpp
src/mavsdk/core/system_impl.h
src/mavsdk/plugins/camera/camera_impl.cpp

As seen in #1728 the MAVLinkParameters is using some magic numbers to define the designated target component of the message,
This prevents the Camera plugin to read the parameters of the any camera other than the first.
This PR add some overloaded functions for the `set_param` and `get_params` actions that accept an additional target `component_id` parameter. 
The Camera plugin as been updated to make use of this new functions.

Fix multicamera options

---

src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/mavsdk_impl.h

This fixes a deadlock that can happen rarely when trying to connect to a system.
Presumably we have seen this happen every now and then in SITL integration tests in CI (FYI @dagar).
It's a typical deadlock where two different mutexes are locked in opposite order, so what happens is that:
- the first thread locks mutex A and then tries to lock mutex B, and
- the second thread locks mutex B and then tries to lock mutex A. At this point both threads are waiting on the other thread and neither can continue.
In this case the two relevant locks are:
- `_new_system_callback_mutex`, and
- `_systems_mutex`
1. The user calls `subscribe_on_new_system()` which locks `_new_system_callback_mutex`, and then checks whether there is already a system that they should be notified about.
In …

core: fix deadlock on discovery

---

.gitignore

Turns out sometimes I'm using CLion.

gitignore: ignore CLion cmake build folders

---

src/mavsdk/core/mavlink_include.h
src/mavsdk/core/mavsdk_impl.cpp

Previously, we made an attempt to fix the outgoing sequence numbers. Therefore, we would ignore the chan number for the mavlink_status_t, however, this lead to serious problems when doing system tests with multiple mavsdk instances sending messages to each other as they would sometimes both use the mavlink_status_t data and mess up each others parsing.
Therefore, we remove the previous hack, and go back to separate mavlink_status_t. This will probably mess up outgoing sequence numbers but given they can't reliably be used to assess drop rate anyway it's an ok pill to swallow, for now. And this enables more consistent system tests, and in general applications with more than one Mavsdk instance.

core: use separate mavlink_status_t again

---

src/mavsdk/core/mavlink_mission_transfer.cpp
src/mavsdk/core/mavlink_mission_transfer.h
src/mavsdk/core/mavlink_mission_transfer_test.cpp

This fixes #1745 and adds some more debugging if the env variable MAVSDK_MISSION_TRANSFER_DEBUGGING is set to 1.

Fix mission transfer duplicates

---

src/mavsdk/core/system_impl.cpp

It seems like `vehicle_type` can jump around a lot if multiple systems are reporting vehicle_types differently. This allows only autopilots the ability to set vehicle types for system.

Fix vehicle_type detection for systems

---

third_party/mavlink/CMakeLists.txt

Otherwise we end up with errors like this:
```
[ 12%] Performing download step (git clone) for 'mavlink'
Cloning into 'mavlink'...
fatal: reference is not a tree: 3b52eac09c2e37325e4bc49cd2667ea37bf1d7d2
CMake Error at /home/dronedojo/github_repos/MAVSDK/build/default/third_party/mavlink/mavlink/tmp/mavlink-gitclone.cmake:49 (message):
Failed to checkout tag: '3b52eac09c2e37325e4bc49cd2667ea37bf1d7d2'
```
Resolves #1755.

Do not shallow-clone and use a specific commit

---

src/mavsdk/core/system_impl.cpp

The change from https://github.com/mavlink/MAVSDK/pull/1752 inadvertantly threw a warning for all heartbeats that came from an "INVALID" autopilot. However, this is acceptable according to the [Heartbeat protocol.](https://mavlink.io/en/messages/common.html#HEARTBEAT) This small commit fixes that issue.

Fix to allow non-flight controller heartbeats to be processed

---

.gitmodules

This is now fetched from cmake or manually.
Leftover from #1741.

gitmodule: remove mavlink repo

---

CMakeLists.txt

It's impossible to build from source.tar.gz or .zips at current as it is dependent on the repo being a git repository. This adds a fallback to `0.0.0` in this case as version number is not known and allows dependent modules to build

Add version number fallback

---

src/mavsdk/core/mavsdk_impl.cpp

Without this fix, MAVSDK has issues detecting more than one system (it seems like one `notify_on_discover` is lost, because one of the systems was `always_connected` and is renamed when a new one is detected).
This fix just clears the "fake system" when a new one is discovered, so that the new one triggers the discovery callback.

Fix system discovery

---

src/mavsdk/core/mavsdk_impl.cpp

@JonasVautherin I think the fix you suggested in #1774 does not work in general.
Removing a system is not really supported, so in the case of the FTP test, the ftp plugin is already created from the fake plugin and removing it has bad effects, in this case a segfault.
This PR reverts your commit and adds a commit which instead triggers a discovery notification when a fake system changes to a real system.
However, in the future, given the server components - I think - we can remove the fake system completely. However, this requires us to split the FTP plugin into client and server. That's something I wanted to do but haven't gotten to yet.

Fix FTP test segfault

---

src/mavsdk/plugins/telemetry/telemetry_impl.cpp

It looks like the lock was released too early, so before the `_rc_status_subscription` and `_health_all_ok_subscription` were used.
This presumably lead to a address sanitizer failure in CI:
https://github.com/mavlink/MAVSDK/runs/6503431662?check_suite_focus=true#step:6:2519

telemetry: fix scope of subscription lock

---

third_party/openssl/CMakeLists.txt

Not sure if we would be affected but let's update anyway:
https://www.openssl.org/news/secadv/20220503.txt

openssl: update to  1.1.1o

---

src/integration_tests/param.cpp
src/mavsdk/core/mavlink_command_sender.cpp
src/mavsdk/core/mavlink_parameters.cpp
src/mavsdk/core/server_component_impl.cpp
src/mavsdk/core/server_component_impl.h
src/system_tests/CMakeLists.txt
src/system_tests/param_get_all.cpp

This fixes a segfault/abort when using get_all_params(). The issue was that the timeout handler was not removed as it should have been, and so after a successful completion, we got another call from the timeout handler which then satisfies the promise a second time which is not possible.
This did not show up in the integration test (or at least not often) because the test was already destructed by the time the timeout would trigger.
Fixes #1785.

params: fix double promise call

---

src/mavsdk/core/CMakeLists.txt
src/mavsdk/core/callback_list.h
src/mavsdk/core/callback_list_test.cpp

This allows to replace callback subscriptions with lists, so that multiple callbacks can be registered.
FYI @devbharat: I think this might be the minimal implementation of what we need for multiple subscriptions.

core: Add callback list

---

src/mavsdk/plugins/telemetry/telemetry_impl.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.h

With this commit we start to use the sys_status flags to determine whether local and global position are ok. If the flags don't appear to be set, we fall back to counting GPS satellites like before.

telemetry: sys_status for position health flags

---

src/mavsdk_server/src/grpc_server.cpp

This PR enables the default grpc health check service for the mavsdk_server. Such a service is useful to check if mavsdk_server has started serving before clients would try to connect it. Documentation on this service is at [gRPC-C++ Health Check Protocol](https://grpc.github.io/grpc/cpp/md_doc_health-checking.html)
Once enabled, a CLI client like [grpc_health_probe](https://github.com/grpc-ecosystem/grpc-health-probe) can be used to check if the service is serving or not.
Example 1: MAVSDK Server is not yet connected to any autopilot so not listening on port 50051.
```bashroot@e85de2b5138f:/home/user/tools# ./grpc_health_probe -addr 127.0.0.1:50051
timeout: failed to connect service "127.0.0.1:50051" within 1s
```
Example 2: MAVSDK Server IS conencted to a autopilot and listening on port …

server: enabled option for default health check service for mavsdk grpc server.

---

src/mavsdk/plugins/rtk/rtk_impl.cpp

Instead of always sending the first part we should actually send the remaining data as well, duh.
Resolves https://github.com/mavlink/MAVSDK/issues/1800

rtk: fix multi part data being sent

---

src/mavsdk/core/system_impl.cpp

Following #1760 The vehicle type can never be changed from generic. As such the vehicle will always operate as generic, breaking plane/quad/rover type detection :)
I believe this was the original intention of the change. @pweids might be able to confirm.

Fix vehicle type detection

---

src/mavsdk/core/CMakeLists.txt
src/mavsdk/plugins/mavlink_passthrough/CMakeLists.txt

Taken from https://github.com/mavlink/MAVSDK/commit/0c8e2367952b3233669739d439a13f2ccb568470, as it feels useful to merge it ASAP.

cmake: install mavlink headers in correct dir

---

src/mavsdk/plugins/telemetry/telemetry_impl.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.h

Sometimes, randomly the home position is not received/processed by MAVSDK which leads to `all_health_okay` to be never `true`. 
This has been often the case in integration tests, where one or two tests would randomly fail waiting for the health to be okay which never happens. 
In this PR, the retry mechanism is added for requesting the home position until it is received/set.
Glad to hear your feedback :)

Retry home position until set. 

---

src/mavsdk/core/CMakeLists.txt
src/mavsdk/core/fs.cpp
src/mavsdk/core/fs_test.cpp

* When given a relative path the function would fail to add correct path separation. For instance, if the current working directory is `/home/ubuntu`, when `fs_canonical("example")`, or `fs_canonical("./example")` is run, it returns `/home/ubuntuexample`.
* MAVSDK claims to support different path separators, but `/` was hardcoded in some cases.
* Along with that, the path separator was assumed to be one character in some cases, particularly when `/` was hardcoded. The datatype of the `path_separator` constant is string, so this assumption is not necessarily correct.
This PR fixes all of these things, and also makes the code more efficient by using a double-ended queue instead of two stacks and avoiding double initialization of object when possible.

core: fix some bugs in fs_canonical

---

.github/workflows/main.yml
docker/Dockerfile-Fedora-36
docker/build_and_push_docker_images.sh

Add Fedora 36 to CI

---

src/integration_tests/mission_transfer_lossy.cpp

This test seems flaky to me in the CI, and I can't help but to think that maybe, sometimes, it gets into a state where dropping _exactly every tenth_ message make it fail.
I changed it for a uniform distribution, which seems deterministic when running on my computer (not sure what the default seed is), but at least it's dropping 10% of the messages, and not exactly every tenth message.
Without this PR (I see a lot of 73):
```
[12:34:32|Debug] Dropped outgoing message: 44 (mavsdk_impl.cpp:359)
[12:34:32|Debug] Dropped incoming message: 51 (mavsdk_impl.cpp:251)
[12:34:33|Debug] Dropped outgoing message: 73 (mavsdk_impl.cpp:359)
[12:34:33|Debug] Dropped outgoing message: 73 (mavsdk_impl.cpp:359)
[12:34:33|Debug] Dropped outgoing message: 73 (mavsdk_impl.cpp:359)
[12:34:34|Debug] Dropped …
```

Use a uniform distribution to drop messages in lossy test

---

third_party/mavlink/CMakeLists.txt

This CMakeLists.txt should work standalone, and therefore it should define the `MAVLINK_DIALECT` if unset.

Set default MAVLINK_DIALECT

---

src/integration_tests/mission_raw_import_and_fly.cpp

Seems like this got forgotten. Should not change anything, just the compiler warning.
> /src/integration_tests/mission_raw_import_and_fly.cpp: In function ‘mavsdk::MissionRaw::MissionItem create_mission_item(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, float, float, float, float, double, double, double, uint32_t)’:
/src/integration_tests/mission_raw_import_and_fly.cpp:187:14: warning: unused parameter ‘_mission_type’ [-Wunused-parameter]
187 |     uint32_t _mission_type)
|     ~~~~~~~~~^~~~~~~~~~~~~

Use mission_type argument in integration test

---

src/mavsdk_server/src/plugins/action_server/action_server_service_impl.h
src/mavsdk_server/src/plugins/camera/camera_service_impl.h
src/mavsdk_server/src/plugins/camera_server/camera_server_service_impl.h
src/mavsdk_server/src/plugins/component_information/component_information_service_impl.h
src/mavsdk_server/src/plugins/component_information_server/component_information_server_service_impl.h
src/mavsdk_server/src/plugins/gimbal/gimbal_service_impl.h
src/mavsdk_server/src/plugins/mission/mission_service_impl.h
src/mavsdk_server/src/plugins/mission_raw/mission_raw_service_impl.h
src/mavsdk_server/src/plugins/mission_raw_server/mission_raw_server_service_impl.h
src/mavsdk_server/src/plugins/shell/shell_service_impl.h
src/mavsdk_server/src/plugins/telemetry/telemetry_service_impl.h
src/mavsdk_server/src/plugins/tracking_server/tracking_server_service_impl.h
src/mavsdk_server/src/plugins/transponder/transponder_service_impl.h
templates/mavsdk_server/stream.j2

Just a minor detail in the templates that creates a lot of warnings.

Fix warnings in mavsdk server

---

src/integration_tests/follow_me.cpp

As discussed in the [Dev-Call](https://discuss.px4.io/t/px4-dev-call-july-06-2022/28093#q2-julianoes-is-reworked-follow-me-available-before-or-after-113-release-8), as the [improved Follow-me](https://github.com/PX4/PX4-Autopilot/pull/18026) didn't get into PX4 v1.13, the SITL tests were failing.
This PR adds capability to do `param_get` to PX4 to check if the improved Follow-me is supported, and if not, it would skip the test (this would also skip the test for flash constrained builds, and is more proper way of handling the test skipping criteria, as the version tag itself is not sufficient indicator of the features the vehicle supports)
Fixes #1845

Only enable follow-me test if the improved followme' parameter exists

---

.github/workflows/main.yml
tools/generate_from_protos.sh

@devbharat suggested to install the protoc-gen-mavsdk package locally and therefore avoiding some of the potential headaches when the system wide package is not the correct version, or not installed.
Objections @JonasVautherin?

Local protoc-gen-mavsdk install

---

src/mavsdk/core/mavlink_command_sender.cpp

In order to prevent too many commands from clogging the queue, we remove them if they look identical.
This changes it so that we only drop a command if it does not come with a callback. If it has a callback associated with it, it's better to call it anyway, otherwise odd races or just Denied results when you don't expect it tend to be the result.
This is the same as I fixed previously, however, this time also for CommandLong which I forgot last time.

core: second in flight command fix

---

src/mavsdk/plugins/camera/camera_impl.cpp
src/mavsdk/plugins/camera/camera_impl.h

It could be that some other component (or the user, manually) formats the storage. MAVSDK can detect that by observing that the `image_count` became smaller than it was before (e.g. `image_count = 30` followed by `image_count = 0` means that the storage was formatted). Because we can lose messages, I don't check `image_count == 0`, but `last_image_count > new_image_count`. The only reason why the image count would get lower is because the storage was formatted.
Also, it _should_ work if just a few pictures are removed from the storage: here it just invalidates the whole photo list and MAVSDK has to start all over again, so that should be fine. Still, that's not a supported use case in the MAVLink specs.

Detect external storage format

---

.github/workflows/main.yml
docker/Dockerfile-Ubuntu-22.04
docker/Dockerfile-Ubuntu-22.04-PX4-SITL-v1.13
docker/build_and_push_docker_images.sh
src/mavsdk/core/mavlink_parameters.h
tools/fix_style.sh
tools/run-docker.sh

`clang-format-12` is a nice choice because it is available for both Ubuntu
20.04 as well as Ubuntu 22.04.
This also bases the PX4 v1.13 SITL build on top of Ubuntu 22.04.

Switch to clang-format-12

---

tools/fix_style.sh

This was hard-coded when it should not have been.

tools: fix clang-format error message

---

src/integration_tests/telemetry_async.cpp
src/integration_tests/telemetry_sync.cpp
src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h
src/mavsdk/plugins/telemetry/mocks/telemetry_mock.h
src/mavsdk/plugins/telemetry/telemetry.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.h
src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.cc
src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.h
src/mavsdk_server/src/generated/telemetry/telemetry.pb.cc
src/mavsdk_server/src/generated/telemetry/telemetry.pb.h
src/mavsdk_server/src/plugins/telemetry/telemetry_service_impl.h

Before we processed whatever attitude was being sent which meant that both MAVLink messages ATTITUDE and ATTITUDE_QUATERNION would trigger both callbacks. This was often ok but can be very confusing when trying
to set the rate of the messages.
This commit decouples this magic and provides setters for both the rates.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/293.
Closes https://github.com/mavlink/MAVSDK/issues/1569.

telemetry: split attitude into Euler + Quaternion

---

src/CMakeLists.txt
src/mavsdk.pc.in

This adds support for pkgconfig. Closes #1428.
The way to get the library in cmake using pkgconfig is:
```
find_package(PkgConfig REQUIRED)
pkg_check_modules(MAVSDK REQUIRED mavsdk)
target_link_libraries(gimbal
${MAVSDK_LIBRARIES}
)
target_include_directories(gimbal
PRIVATE ${MAVSDK_INCLUDE_DIRS}
)
```

Add support for pkgconfig

---

src/mavsdk/core/mavlink_mission_transfer.cpp
src/mavsdk/plugins/mission_raw/mission_import.cpp
src/mavsdk/plugins/mission_raw/mission_import.h
src/mavsdk/plugins/mission_raw/mission_import_test.cpp
src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp

ArduPilot stores the home position in mission item 0. This means that we need to add the home position as saved in the .plan file to the mission raw list of mission items.

mission_raw: add home position at 0 for ArduPilot

---

.github/workflows/main.yml

Fix workers to use `macos-12`.
Note that `macos-12` still defaults to [xcode 13.4.1](https://github.com/actions/runner-images/blob/macOS-11/20220906.1/images/macos/macos-12-Readme.md#xcode). When that changes to xcode 14, we can probably remove the bitcode support.

Fix ci workers to macos-12

---

src/mavsdk/plugins/telemetry/telemetry_impl.cpp

This must have snucked in during some merge.

core: remove wrong/confusing warning

---

src/mavsdk/core/CMakeLists.txt
src/mavsdk/plugins/mavlink_passthrough/CMakeLists.txt

[Backport v1.4] cmake: install mavlink headers in correct dir

---

src/integration_tests/telemetry_async.cpp
src/integration_tests/telemetry_sync.cpp
src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h
src/mavsdk/plugins/telemetry/mocks/telemetry_mock.h
src/mavsdk/plugins/telemetry/telemetry.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.h
src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.cc
src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.h
src/mavsdk_server/src/generated/telemetry/telemetry.pb.cc
src/mavsdk_server/src/generated/telemetry/telemetry.pb.h
src/mavsdk_server/src/plugins/telemetry/telemetry_service_impl.h

This pull request would close [#1903](https://github.com/mavlink/MAVSDK/issues/1903).  Created a pull request [#300](https://github.com/mavlink/MAVSDK-Proto/pull/300) in MAVSDK-Proto

Added altitude to telemetry plugin

---

src/mavsdk/core/mavlink_mission_transfer_test.cpp
src/mavsdk/core/timesync.cpp
src/mavsdk/plugins/mission_raw_server/mission_raw_server_impl.cpp
src/mavsdk/plugins/mocap/mocap_impl.cpp
third_party/mavlink/CMakeLists.txt

- Fetch latest git commit tag for MAVLink.
- Update the code with the new definitions (MISSION_CURRENT, TIMESYNC and ODOMETRY).

Use latest MAVLink definitions

---

src/mavsdk/plugins/mavlink_passthrough/CMakeLists.txt

Hopefully, this time I get it right.

[v1.4] cmake: copy correct mavlink directory

---

tools/multi_mavsdk_server.sh

Bash script that eases spawning multiple mavsdk_server processes. Useful to perform multi vehicle testing, both in SITL and real executions.
Instances are spawned following the next pattern:
```
./mavsdk_server -p 50040 udp://:14540
./mavsdk_server -p 50041 udp://:14541
./mavsdk_server -p 50042 udp://:14542
```
Mavsdk-Server executable name can easily be selected by editing a constant, same with the spawned process name.
It Kills the already running mavsdk_server instances when it's launched and then clears the spawned processes at exit
I use it in conjunction with scripts like [sitl_multiple_run.sh](https://github.com/PX4/PX4-Autopilot/blob/main/Tools/simulation/gazebo/sitl_multiple_run.sh)
Execution example:
User has the _mavsdk_server_manylinux2010-x64_ binary in the parent folder and …

Add multi_mavsdk_server.sh util

---

src/mavsdk/plugins/mission_raw/include/plugins/mission_raw/mission_raw.h
src/mavsdk/plugins/mission_raw/mission_raw.cpp
src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp
src/mavsdk/plugins/mission_raw/mission_raw_impl.h
src/mavsdk_server/src/generated/mission_raw/mission_raw.grpc.pb.cc
src/mavsdk_server/src/generated/mission_raw/mission_raw.grpc.pb.h
src/mavsdk_server/src/generated/mission_raw/mission_raw.pb.cc
src/mavsdk_server/src/generated/mission_raw/mission_raw.pb.h
src/mavsdk_server/src/plugins/mission_raw/mission_raw_service_impl.h

This enables to import mission plan files without having to write them to some location first.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/305.
Closes #1948.

mission_raw: add method to import plan from string

---

src/integration_tests/telemetry_async.cpp
src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h
src/mavsdk/plugins/telemetry/telemetry.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.cpp
src/mavsdk_server/src/generated/telemetry/telemetry.pb.cc
src/mavsdk_server/src/generated/telemetry/telemetry.pb.h
src/mavsdk_server/src/plugins/telemetry/telemetry_service_impl.h

Following the new messages in MAVSDK-Proto, it is required to implement the logic and conversion if necessary of the battery status. New messages are:
- temperature_degc
- current_battery_a
- capacity_consumed_ah
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/297.

Add battery status message for v1

---

.github/workflows/main.yml
src/mavsdk/core/include/mavsdk/system.h
third_party/mavlink/CMakeLists.txt

This points to the v1.4 branch which contains the protobuf version fix.

[v1.4] proto submodule update

---

src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/mavsdk_impl.h

PX4 starting with v1.13 does not send heartbeats by default, so we need to initiate the MAVLink connection by sending heartbeats. Therefore, we override the default here and enable sending heartbeats.
Fixes #1967.

core: always send heartbeat on serial connections

---

src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/mavsdk_impl.h

[BACKPORT v1.4] core: always send heartbeat on serial connections

---

src/mavsdk/plugins/telemetry/telemetry_impl.cpp

The scaling was wrong.
Thanks to @potaito and @reedev for catching it.

telemetry: fix distance_sensor unit

---

src/mavsdk/plugins/calibration/calibration_impl.cpp

This line must have slipped in there. It doesn't seem right.
Fixes #1600.

calibration: remove spurious cancel command

---

src/mavsdk/plugins/offboard/offboard_impl.cpp

1. We no longer need to send a message immadiately as add_call_every now does that for us.
2. We need to make sure the vectors are resized appropriately before accessing them, otherwise this can trigger segfaults.

offboard: two actuator control fixes

---

src/mavsdk/core/flight_mode.cpp
src/mavsdk/core/system_impl.cpp
src/mavsdk/plugins/offboard/offboard_impl.cpp

This PR enables the use of the _offboard_ plugin with Ardupilot Rovers. Tested with a real R1 rover.
- Add the `ardupilot::Rover::Guided` <-> `FlightMode::Offboard` mapping in the _core_, to allow entering Offboard mode with an Ardupilot Rover.
- Update the flight mode monitoring callback in _offboard_ plugin, to also handle Ardupilot modes.

Enable offboard plugin with Ardupilot Rover

---

src/mavsdk/plugins/action/action_impl.cpp

This pr fixes issue described in #1996.
Previously, if apm vehicle was already in offboard mode, send_takeoff_command was never executed.
Now it works as intended.

plugins/action: fix apm_takeoff

---

templates/plugin_impl_h/file.j2

This adds 
```cpp
void init() override;
void deinit() override;
```
to the auto-generated implementation header, to mimic this part here in the corresponding cpp template:
https://github.com/mavlink/MAVSDK/blob/e7231dc8f390b96f4682e6810ac3d2fe554b5b8b/templates/plugin_impl_cpp/file.j2#L35-L39
Otherwise I get an `inherited member is not allowed` error in the impl.cpp file.
Speaking of which, what are servers in MAVSDK? I noticed that there are server plugins, but I didn't know that they are treated differently until I saw the template.

Add overrides in impl_h template

---

src/mavsdk_server/src/CMakeLists.txt
src/mavsdk_server/test/CMakeLists.txt

This fixes linking on Debian Bullseye for me with
cmake 3.26.0
GCC 10.2.1
The error was:
```
/usr/bin/ld: libmavsdk_server.so.1.4.0: undefined reference to `dlsym'
/usr/bin/ld: libmavsdk_server.so.1.4.0: undefined reference to `dlopen'
/usr/bin/ld: libmavsdk_server.so.1.4.0: undefined reference to `dlclose'
/usr/bin/ld: libmavsdk_server.so.1.4.0: undefined reference to `dlerror'
/usr/bin/ld: libmavsdk_server.so.1.4.0: undefined reference to `dladdr'
```

mavsdk_server: fix linking

---

src/mavsdk/plugins/info/info_impl.cpp
src/mavsdk/plugins/info/info_impl.h

Otherwise we miss it in Python because we construct the plugin just before accessing the info.
Bit of a hack but should work for now. Need to backport to v1.4.
Fixes: https://github.com/mavlink/MAVSDK-Python/issues/556.

info: wait up to 1.5s for information

---

src/mavsdk/plugins/info/info_impl.cpp
src/mavsdk/plugins/info/info_impl.h

Backport of https://github.com/mavlink/MAVSDK/pull/2006.

[BACKPORT v1.4] info: wait up to 1.5s for information

---

src/mavsdk/core/system_impl.cpp
src/mavsdk/core/system_impl.h
src/mavsdk/plugins/mavlink_passthrough/include/plugins/mavlink_passthrough/mavlink_passthrough.h
src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough.cpp
src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough_impl.h

The use-case is to request params from a component that is not exposed in a plugin (`param` or `camera`).
Since the command microservice is exposed in mavlink_passthrough, it feels like it makes sense to expose the params one as well :sweat_smile:

Expose params through mavlink_passthrough

---

.github/workflows/main.yml

Seems like Ubuntu 18.04 is not supported anymore in github actions: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
Removing it because I have seen CI jobs hang indefinitely because of that (Ubuntu 18.04 would never run).

CI: Remove deprecated ubuntu-18.04

---

.github/workflows/main.yml

The `deb-package` job fails on Ubuntu 22.04 because of some key when we try to install the latest CMake. But since 18.04 is now obsolete, and [Ubuntu 22.04](https://github.com/actions/runner-images/blob/ubuntu20/20230402.1/images/linux/Ubuntu2004-Readme.md#tools) in CI has a recent cmake (3.26+), I don't think we need this task anymore.
If that works, it will bring `.deb` packages for 22.04 (while removing them for 18.04).
Kind of related to https://github.com/mavlink/MAVSDK/pull/2017, but a bit different.

Build deb package for Ubuntu 22.04

---

src/mavsdk_server/src/CMakeLists.txt
src/mavsdk_server/test/CMakeLists.txt

Not sure if it actually makes a big difference for us, but `CMAKE_DL_LIBS` may be different depending on the platform (but the [CMake docs](https://cmake.org/cmake/help/v3.26/variable/CMAKE_DL_LIBS.html) doesn't really specify how).
Feels like it doesn't hurt, and it could be worth the change :innocent:.

Change dl with CMAKE_DL_LIBS

---

src/mavsdk/plugins/telemetry/telemetry_impl.cpp

[set_rate_battery](https://github.com/mavlink/MAVSDK/blob/57fa6e80790a1af4d4bde21292ad5084112b506b/src/mavsdk/plugins/telemetry/telemetry_impl.cpp#L585) is actually setting the rate of system status. It has also been mentioned in the [issue](https://github.com/mavlink/MAVSDK/issues/1996).

telemetry: fix set battery rate

---

src/mavsdk/core/callback_list_impl.h
src/mavsdk/core/include/mavsdk/handle.h
src/system_tests/system_tests_helper.cpp

It turns out that the handle went out of scope and we segfaulted. Therefore, we need to create a shared_ptr containing it.
This also required the Handle to be default constructible, with id 0 which basically means it's a NullHandle.

core: fix system tests subscription

---

examples/battery/battery.cpp
examples/calibrate/calibrate.cpp
examples/fly_mission/fly_mission.cpp
examples/fly_qgc_mission/fly_qgc_mission.cpp
examples/follow_me/follow_me.cpp
examples/ftp_client/ftp_client.cpp
examples/geofence/geofence.cpp
examples/gimbal/gimbal.cpp
examples/logfile_download/logfile_download.cpp
examples/manual_control/manual_control.cpp
examples/mavshell/mavshell.cpp
examples/offboard/offboard.cpp
examples/sniffer/sniffer.cpp
examples/system_info/system_info.cpp
examples/takeoff_and_land/takeoff_and_land.cpp
examples/transponder/transponder.cpp
examples/tune/tune.cpp
examples/vtol_transition/vtol_transition.cpp
src/mavsdk/core/include/mavsdk/mavsdk.h
src/mavsdk/core/mavsdk.cpp
src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/mavsdk_impl.h

This adds an easy blocking API which allows to wait for the first system. This should cover a big percentage of use cases, especially for the integration tests and examples.

Easier discovery

---

src/mavsdk/plugins/tune/tune_impl.cpp

This fixes the case where the mavlink pack function does a memcpy on an array that is shorter.
Fixes "Illegal instruction" errors.
Or in address sanitizer:
```
Address 0x7f0f941f4ac0 is located in stack of thread T10 at offset 192 in frame
#0 0x7f0f9d0f07f1 in mavsdk::TuneImpl::play_tune_async(mavsdk::Tune::TuneDescription const&, std::function<void (mavsdk::Tune::Result)> const&) (/home/julianoes/src/upstream/MAVSDK/build/debug/src/mavsdk/libmavsdk.so.1+0x9747f1)
This frame has 10 object(s):
[32, 40) '__for_begin' (line 54)
[64, 72) '__for_end' (line 54)
[96, 120) 'song_elements' (line 43)
[160, 192) 'tune_str' (line 51)
[224, 256) '<unknown>' <== Memory access at offset 192 partially underflows this variable
[288, 320) '<unknown>' <== Memory access at offset 192 partially underflows …
```

tune: fix stack overrun

---

src/mavsdk/plugins/tune/tune_impl.cpp

This fixes the case where the mavlink pack function does a memcpy on an array that is shorter.
Backport of #2036.

[BACKPORT v1.4] tune: fix stack overrun

---

src/mavsdk/core/mavsdk_impl.cpp

Often when waiting for a system, you only really want one, so the first one connecting. Therefore, you might immediately unsubscribe again inside the callback.
This pattern didn't work anymore with the new returned handle because we did not return from the function before calling the callback meaning the handle is not actually valid yet.
By adding the callback to the queue we can work around this case although the race condition still exists until we change when the callback is called in a later commit.
Edit: Actually looking at all the logic of queuing and de-queuing a callback it might as well work fine like this in practice.

core: improve subscription race

---

.github/workflows/main.yml

I'm not sure why this step is needed, and it now fails with:
```
fatal: remote error: upload-pack: not our ref 07daa576c40ea3c90a9f2b777b919debd49697b7
Errors during submodule fetch:
mavsdk-proto
```
Just trying without it :see_no_evil: 
EDIT: seems fine now. @julianoes do you remember why you added the `git fetch` part?

ci: try to fix fetching tags on macOS

---

src/mavsdk/core/param_value.cpp
src/mavsdk/plugins/camera/camera_definition.cpp
src/mavsdk/plugins/camera/camera_definition_test.cpp
src/mavsdk/plugins/camera/camera_impl.cpp

It was raised in #2046 that the bool type is rejected even though it's listed in the docs: https://mavlink.io/en/services/camera_def.html#parameter-types
This is an attempt to fix that, plus getting rid of `strcmp` while we're at it.
Closes #2046.

Camera definition: accept bool type in xml

---

src/mavsdk/core/mavlink_mission_transfer.cpp

This PR corrects the mission item sequence check for ardupilot. 
Solves https://github.com/mavlink/MAVSDK/issues/728 and https://github.com/mavlink/MAVSDK/issues/2023
ArduPilot Mission Plan sequence starts at 0 just like PX4. Its just that the item 0 should be home position and item 1 should be takeoff and then follows other mission items. In this PR, the special check for Ardupilot is removed since the same check which is used for PX4 should work for ardupilot as well.

corrected mission item seq check for ardupilot

---

src/mavsdk/core/mavlink_mission_transfer.cpp

Backport of https://github.com/mavlink/MAVSDK/pull/2064.

[BACKPORT v1.4] corrected mission item seq check for ardupilot

---

src/mavsdk/plugins/camera/camera_definition.cpp

When a bool parameter is encountered the on/off options should be created automatically as per [documentation](https://mavlink.io/en/services/camera_def.html#parameter-definition).
This should solve the second part of issue https://github.com/mavlink/MAVSDK/issues/2046.
And is a reopen of #2056 PR which got automatically closed.

The bool parameter now automatically creates on/off options. Reopen.

---

tools/generate_from_protos.sh

* Change the python executable to python3 (In MacOS the default python is python2.7)
* Use relative path for grpc_server_jinja.py
_**Todo**_: the grpc_server_jinja.py also use absolute path. The **generate_from_protos.sh** script only works well in the **MAVSDK root path.**
```
Traceback (most recent call last):
File "/Users/tbago/MAVSDK/tools/grpc_server_jinja.py", line 30, in <module>
main()
File "/Users/tbago/MAVSDK/tools/grpc_server_jinja.py", line 19, in main
template = env.get_template("grpc_server.h.j2")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/tbago/MAVSDK/build/pb_plugins/jinja2/environment.py", line 1010, in get_template
return self._load_template(name, globals)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/tbago/MAVSDK/build/pb_plugins/jinja2/environment.py", line …
```

Tools: change the absolute path for generate_from_protos.sh

---

examples/disconnect/CMakeLists.txt
examples/disconnect/disconnect.cpp

This is an example how to destruct Mavsdk when a system has disconnected.
Thanks to @jperez-droneup for creating the initial version of this example in https://github.com/mavlink/MAVSDK/issues/2075.
Note, I also tried to run this 3 times and then break out of the while with valgrind and it showed no leaks, so that makes me hopeful. There have been quite a few destruction bugs in the past but thanks to the system tests which create and destruct `Mavsdk` and `System`s all the time I was able to catch quite a few of them.

examples: add disconnection example

---

.github/workflows/main.yml
src/mavsdk/core/include/mavsdk/system.h
src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/mavsdk_impl.h
src/mavsdk/core/system.cpp
src/mavsdk/core/system_impl.cpp
src/mavsdk/core/system_impl.h

This flag was added when we didn't have the notion of a component, and therefore it was required for the FTP server implementation. I believe we should be able to remove it now.
Fixes #2076.

core: remove always connected flag

---

src/mavsdk/core/include/mavsdk/handle.h
src/mavsdk/core/include/mavsdk/mavsdk.h
src/mavsdk/core/mavsdk.cpp
src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/mavsdk_impl.h

This adds the method add_any_connection_with_handle which returns a handle that can later be used to remove a connection again using remove_connection.
Untested, @jperez-droneup if you want to give this a try.

core: add way to remove a connection

---

src/mavsdk/core/mavsdk_impl.cpp

When we use setup_udp_remote twice, we end up creating a null system every time which didn't make sense.
Closes #2080

core: don't create a null system if not required

---

src/mavsdk/core/tcp_connection.cpp

This allows TCP connections to be made by hostname, not just IP - e.g. `tcp://localhost:1234`, or `tcp://my-device.local:1234`
Tested on linux and macos

TCP: Allow connecting by hostname

---

src/MAVSDKConfig.cmake.in
src/cmake/compiler_flags.cmake
src/mavsdk/core/CMakeLists.txt
tools/.doxygen

This reverts a previous change which requires MAVLink to be installed standalone next to MAVSDK. Instead, the headers are, for now included as part of the MAVSDK install.
While this is not the right way to go about dependencies it avoids two problems:
1. It behaves the same as before. No MAVLink dependency is suddenly required disrupting an existing workflow.
2. It avoids a potential pitfall where a user of the library installs the MAVSDK library compiled with MAVLink from the common dialect but then later tries to use MAVLink headers containing their custom dialect. Intuitively, one would expect the message of the custom dialect to work via the mavlink_passthrough plugin, however, because the MAVlink parser has a static CRC_EXTRA table it won't parse the added custom messages unless the …

build: Install MAVLink headers within MAVSDK

---

src/mavsdk/core/cli_arg.cpp
src/mavsdk/core/fs.h

It looks like gcc13 libs don't include `<cstdint>` header in some of the other `<>` headers and that breaks the build or there is some other change with the libs. 
Either way adding `#include <cstdint>` to the affected files fixes the issue and allows for the build with gcc13.

Build with gcc13 without errors

---

src/mavsdk/plugins/log_files/log_files_impl.cpp
src/mavsdk/plugins/log_files/log_files_impl.h

Instead, use the timeout which can be configured.
Also, make the initial list timeout quite big as it can take a while in reality.
Found when looking into #2091.

log_files: remove hard-coded timeout values

---

src/mavsdk/plugins/action/action_impl.cpp

Pull request in support of https://github.com/mavlink/MAVSDK/issues/2111
I added support for actuator control in ArduPilot by modifying the set_actuator function from the Action plugin. I added an if statement that uses the MAV_CMD_DO_SET_SERVO command on ArduPilot systems due to the MAV_CMD_DO_SET_ACTUATOR command not being implemented in ArduPilot. PX4 will continue to use MAV_CMD_DO_SET_ACTUATOR as before.
A word on MAV_CMD_DO_SET_ACTUATOR: this command is capable of setting multiple actuator values at once, while MAV_CMD_DO_SET_SERVO only sets one actuator at a time. Since the set_actuator function is only setting one actuator at a time, MAV_CMD_DO_SET_SERVO is a one-to-one substitute of MAV_CMD_DO_SET_ACTUATOR.

Added new code for MAV_CMD_DO_SET_SERVO ArduPilot

---

src/mavsdk/plugins/mission/mission_impl.cpp

Hello,
As I continue to incorporate ArduPilot compatibility with MAVSDK Mission module (https://github.com/mavlink/MAVSDK/issues/2110), I noticed some discrepancies with how the camera action commands are formatted vs. the Mavlink standard for the commands. ArduPilot was rejecting the commands due to invalid parameters:
MAV_CMD_IMAGE_START_CAPTURE:
param 4 was set to NaN, [must be set to 0 instead](https://mavlink.io/en/messages/common.html#MAV_CMD_IMAGE_START_CAPTURE)
MAV_CMD_VIDEO_START_CAPTURE
param 2 was set to NaN, [must be set to 0 instead](https://mavlink.io/en/messages/common.html#MAV_CMD_VIDEO_START_CAPTURE)
In terms of testing, the only testing I have done in ArduPilot SITL is to see if the commands are accepted. These changes make both of these commands accepted. I have not …

Mission module: Updated camera action commands (param4) to be compliant with mavlink standard

---

src/mavsdk_server/src/CMakeLists.txt

This is also needed for Android, and `CMAKE_DL_LIBS` should be empty when it does not apply (e.g. Windows). Not sure about the musl builds, though :thinking:.

Link CMAKE_DL_LIBS when necessary

---

src/mavsdk/core/mavsdk_impl.cpp

With a UDP remote, we need to initiate the connection by sending heartbeats. This functionality had been broken once we did no longer mark a UDP remote connection as "always connected".
Follow up to https://github.com/mavlink/MAVSDK/pull/2077.
Thanks to @reedev for narrowing this down.

core: send heartbeats to UDP remote

---

src/mavsdk/plugins/telemetry/telemetry_impl.cpp

It turns out that PX4 v1.13 and likely PX4 v1.14 send out UINT16_MAX instead of 0 in the extensions. We can at least catch this and prevent a wrong battery voltage from slipping through.
Follow-up to #2114.

telemetry: Be compatible for battery_status

---

src/mavsdk/plugins/action/action_impl.cpp

The pull request is related to this [issue](https://github.com/mavlink/MAVSDK/issues/2102)

Action plugin 'set_actuator_async' switch statement index changed to zero-based

---

src/mavsdk/plugins/telemetry/telemetry_impl.cpp

The calibration check should be stopped when the drone is actually found to be running in hitl mode, and not when the hitl param is received (because the hitl param may say that the drone is not running hitl, in which case we need to continue checking the calibration).
Without this fix, the health booleans related to the calibration tend to be "stuck" on the default `false` value (because MAVSDK stops checking and never gets to the point where it realizes that the check is actually fine).

Fix calibration in telemetry health

---

src/mavsdk/plugins/camera/camera_impl.cpp

The fact that `_status.call_every_cookie` is shared between two subscriptions (camera status and camera information) makes them conflict: when unsubscribing from one, it cancels the call_every for both.
Also, depending on the order, it will `add_call_every` twice with the same cookie, which I believe ends up leaking one.
This PR makes it simpler by requesting the status updates in the plugin directly. I don't think it is worth trying to optimize the number of requests here (and I am pretty sure it ended up doubling them in SiteScan).

[v1.4] Fix conflict in camera subscriptions

---

src/mavsdk/plugins/telemetry/telemetry_impl.cpp

Bringing https://github.com/mavlink/MAVSDK/pull/2132 upstream.

telemetry: do not interrupt calibration checks too early

---

src/mavsdk/plugins/offboard/offboard_impl.cpp

[Backport v1.4] offboard: two actuator control fixes

---

src/mavsdk/plugins/camera/camera_impl.cpp
src/mavsdk/plugins/camera/camera_impl.h

We should not use `static_cast` to translate between a MAVLink enum and a MAVSDK enum, because their values don't necessarily correspond. Here STORAGE_TYPE_OTHER has a MAVLink value of 254 and fails to translate.
```c++
_status.data.storage_type = static_cast<Camera::Status::StorageType>(storage_information.type);
```

v1.4 fix storage type translation (STORAGE_TYPE_OTHER)

---

src/mavsdk_server/tools/package_mavsdk_server_framework.bash

Hi!
When trying to build an app for macOS, Xcode complains about not being able to follow a symlink. After some investigation it turns out that the `Current` folder (`/mavsdk_server.xcframework/macos-x86_64/mavsdk_server.framework/Versions/Current`) is in fact not a symlink, but it should be.
Updating the `zip` command to preserve symlinks should fix the issue.

Preserve symlinks in zip file

---

src/mavsdk/core/lazy_plugin.h
src/mavsdk/core/mocks/system_mock.h
src/mavsdk_server/src/connection_initiator.h
src/mavsdk_server/test/connection_initiator_test.cpp

Currently, `mavsdk_server` defaults to being a ground station (i.e. it does not expose the `Configuration`). When started, `mavsdk_server` connects to the first MAVLink `System` it detects.
The problem I have seen is that in some setups, there are sometimes MAVLink systems that are not an autopilot but that are advertising on the link that `mavsdk_server` is listening to. I had the issue with a Herelink radio, that advertises radio messages with sysid 42. For an app running on Herelink, if `mavsdk_server` picks up the system "42" first, then there is nothing to do other than restarting it and hoping that it picks up the right system.
Now I argue that the "right" system for `mavsdk_server`, given the current situation where it defaults to being a ground station, is a system that has an …

mavsdk_server: default to the first autopilot 

---

src/mavsdk/core/lazy_plugin.h
src/mavsdk/core/mocks/system_mock.h
src/mavsdk_server/src/connection_initiator.h
src/mavsdk_server/test/connection_initiator_test.cpp

Bring https://github.com/mavlink/MAVSDK/pull/2159 to `main`. This is a little simpler than in `v1.4` because `main` already has a `mavsdk.first_autopilot()` function :blush:.

Mavsdk server default to autopilot

---

src/mavsdk/plugins/action/action_impl.cpp

**Problem Description**
The goto action in the examples of MAVSDK-Python is currently broken with PX4 `main` (reported in https://github.com/mavlink/MAVSDK-Python/issues/633)
PX4 returns an unsupported error, as the following.
```
Traceback (most recent call last):
File "goto.py", line 47, in <module>
asyncio.run(run())
File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
return future.result()
File "goto.py", line 38, in run
await drone.action.goto_location(47.397606, 8.543060, flying_alt, 0)
File "/home/yunpeng/.local/lib/python3.8/site-packages/mavsdk/action.py", line 548, in goto_location
raise ActionError(result, "goto_location()", latitude_deg, …
```

Request mode change for action MAV_CMD_DO_REPOSITION

---

src/mavsdk/core/CMakeLists.txt
src/mavsdk/core/flight_mode.h
src/mavsdk/core/mavlink_mission_transfer_client.cpp
src/mavsdk/core/mavlink_mission_transfer_client.h
src/mavsdk/core/mavlink_mission_transfer_client_test.cpp
src/mavsdk/core/mavlink_mission_transfer_server.cpp
src/mavsdk/core/mavlink_mission_transfer_server.h
src/mavsdk/core/mavlink_mission_transfer_server_test.cpp
src/mavsdk/core/mocks/sender_mock.h
src/mavsdk/core/server_component_impl.cpp
src/mavsdk/core/server_component_impl.h
src/mavsdk/core/system_impl.cpp
src/mavsdk/core/system_impl.h
src/mavsdk/plugins/geofence/geofence_impl.cpp
src/mavsdk/plugins/geofence/geofence_impl.h
src/mavsdk/plugins/mission/mission_impl.cpp
src/mavsdk/plugins/mission/mission_impl.h
src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp
src/mavsdk/plugins/mission_raw/mission_raw_impl.h
src/mavsdk/plugins/mission_raw_server/mission_raw_server_impl.cpp
src/mavsdk/plugins/mission_raw_server/mission_raw_server_impl.h

This was weirdly mixed up in the same class before and required another thread in the server plugin due to locking problems.
Here I go again :smile: 
Currently on top of #2060.

Split mission transfer into client and server

---

src/mavsdk/core/mavlink_ftp_client.cpp
src/mavsdk/core/mavlink_ftp_client.h
src/mavsdk/core/mavlink_ftp_server.cpp
src/mavsdk/core/mavlink_ftp_server.h

This fixes the burst implementation which was implemented according to the docs rather than the existing implementations out there (like ArduPilot, MissionPlanner, and QGroundControl.
The difference is that the size field is used to signal the size of each burst packet rather than the overall burst. This means a burst transfer always has to be the whole file and can't be a partial file.
For discussion see https://github.com/mavlink/mavlink/issues/2052.

core: fix burst implementation

---

src/mavsdk/core/mavlink_mission_transfer_client.cpp
src/mavsdk/core/mavlink_mission_transfer_client_test.cpp

This broke during the recent refactor. Target and source IDs got mixed up.

core: fix mission transfer

---

examples/gimbal_device_tester/gimbal_device_tester.cpp

Various gimbal_device_test fixes as they are discovered.
Backport of https://github.com/mavlink/MAVSDK/pull/2171.

[v1.4] gimbal device test fixes

---

.github/workflows/main.yml

This is to avoid the problem with future trying to import imp which is now importlib.
The dependency goes to mavlink and then in turn to pymavlink, so it'll be a while until this trickles down.

CI: downgrade to Python 3.11 for macOS

---

.github/workflows/main.yml
third_party/mavlink/CMakeLists.txt

Backporting https://github.com/mavlink/MAVSDK/pull/2179

[v1.4] Downgrade Python to 3.11 for macOS CI builds

---

src/mavsdk_server/src/CMakeLists.txt

Resolves https://github.com/mavlink/MAVSDK-Java/issues/131
Apply the changes that were suggested [here](https://github.com/mavlink/MAVSDK-Java/issues/131).

mavsdk_server: fix dl-lib linking

---

src/mavsdk/core/connection.h

Even though newer MSVC 2019 version compile perfectly fine it's worth including this header since it's used in 'Connection' class.

Include header <atomic> in connection.h to avoid compiler erros with msvc2019 16.4

---

src/mavsdk/core/CMakeLists.txt

Since it's not possible to mix debug and release msvc runtime on
windows, it's important to link against a mavsdk debug lib when
compiling the program for debug and later link against the mavsdk
release lib when deploying the program. But this did not work until now
because the name for the debug and release dll was the same. For this
purpose CMake invented the 'DEBUG_POSTFIX' property for a target.
The generated CMake files to find mavsdk are correctly filled with the
appropriate library name so no need to change anything else here.

Use DEBUG_POSTFIX cmake property to distinguish between debug and release dll

---

examples/gimbal_device_tester/gimbal_device_tester.cpp
src/mavsdk/plugins/mavlink_passthrough/include/plugins/mavlink_passthrough/mavlink_passthrough.h
src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough.cpp
src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough_impl.h

This updates MavlinkPassthrough to require a message id in unsubscribe_message.  It fixes the bug where unsubscribing from a passthrough message also unsubscribed from messages with the same handle id but different message ids.

Update to MavlinkPassthrough unsubscribe_message

---

src/mavsdk/core/mavsdk_impl.cpp

This fixes a copy/paste error in the component ID check.
Found while working on #2192.
Needs backporting to v1.4.

core: fix component ID check

---

src/mavsdk/core/mavlink_message_handler.cpp
src/mavsdk/core/mavlink_message_handler.h
src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/server_component_impl.cpp
src/mavsdk/core/server_component_impl.h
src/mavsdk/core/system_impl.cpp
src/mavsdk/core/system_impl.h
src/mavsdk/plugins/camera/camera_impl.cpp

This fixes a recent regression after a refactoring where messages from different systems are no longer filtered according to the source system ID and instead are distributed to all systems.
Fixes #2191.

core: fix incoming messages by sysid

---

src/mavsdk/core/mavsdk_impl.cpp

This fixes a copy/paste error in the component ID check.
Backport of #2193

[BACKPORT v1.4] core: fix component ID check

---

src/mavsdk/core/CMakeLists.txt
src/mavsdk/plugins/camera/camera_impl.cpp
src/mavsdk/plugins/camera/camera_impl.h
third_party/CMakeLists.txt

This adds the cmake configure option BUILD_WITHOUT_CURL which allows building MAVSDK without the cURL dependency.
This has been requested numerous times, so it's probably worthwhile adding as an option.
For now it means that camera definition files can't be downloaded via http.
In the future we will also add the option to download the definition files via MAVLink FTP.
Closes #830.

Add option to build without cURL

---

examples/autopilot_server/autopilot_server.cpp
examples/camera_server/camera_client.cpp
examples/camera_server/camera_server.cpp
examples/ftp_server/ftp_server.cpp
examples/gimbal_device_tester/gimbal_device_tester.cpp
src/integration_tests/camera_take_photo.cpp
src/integration_tests/connection.cpp
src/integration_tests/statustext.cpp
src/mavsdk/core/include/mavsdk/mavsdk.h
src/mavsdk/core/lazy_server_plugin.h
src/mavsdk/core/mavsdk.cpp
src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/mavsdk_impl.h
src/system_tests/action_arm_disarm.cpp
src/system_tests/camera_take_photo.cpp
src/system_tests/component_information.cpp
src/system_tests/ftp_compare_files.cpp
src/system_tests/ftp_create_dir.cpp
src/system_tests/ftp_download_file.cpp
src/system_tests/ftp_download_file_burst.cpp
src/system_tests/ftp_list_dir.cpp
src/system_tests/ftp_remove_dir.cpp
src/system_tests/ftp_remove_file.cpp
src/system_tests/ftp_rename_file.cpp
src/system_tests/ftp_upload_file.cpp
src/system_tests/mission_raw_upload.cpp
src/system_tests/param_custom_set_and_get.cpp
src/system_tests/param_get_all.cpp
src/system_tests/param_set_and_get.cpp
src/system_tests/telemetry_subscription.cpp

This should make dealing with the configuration and components a bit clearer.
This is the last step towards v2 :crossed_fingers:.
Closes #2125.

Consolidate components

---

examples/distance_sensor/CMakeLists.txt
examples/distance_sensor/distance_sensor.cpp
src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h
src/mavsdk/plugins/telemetry/telemetry.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.h
src/mavsdk_server/src/generated/telemetry/telemetry.pb.cc
src/mavsdk_server/src/generated/telemetry/telemetry.pb.h
src/mavsdk_server/src/plugins/telemetry/telemetry_service_impl.h

Customized telemetry.h and telementry_impl.cpp to add the orientation parameter to telemetry.distance_sensor to add multisensor support readings on distance_sensor
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/321 :heavy_check_mark:

Customizing distance sensor to add orientation for multiple sensor support

---

LICENSE.md
README.md

This fixes a few links in the readme.
And also I decided to change the copyright from PX4 Development Team to MAVSDK Development Team.
PX4 Development Team doesn't actually really make sense, given there are also contributions by ArduPilot. I'm therefore taking the freedom to change this to MAVSDK Development Team which represents the authors a bit better.
This also adds a section regarding maintenance and support.

Update readme and license

---

third_party/absl/CMakeLists.txt

Required for Alpine 3.19, where it currently fails with:
> [  7%] Building CXX object absl/base/CMakeFiles/malloc_internal.dir/internal/low_level_alloc.cc.o
In file included from /home/mavsdk/third_party/absl/build/absl/src/absl/absl/base/internal/low_level_alloc.cc:26:
/home/mavsdk/third_party/absl/build/absl/src/absl/absl/base/internal/direct_mmap.h:75:25: error: 'off64_t' has not been declared
75 |                         off64_t offset) noexcept {

Update absl to 20230802.1

---

src/mavsdk/plugins/camera_server/camera_server_impl.cpp

If we don't send out the status before and after a capture, the photo button in QGC stays "busy".

camera_server: send status before/after capture

---

third_party/tinyxml2/CMakeLists.txt
third_party/tinyxml2/no-lfs64.patch

Applying the patch from alpine (see https://git.alpinelinux.org/aports/tree/main/tinyxml2/no-lfs64.patch). I slightly modified the patch for Android.

ci: fix tinyxml2 build for alpine 3.19

---

src/mavsdk/plugins/gimbal/gimbal_protocol_v2.cpp
src/mavsdk/plugins/gimbal/gimbal_protocol_v2.h

We should unregister anything we have subscribed to when being destructed.
Related to #2207

gimbal: fix unregister message subscription

---

.gitmodules
examples/gimbal_full_control/CMakeLists.txt
examples/gimbal_full_control/gimbal_full_control.cpp
src/mavsdk/core/CMakeLists.txt
src/mavsdk/plugins/gimbal/gimbal.cpp
src/mavsdk/plugins/gimbal/gimbal_impl.cpp
src/mavsdk/plugins/gimbal/gimbal_impl.h
src/mavsdk/plugins/gimbal/gimbal_protocol_base.h
src/mavsdk/plugins/gimbal/gimbal_protocol_v1.cpp
src/mavsdk/plugins/gimbal/gimbal_protocol_v1.h
src/mavsdk/plugins/gimbal/gimbal_protocol_v2.cpp
src/mavsdk/plugins/gimbal/gimbal_protocol_v2.h
src/mavsdk/plugins/gimbal/include/plugins/gimbal/gimbal.h
src/mavsdk_server/src/generated/gimbal/gimbal.grpc.pb.cc
src/mavsdk_server/src/generated/gimbal/gimbal.grpc.pb.h
src/mavsdk_server/src/generated/gimbal/gimbal.pb.cc
src/mavsdk_server/src/generated/gimbal/gimbal.pb.h
src/mavsdk_server/src/plugins/gimbal/gimbal_service_impl.h

Implementation of the full gimbal angle control
This feature is a request as I have to use the gimbal I have in a certain way and the roll and pitch axis are switched.
As the pitch of the payload of the gimbal is vitally important, this feature is needed.
I have tested the new implementation and it fully works.
Proto PR:
https://github.com/mavlink/MAVSDK-Proto/pull/328
Quick note from my side: This is the first time I have done something like this and thus I am completely new to the process or anything. If I have done something wrong, let me know. I like to improve.

Full gimbal angle control

---

.github/workflows/main.yml

When we add the debug symbols for the musl builds we end up with binaries around 300 to 400 MB which are too big for PyPi.

CI: don't include debug symbols for musl builds

---

third_party/CMakeLists.txt
third_party/zlib-ng/CMakeLists.txt

Because zlib-ng has better CMake support and explicitly tries to keep API compatibility with zlib (see `-DZLIB_COMPAT=ON`), it feels like it may be easier to maintain here.
@julianoes: what do you think?

Move to zlib-ng which has better CMake support

---

src/mavsdk/plugins/ftp/ftp_impl.cpp

I experienced dead locks while calling ftp functions inside ftp callback. For example, I was trying to start a download while in `are_files_identical_async` callback.
Currently, only `list_directory_async` is using `call_user_callback` since commit 50c23012a65bd5f28b8b19192068a555f582f911

Ftp: use call_user_callback

---

src/mavsdk/core/system_impl.cpp

Without that, functions such as goto_location are reporting that they cannot convert the System's flight mode to the Ardupilot one :)

Add missing switch-case parameter

---

src/mavsdk/core/mavlink_ftp_client.cpp
src/mavsdk/core/mavlink_ftp_client.h
src/mavsdk/core/mavlink_ftp_server.cpp

I attempted FTP burst download with PX4 and encountered some issues. After a certain period, the burst download would halt, and the remaining data would be downloaded as missed parts. Upon inspecting the PX4 code, I discovered the following comment: `/* perform transfers in 35K chunks - this is determined empirically */`.
When attempting to resume burst download for incomplete files, I observed that missed parts were managed using a file-sized buffer with a binary value (1 or 0) for each byte. This implies that for a 10MB file, it requires 10MB of RAM to download.
With this pull request, instead of storing the entire missed parts in memory, we now only store the offset and size of the missing parts. Burst download is restarted if the file is not complete before checking missed parts.
To …

Ftp client: Fix burst download

---

src/mavsdk/core/mavlink_ftp_client.cpp
src/system_tests/ftp_download_file_burst.cpp

When we ask PX4 to list an empty directory, it sends back an ack with a empty payload.

Stop list directory job if received size is null

---

src/mavsdk/core/mavlink_ftp_server.cpp
src/mavsdk/core/mavlink_ftp_server.h
src/system_tests/ftp_download_file_burst.cpp

Currently, 100 packets are sent per second. With a 255 bytes payload, send rate is 25kB/s. With a thread, we use the line at its maximum speed.

Ftp server : use a thread to send ftp burst

---

src/mavsdk/plugins/log_files/log_files_impl.cpp

This fixes an future/promise exception which causes a crash. This would occur if you clicked "Refresh" in the QGC Log Download menu while MAVSDK is running on another system.

[log_files] remove callback after get_entries

---

src/mavsdk/core/mavlink_command_sender.cpp

This reverts commit e5c44812827af7e68465519228ba8891a72c774e.
We don't want to carry the workarounds in source, and given @jperez-droneup has his own fork, we can remove this again.

Revert "core: workaround for winch component ID"

---

src/mavsdk/core/mavlink_command_receiver.cpp

It turns out we didn't filter incoming commands in server components.
Adresses #2268.

core: filter commands in command receiver

---

src/integration_tests/info.cpp
src/mavsdk/plugins/info/include/plugins/info/info.h
src/mavsdk/plugins/info/info.cpp
src/mavsdk/plugins/info/info_impl.cpp
src/mavsdk/plugins/info/info_impl.h
src/mavsdk_server/src/generated/info/info.pb.cc
src/mavsdk_server/src/generated/info/info.pb.h
src/mavsdk_server/src/plugins/info/info_service_impl.h

This adds two fields:
- Duration since arming
- Duration since takeoff
And also:
- Simplifies the info plugin a bit by just requesting FLIGHT_INFORMATION at 1 Hz.
- Slightly cleans up the info plugin.
- Slightly cleans up the info integration test.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/340.

info: add duration since arming and takeoff

---

src/mavsdk/plugins/gimbal/gimbal_impl.cpp

Don't destruct the found protocol on each discovery. Otherwise, we lose all subscriptions when a timeout occurs.
Longer term, we'll probably just want to remove the v1 logic to simplify this.

gimbal: only reset protocol on destruction

---

src/mavsdk/plugins/gimbal/gimbal_impl.cpp
src/mavsdk/plugins/gimbal/gimbal_impl.h
src/mavsdk/plugins/info/info_impl.cpp

Some fixups against lockups and subscriptions, both failing after re-discovery.

gimbal/info: fixups

---

examples/autopilot_server/autopilot_server.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.cpp
src/mavsdk/plugins/telemetry_server/telemetry_server_impl.cpp

It was a bit odd to take the Unix epoch time from the UTM message.
Therefore, I've changed this to just SYSTEM_TIME, and also implemented it in the telemetry server and added a simple end to end test in the example.

telemetry and telemetry_server: fix Unix epoch time

---

.github/workflows/main.yml
src/CMakeLists.txt
src/mavsdk/core/CMakeLists.txt

CI: try to fix MSVC

---

src/mavsdk/plugins/gimbal/gimbal_impl.cpp
src/mavsdk/plugins/gimbal/gimbal_impl.h

- Make sure that _gimbal_protocol is also protected by the mutex.
- Add MAVSDK_FORCE_GIMBAL_V2 to force usage of the gimbal v2 protocol and prevent the fallback to gimbal v1. This helps when we don't immediately detect all the components.
- Keep trying to request the GIMBAL_MANAGER_INFORMATION message.
With MAVSDK v3, I want to remove support for gimbal v1, it's just a pain.

gimbal: mutex fixes and added env variable for v2

---

examples/log_streaming/log_streaming.cpp
src/mavsdk/plugins/log_streaming/log_streaming_impl.cpp
src/mavsdk/plugins/log_streaming/log_streaming_impl.h

When a message is dropped, we need to discard any message part. Otherwise, we end up having corrrupt ulog files.

log_streaming: make it robust to message drops

---

src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/system_impl.cpp
src/mavsdk/plugins/info/info_impl.cpp

Three issues I found running multiple instances overnight. See commits.

core: deadlock fix, remove empty system, relax version request

---

src/mavsdk/plugins/log_streaming/log_streaming_impl.cpp
src/mavsdk/plugins/log_streaming/log_streaming_impl.h

I think I finally understand how this is supposed to work, and my testing seems to pass, phew.
Thanks to @bkueng for the reviews! I hope this one will be easiest one.

log_streaming: refactor/fixup drop logic

---

src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp

This fixes the case where a rally points upload right after a geofence upload fails with busy. That's because the work item still exists and hasn't been cleaned up yet.
However, we can ignore that case if the work item has been done.

mission_raw: fix upload race condition

---

.github/workflows/main.yml
docker/Dockerfile.dockcross-linux-arm64-lts-custom
docker/build_and_push_docker_images.sh

This is an attempt to add an arm64-lts target which is needed on Jetson Jetpack 5.

add arm64-lts docker workflow

---

src/mavsdk/plugins/camera/camera_impl.cpp
src/mavsdk/plugins/camera/camera_impl.h

Instead of only supporting camera definition files to be downloaded using cURL, we now also support getting them using MAVLink FTP.

camera: support camera def files via MAVLink FTP

---

src/mavsdk/plugins/action/action_impl.cpp

We can't call the callback more than once, otherwise we segfault with "promise already satisfied".
Fixes #2319

action: ignore InProgress updates

---

examples/autopilot_server/autopilot_server.cpp

This fix addresses an issue where the server never achieves healthy telemetry due to the home position not being captured and the gps never being marked as good. Transmit the home position and sys_status message periodically.
Addresses #2117

examples: fix autopilot_server arming issue

---

src/mavsdk/core/inflate_lzma.cpp

Sonarcloud still wasn't happy. I think this actually doesn't matter in our case because we don't use the bufers outside of decompress.
Follow up to #2322.

core: prevent all potential use after stack scope

---

.github/workflows/main.yml

We don't need it, we already call have debian11 vs debian12.

CI: remote -lts from filename

---

.github/workflows/main.yml

We can't use arm64-lts for the arch name, duh.
Fixes https://github.com/mavlink/MAVSDK/issues/2328.
FYI @AlexKlimaj

CI: fix arch name for arm64-lts

---

examples/ftp_client/ftp_client.cpp
src/mavsdk/core/mavlink_ftp_client.cpp
src/mavsdk/core/mavlink_ftp_client.h
src/mavsdk/plugins/component_metadata/component_metadata_impl.cpp
src/mavsdk/plugins/ftp/ftp.cpp
src/mavsdk/plugins/ftp/ftp_impl.cpp
src/mavsdk/plugins/ftp/ftp_impl.h
src/mavsdk/plugins/ftp/include/plugins/ftp/ftp.h
src/mavsdk_server/src/generated/ftp/ftp.pb.cc
src/mavsdk_server/src/generated/ftp/ftp.pb.h
src/mavsdk_server/src/plugins/ftp/ftp_service_impl.h
src/system_tests/ftp_list_dir.cpp

This way we get a clear list of files and folders instead of an odd list with F or D prefixes.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/343.
Closes #2308.

ftp: split list_directory response

---

src/mavsdk/plugins/rtk/include/plugins/rtk/rtk.h
src/mavsdk/plugins/rtk/rtk.cpp
src/mavsdk/plugins/rtk/rtk_impl.cpp
src/mavsdk_server/src/generated/rtk/rtk.pb.cc
src/mavsdk_server/src/generated/rtk/rtk.pb.h
src/mavsdk_server/src/plugins/rtk/rtk_service_impl.h

This makes it possible to use this in language wrappers such as Python.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/344.
Closes #2314.

rtk: encode RTCM data in base64

---

examples/log_streaming/log_streaming.cpp
src/mavsdk/plugins/log_streaming/include/plugins/log_streaming/log_streaming.h
src/mavsdk/plugins/log_streaming/log_streaming.cpp
src/mavsdk/plugins/log_streaming/log_streaming_impl.cpp
src/mavsdk_server/src/generated/log_streaming/log_streaming.pb.cc
src/mavsdk_server/src/generated/log_streaming/log_streaming.pb.h
src/mavsdk_server/src/plugins/log_streaming/log_streaming_service_impl.h

By having base64 in the variable name we make it clear what the encoding is.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/345.

log_streaming: make base64 encoding clear

---

src/mavsdk/core/system_impl.cpp

This problem introduced in v2.10.1
Now it works only if there was a change in the connection status
closes: #2354

core: Fixed unnecessary repeated invocations of `notify_on_discover`

---

.github/workflows/main.yml
README.md
third_party/absl/CMakeLists.txt

[BACKPORT v2.12] Fix absl CI

---

src/mavsdk/core/system_impl.cpp

Backport of #2356.
Note: merge #2358 first.

[BACKPORT v2.12] core: Fixed unnecessary repeated invocations of `notify_on_discover`

---

src/mavsdk/core/CMakeLists.txt
src/mavsdk/core/socket_holder.cpp
src/mavsdk/core/socket_holder.h
src/mavsdk/core/tcp_connection.cpp
src/mavsdk/core/tcp_connection.h
src/mavsdk/core/udp_connection.cpp
src/mavsdk/core/udp_connection.h

[BACKPORT v2.12] core: Correctly close sockets

---

src/mavsdk/plugins/action_server/action_server_impl.cpp
src/mavsdk_server/tools/package_mavsdk_server_framework.bash

macOS tooling shifting from under you, it doesn't get much worse than that.
:angry:

CI: fix macOS

---

examples/manual_control/manual_control.cpp

Just saw this while glancing over trying to understand what's necessary to support MANUAL_CONTROL.aux fields, counterpart to https://github.com/PX4/PX4-Autopilot/pull/22108

examples: fix manual_control for loop

---

src/mavsdk/plugins/telemetry/telemetry_impl.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.h

This removes some of the hacks which were required in the past:
- Calibration health using params as this should be covered by system status now.
- Position validity based on system status instead of GPS magic.
- HITL workarounds that should also be taken care of autopilot internal.
Closes #2318

telemetry: remove various hacks/workarounds

---

src/mavsdk/core/mavsdk_impl.cpp

It is confusing that we just ignore the system for the telemetry radio. We should instead treat it as a proper system. Users should be able to filter for it properly, especially given they now have the nice `wait_for_autopilot` method.
Closes #2302.

core: don't ignore radio messages and system

---

.github/workflows/main.yml
CMakeLists.txt
debian/rules
src/CMakeLists.txt
src/mavsdk_server/CMakeLists.txt
third_party/CMakeLists.txt

It has been a problem e.g. [here](https://github.com/mavlink/MAVSDK/issues/2374#issuecomment-2293752977) and [here](https://discuss.px4.io/t/mavsdk-main-branch-fails-to-build-on-rpi4-blueos/40003/9). I think it makes sense to add an option for those who don't need to run the tests.
Also I renamed BUILD_TESTS to BUILD_TESTING, which is more common with CMake (that's actually the CTest way, I believe).

Add a BUILD_TESTING option to superbuild

---

.github/workflows/main.yml

Trying to reproduce the CI failure from https://github.com/mavlink/MAVSDK/pull/2377

CI fails because the third_party folder is too big to cache

---

src/mavsdk/plugins/gimbal/gimbal_impl.cpp
src/mavsdk/plugins/gimbal/gimbal_impl.h

This will be fixed properly with v3 but it's worth trying to avoid the deadlock anyway.

gimbal: try to avoid potential lockup on reconnection

---

examples/gimbal_full_control/gimbal_full_control.cpp

- Added `gimbal_id` parameter to all gimbal related methods.
- Replaced the non-existing `set_mode` method with the `set_angles` method.
- Revised `set_angle` methods to include the correct parameters

Update gimbal_full_control.cpp example

---

src/mavsdk/core/CMakeLists.txt
src/mavsdk/core/mavlink_component_metadata.cpp
src/mavsdk/core/mavlink_message_handler.cpp
src/mavsdk/core/mavlink_message_handler.h
src/mavsdk/core/mavlink_request_message.cpp
src/mavsdk/core/mavlink_request_message.h
src/mavsdk/core/request_message.cpp
src/mavsdk/core/request_message.h
src/mavsdk/core/system_impl.cpp
src/mavsdk/core/system_impl.h
src/mavsdk/plugins/camera/camera_impl.cpp
src/mavsdk/plugins/camera/camera_impl.h
src/mavsdk/plugins/gimbal/gimbal_impl.cpp
src/mavsdk/plugins/info/info_impl.cpp
src/mavsdk/plugins/mission/mission_impl.cpp
src/mavsdk/plugins/mission/mission_impl.h
src/mavsdk/plugins/telemetry/telemetry_impl.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.h

This implements the logic of requesting messages using the new command as well as the deprecated commands consolidated in the RequestMessage class.
Currently WIP implementing the functionality in REQUEST_MESSAGE. The next step is to use this class consistently everywhere.
Closes #1605, closes #2013.

Switch to new REQUEST_MESSAGE but fall back to deprecated request message commands if required

---

src/mavsdk/core/udp_connection.cpp

There is no point spamming the user about no known remotes. It's just confusing and noisy until the remotes appear.

core: ignore no known remotes

---

src/mavsdk/core/udp_connection.cpp

There is no point spamming the user about no known remotes. It's just confusing and noisy until the remotes appear.

[v2.12 BACKPORT] core: ignore no known remotes

---

src/mavsdk/core/mavlink_parameter_client.cpp

core: Fix reading int8/16 params from ArduPilot

---

src/mavsdk/core/mavlink_parameter_client.cpp

[BACKPORT v2.12] core: Fix reading int8/16 params from ArduPilot

---

third_party/libevents/CMakeLists.txt

No more jsonlohmann submodule to clone.
Thanks @bkueng .
Also see: https://github.com/mavlink/libevents/pull/10

third_party: update libevents

---

src/mavsdk/plugins/mission_raw/include/plugins/mission_raw/mission_raw.h
src/mavsdk/plugins/mission_raw/mission_raw.cpp
src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp
src/mavsdk/plugins/mission_raw/mission_raw_impl.h
src/mavsdk_server/src/generated/mission_raw/mission_raw.grpc.pb.cc
src/mavsdk_server/src/generated/mission_raw/mission_raw.grpc.pb.h
src/mavsdk_server/src/generated/mission_raw/mission_raw.pb.cc
src/mavsdk_server/src/generated/mission_raw/mission_raw.pb.h
src/mavsdk_server/src/plugins/mission_raw/mission_raw_service_impl.h

mainly a copy & paste of download_mission for rallypoints  and geofence. Which solves my issue #2403

added functionality to download geofences and rallypoints

---

src/mavsdk/core/mavsdk_impl.cpp

When we destroy Mavsdk and clear the list of connections, we likely end up in a deadlock.
What happens is that:
1. A connection wants to forward a message and is trying to acquire the connection mutex.
2. At the same time, the connection is being destroyed, so we are waiting for the connection receive thread to be joinable. While the connections are being destroyed, we have the connection mutex which is blocking 1.
The proposed solution is to:
1. Make it less likely by acquiring the connection mutex properly before checking _connections.size() and not for the individual connections.
2. Check the _should_exit flag before trying to acquire the mutex. I believe by the time the connections are being cleared, this flag is set, and hence the deadlock should not happen, fingers crossed.

core: prevent lockup on connection destruction

---

src/mavsdk/core/mavsdk_impl.cpp

[BACKPORT v2.12] core: prevent lockup on connection destruction

---

src/mavsdk/core/tcp_client_connection.cpp
src/mavsdk/core/udp_connection.cpp

- UDP inet_pton(remote_ip)'s result is not checked -> the server ends up sending packets to the null address when a hostname is given instead of a IPv4 address. A error is now raised
- TCP is using sendto() instead of send(). We can thus remove a useless inet_pton() call (which moreover differs from the gethostbyaddr used in setup_port() - possible issues when using hostnames)
Before the change:
```
$ mavsdk_server udpout://localhost:12345
[09:09:33|Info ] MAVSDK version: v2.12.2-108-g2328ed69 (mavsdk_impl.cpp:28)
[09:09:33|Info ] Waiting to discover system on udpout://localhost:12345... (connection_initiator.h:20)
Sits there quietly
```
After:
```
$ mavsdk_server udpout://localhost:12345
[09:10:33|Info ] MAVSDK version: v2.12.2-108-g2328ed69 (mavsdk_impl.cpp:28)
[09:10:33|Info ] Waiting …
```

TCP sendto removal + error when UDP for hostnames

---

src/mavsdk_server/src/connection_initiator.h
src/mavsdk_server/src/mavsdk_server.cpp

This fixes a segfault which happens when the mavsdk_server is stopped and destroyed before every having discovered any autopilot.
What happened is that:
1. ConnectionInitiator would be cancelled.
2. ConnectionInitiator would be destructed.
3. And only now the connect thread would wake up from sleeping and read the _should_exit flag which at this point has been destroyed. At this point the connect function would try to access Mavsdk::systems() which is also destructed by that point and cause a segfault.
The fix is to wrap the ConnectionInitiator class in a shared ptr and keep that one alive in the connect function to avoid destruction until it has returned.

mavsdk_server: fix crash on stop/destruction

---

src/mavsdk/plugins/component_metadata_server/CMakeLists.txt

[BACKPORT v2.12] plugins: fix install path

---

src/mavsdk/core/include/mavsdk/component_type.h
src/mavsdk/core/include/mavsdk/mavsdk.h
src/mavsdk/core/mavsdk.cpp
src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/system_impl.cpp

- ~Removed unused duplicate enum class in system.h~ Can we consolidate `System::ComponentType` with `Mavsdk::ComponentType`?
- Added `ComponentType::RemoteID` -- I'm transitioning [RemoteIDTransmitter](https://github.com/ARK-Electronics/RemoteIDTransmitter) to MAVSDK
- Removed `ComponentType::Custom` to reduce confusion since it was defaulting to MAV_TYPE_GENERIC
- Added `Mavsdk::Configuration` constructor for `ComponentType::RemoteId`

[core] Added ComponentType::RemoteID

---

examples/autopilot_server/autopilot_server.cpp
src/mavsdk/core/mavlink_command_receiver.cpp
src/mavsdk/plugins/telemetry_server/telemetry_server_impl.cpp

See commits.
The command fix gets rid of these confusing warnings:
```
[02:27:01|Debug] Received ack from 1/1 for not-existing command: 512! Ignoring... (mavlink_command_sender.cpp:285)
```
Finally...

Autopilot server and command server fixes

---

src/mavsdk/plugins/telemetry_server/telemetry_server_impl.cpp

It turns out we respond with two acks to a MAV_REQUEST_MESSAGE when we should only respond once with the successful one.
Alternatively, we could first grab all the results and then do some magic to determine which one is the best ack but that's a bit too magic and complex, so I'm not doing that yet.

[BACKPORT v2.12] core: prevent invalid duplicate acks

---

src/mavsdk/core/cli_arg.cpp
src/mavsdk/core/cli_arg_test.cpp

We don't want to accept udpin://:PORT but we always need the network interface, e.g.:
- udpin://192.168.X.Y:PORT, or
- udpin://0.0.0.0:PORT for all network interfaces
Without this we got an error further down with inet_pton.

core: make udpin parsing stricter

---

src/mavsdk/plugins/camera_server/camera_server_impl.cpp

[BACKPORT v2.12] camera_server: prevent double ack+message

---

.github/workflows/main.yml
src/mavsdk/core/mavlink_command_sender.cpp

core: add missing locks in command queue

---

src/mavsdk/core/CMakeLists.txt
src/mavsdk/core/hostname_to_ip.cpp
src/mavsdk/core/hostname_to_ip.h
src/mavsdk/core/hostname_to_ip_test.cpp
src/mavsdk/core/mavsdk_impl.cpp

Otherwise we end up with two connections, one for the hostname that we add and one for the IP where we receive messages from.
Fixes https://github.com/mavlink/MAVSDK-Java/issues/182.

core: always convert hostname to IP for UDP remotes

---

src/mavsdk/core/CMakeLists.txt
src/mavsdk/core/hostname_to_ip.cpp
src/mavsdk/core/hostname_to_ip.h
src/mavsdk/core/hostname_to_ip_test.cpp
src/mavsdk/core/mavsdk_impl.cpp

[BACKPORT v2.12] core: always convert hostname to IP for UDP remotes

---

src/mavsdk_server/src/CMakeLists.txt

This allows to install the mavsdk_server binary in any install prefix and run it.

cmake: set RPATH of installed mavsdk_server

---

.github/workflows/main.yml

I suspect the segfault happens in std::filesystem somewhere for older distributions. Therefore, for now, I'm just disabling these tests.

CI: ignore system_tests on earlier GCC versions

---

src/mavsdk/core/mavlink_ftp_client.cpp
src/mavsdk/core/mavlink_ftp_server.cpp

[BACKPORT v2.12] core: remove way too verbose warnings

---

src/mavsdk/core/server_component_impl.cpp
src/mavsdk/core/server_component_impl.h

MAVSDK comfortably supports MAVLINK 2, but the server component doesn't currently respond to the MAVLINK_MSG_ID_PROTOCOL_VERSION request, and thus GCSes like QGroundControl fall back to MAVLINK 1 when establishing communication.
This change adds the MAVLINK_MSG_ID_PROTOCOL_VERSION handler with a corresponding capability to communicate to clients that MAVLINK 2 is supported.
QGroundControl log before:
```
InitialConnectStateMachineLog: Sending REQUEST_MESSAGE:PROTOCOL_VERSION
VehicleLog: _waitForMavlinkMessage msg:timeout 300 1000
...
InitialConnectStateMachineLog: REQUEST_MESSAGE PROTOCOL_VERSION command acked but message never received
InitialConnectStateMachineLog: "Setting _maxProtoVersion to 100 due to timeout on receiving PROTOCOL_VERSION message."
VehicleLog: …
```

Respond to MAVLINK 2 PROTOCOL_VERSION request

---

src/mavsdk/plugins/camera/camera_impl.cpp

Corrects the conversion to numeric string representation

Fixes MAVSDK-Java#155 camera::possibleSettingOptions crashes as a result of erroneous string format

---

src/mavsdk/core/mavlink_parameter_client.cpp

We don't have the hash check based on the hidden param _HASH_CHECK implemented yet, so we shouldn't use the cache to get (all) params.

core: fix get_all_params caching

---

src/mavsdk/core/mavlink_parameter_client.cpp

Backport of https://github.com/mavlink/MAVSDK/pull/2457.

[BACKPORT v2] core: fix get_all_params caching

---

src/mavsdk_server/src/connection_initiator.h

This was removed by mistake in an earlier commit leading rightfully to confusion.

mavsdk_server: add waiting info back in

---

src/mavsdk/core/mavlink_parameter_cache.cpp
src/mavsdk/core/mavlink_parameter_cache.h
src/mavsdk/core/mavlink_parameter_cache_test.cpp
src/mavsdk/core/mavlink_parameter_client.cpp
src/mavsdk/core/mavlink_parameter_client.h

This includes several fixes to improve/fix getting all parameters, especially using a low bandwidth radio such as an SiK radio.
The main fixes are:
- Logic fix in keeping track of which parameters have already been received. We used to re-transmit way too many parameters again unnecessarily.
- Increase timeout to start re-transmissions. Parameters sent in bursts over an SiK radio can have long periods of silence. We just need to wait these out instead of using re-transmissions too early.
- When re-requesting parameters, we should still accept any other parameters, in case they are still coming in and we started the re-transmission too early.
- During re-transmission, request missing parameters in chunks of 10 to speed things up.

get_all_params fixes

---

src/mavsdk/core/mavlink_parameter_cache.cpp
src/mavsdk/core/mavlink_parameter_cache.h
src/mavsdk/core/mavlink_parameter_cache_test.cpp
src/mavsdk/core/mavlink_parameter_client.cpp
src/mavsdk/core/mavlink_parameter_client.h

[BACKPORT v2] get_all_params fixes

---

src/mavsdk/core/http_loader.cpp

With v2 we don't have https support in cURL that we compile, so we have to try http instead of https.
In order to avoid dependency churn on v2, I suggest to just use this hack instead of https://github.com/mavlink/MAVSDK/pull/2460.
@rayw-dronesense would this work for you?

[v2 only] core: use http instead of https

---

examples/CMakeLists.txt
examples/start_stop_server/CMakeLists.txt
examples/start_stop_server/start_stop_server.cpp

This just shows how to use the C API to instantiate the gRPC server.

examples: Add example on how to use mavsdk_server lib

---

.gitmodules
src/mavsdk/core/mavlink_mission_transfer_server.cpp
src/mavsdk/core/mavlink_mission_transfer_server.h
src/mavsdk/core/mavlink_mission_transfer_server_test.cpp
src/mavsdk/plugins/mission_raw_server/include/plugins/mission_raw_server/mission_raw_server.h
src/mavsdk/plugins/mission_raw_server/mission_raw_server.cpp
src/mavsdk/plugins/mission_raw_server/mission_raw_server_impl.cpp
src/mavsdk/plugins/mission_raw_server/mission_raw_server_impl.h
src/mavsdk_server/src/generated/mission_raw_server/mission_raw_server.pb.cc

MAVSDK has two classes for managing mission transfers:
* `MavlinkMissionTransferClient` used for initiating mission transfers (used primarily on the ground side)
* `MavlinkMissionTransferServer` used for handling mission transfer requests (used primarily on the air vehicle)
`MavlinkMissionTransferClient` has support both for sending missions as well as requesting missions from a server and handling the response. `MavlinkMissionTransferServer` currently only handles receiving missions, but does not respond to mission download requests (air to ground). The `MissionRawServer` service uses `MavlinkMissionTransferServer` to handle mission transfer requests, and thus `MissionRawServer` is currently "unidirectional".
This pull request implements the required functionality in …

Support Mission Download In Mission Raw Server

---

examples/start_stop_server/start_stop_server.cpp

Otherwise, we'd have to use attach.

examples: don't exit too early

---

src/mavsdk/core/mavlink_parameter_client.cpp

It turns out single params are sent with index -1, so caught by the test for the _HASH_CHECK param.
Backport part of https://github.com/mavlink/MAVSDK/pull/2480.
Fixes #2477.

[BACKPORT v2] core: fix param get regression

---

examples/params/params.cpp
src/mavsdk/core/mavlink_parameter_client.cpp

Fix set param regression, improve param example

---

src/integration_tests/CMakeLists.txt
src/integration_tests/autopilot_server_configuration.cpp
src/mavsdk/core/include/mavsdk/mavsdk.h
src/mavsdk/core/mavsdk.cpp
src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/mavsdk_test.cpp

- Add MAV_TYPE to Configuration
- Set mav_type from component by default or by setter method
- Move deriving of mav type from component type to Configuration
I want to use MAVSDK (MAVLink) as an API for a Rover type vehicle and want a more specific type than MAV_TYPE_GENERIC in the heartbeat. By default the mav type is derived from the component type or id, using the already existing implementation. It is implemented in a way that does not break the exsiting Constructors but only adds getter and setters.

Add Option to set the MAV_TYPE manually

---

src/mavsdk_server/src/CMakeLists.txt

seeing some rpath issue with `mavsdk_server` macos build 
```
==> /opt/homebrew/Cellar/mavsdk/3.0.0/bin/mavsdk_server --help
dyld[21093]: Library not loaded: @rpath/libmavsdk_server.3.dylib
Referenced from: <3175EB8C-F78F-3F99-AC24-F073CB8A7838> /opt/homebrew/Cellar/mavsdk/3.0.0/bin/mavsdk_server
Reason: tried: 'lib/libmavsdk_server.3.dylib' (no such file), 'lib/libmavsdk_server.3.dylib' (no such file)
```
relates to https://github.com/Homebrew/homebrew-core/pull/204677

fix `rpath` issue for `mavsdk_server` macos build

---

.github/workflows/main.yml

forked + PR to test  https://github.com/mavlink/MAVSDK/issues/2475

Fix CMAKE_INSTALL_PREFIX

---

examples/start_stop_server/start_stop_server.cpp
src/mavsdk_server/src/mavsdk_server_api.cpp
src/mavsdk_server/src/mavsdk_server_api.h
src/mavsdk_server/src/mavsdk_server_bin.cpp

This adds docstrings to the C API and changes the return value of mavsdk_server_run as you would expect a C API, wich 0 being successful.
Closes #2479.
This will require an update for MAVSDK-Java when switching to v3.x: https://github.com/mavlink/MAVSDK-Java/blob/b880fd2dfb01fa868bd9dcbffe222e4408bd3218/mavsdk_server/src/main/cpp/native-lib.cpp#L25

mavsdk_server: document and fixup C API

---

tools/generate_markdown_from_doxygen_xml.py

This updates the doxygen xml to md script to change gitbook notes to Vitepress info blocks. Fairly sure it is correct.
```
::: info
A note
:::
```

Fix up notes in source code

---

src/mavsdk/plugins/geofence/geofence_impl.cpp

Overview
Currently there is a bug in MAVSDK server that will only allow geofence upload for UAV's with sysID of 1. This has been replaced with a function to return the sys id of the device assigned.
Tested IRL and in Gazebo with quad's assigned sys ID's from 1 - 6.

update to working geofence

---

src/integration_tests/telemetry_async.cpp
src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h
src/mavsdk/plugins/telemetry/telemetry.cpp
src/mavsdk/plugins/telemetry/telemetry_impl.cpp
src/mavsdk/plugins/telemetry_server/include/plugins/telemetry_server/telemetry_server.h
src/mavsdk/plugins/telemetry_server/telemetry_server.cpp
src/mavsdk/plugins/telemetry_server/telemetry_server_impl.cpp
src/mavsdk/plugins/telemetry_server/telemetry_server_impl.h
src/mavsdk_server/src/generated/telemetry/telemetry.pb.cc
src/mavsdk_server/src/generated/telemetry/telemetry.pb.h
src/mavsdk_server/src/generated/telemetry_server/telemetry_server.grpc.pb.cc
src/mavsdk_server/src/generated/telemetry_server/telemetry_server.grpc.pb.h
src/mavsdk_server/src/generated/telemetry_server/telemetry_server.pb.cc
src/mavsdk_server/src/generated/telemetry_server/telemetry_server.pb.h
src/mavsdk_server/src/plugins/telemetry/telemetry_service_impl.h
src/mavsdk_server/src/plugins/telemetry_server/telemetry_server_service_impl.h

**NOTE: this is a re-creation of the now closed PR https://github.com/mavlink/MAVSDK/pull/2504. As far as I can tell, PR 2504 got closed because it was targeting a feature branch that was deleted. This now re-created PR is targeting `main` but is otherwise the same.**
This PR does 3 things:
1. Expands the `FixedwingMetrics` telemetry object to include all fields that show up in the MAVLINK VFR_HUD message. The telemetry client handles the VFR_HUD message currently, translating it to a `FixedwingMetrics` struct, but it only takes half the fields. This PR fills out the rest of the fields so the full message is available.
2. Adds an endpoint for sending the VFR_HUD message via `TelemetryServer`
3. Adds an endpoint for sending the MAVLINK ATTITUDE message via `TelemetryServer`. Note that the …

Telemetry and TelemetryServer improvements

---

.github/workflows/main.yml

[This change in dockcross](https://github.com/dockcross/dockcross/pull/869#event-16501631543) is breaking all our dockcross builds. I haven't found a solution to work around that change, but anyway it seems wise to pin the version of dockcross we use, to avoid similar problems in the future.

Pin dockcross version to avoid breaking change

---

docs/en/cpp/api_reference/classmavsdk_1_1_action_server.md
src/mavsdk/plugins/action_server/action_server.cpp
src/mavsdk/plugins/action_server/action_server_impl.cpp
src/mavsdk/plugins/action_server/action_server_impl.h
src/mavsdk/plugins/action_server/include/plugins/action_server/action_server.h
src/mavsdk_server/src/generated/action_server/action_server.grpc.pb.cc
src/mavsdk_server/src/generated/action_server/action_server.grpc.pb.h
src/mavsdk_server/src/generated/action_server/action_server.pb.cc
src/mavsdk_server/src/generated/action_server/action_server.pb.h
src/mavsdk_server/src/plugins/action_server/action_server_service_impl.h

SDK changes to implement the interface provided in the corresponding [proto PR](https://github.com/mavlink/MAVSDK-Proto/pull/370). Testing continues to be done using QGroundControl to provide visibility into vehicle mode changes.
It's worth noting that there is probably a broad class of state changes like this that could use public APIs. I've opted to keep the scope constrained and focus only on the most essential information for now.

ActionServer: allow direct setting of arm/disarm state and vehicle flight mode

---

.github/workflows/main.yml

Trying to understand what's happening in https://github.com/mavlink/MAVSDK/pull/2531 and https://github.com/mavlink/MAVSDK/pull/2530 :thinking: 
It seems like the recent dockcross releases have broken our builds. I thought I had fixed it, but apparently not completely. It works well with the dependencies, but it has issues when coming to the main project.
I would suggest we use a dockcross from 3 months ago until I get time to investigate and fix this.

Rollback to older dockcross

---

src/mavsdk/core/udp_connection.cpp

The inet_ntoa function is not thread-safe and uses a static buffer that can be overwritten by subsequent calls. Let's try this instead.

core: try to fix inte_ntoa erro on macOS

---

.github/workflows/main.yml

I was only setting CMAKE_PREFIX_PATH on cache hit, which I believe is wrong: it should always be set.
It may explain issues with "OpenSSL not found" by CMake over the years. It has been made clearly visible with the recent update of dockcross which systematically fails. This PR fixes it.

Update dockcross and fix CMAKE_PREFIX_PATH in workflows

---

src/mavsdk/core/udp_connection.cpp
src/mavsdk/core/udp_connection.h

This commit fixes an issue in the UDP connection handling where MAVSDK would duplicate streams when clients reconnect and continue sending packets to endpoints that had closed their connections.

core: Add timeout mechanism for inactive UDP connections

---

src/mavsdk/core/mavlink_mission_transfer_server.cpp
src/mavsdk/core/mavlink_mission_transfer_server.h
src/mavsdk/core/mavlink_mission_transfer_server_test.cpp
src/mavsdk/plugins/mission_raw_server/mission_raw_server_impl.cpp
src/mavsdk/plugins/mission_raw_server/mission_raw_server_impl.h

I'm working with @jonathanreeves to update the mission server to support more mission types.
In this branch, I have done the following:
- Added fence and rally item vectors to the raw server so they can be sent and received independently from the mission vector.
- Added getter for mission items based on the mission type; if an unsupported mission type is used, an empty vector is returned.
- Added mission type parameter to ResultAndItemsCallback so server callbacks can use the relevant item vector.
- Updated raw server calls to mission transfer server calls to use the mission type of messages instead of being hard coded mission.
- Added raw server logic to only reset mission completion if mission items are received for a mission type mission.
- Added raw server logic to clear fence and …

Add fence and rally missions to raw server

---

src/mavsdk/plugins/mission_raw/mission_import.cpp
src/mavsdk/plugins/mission_raw/mission_import.h
src/mavsdk/plugins/mission_raw/mission_import_test.cpp
src/mavsdk/plugins/mission_raw/test_plans/qgroundcontrol_sample_with_digicam_control.plan

We should only convert lat/lon values but not regular commands. We can tell by checking the mission item's frame.
Fixes #2543.

mission_raw: fix mission import for mission commands

---

src/mavsdk/plugins/action/action_impl.cpp

This reverts #2562.
I need to revert this because yaw is implemented in radians for PX4, so this would be a breaking and surprising change.
@RoseBeaupreARA I'm suggesting to change the spec, see discussion: https://github.com/mavlink/mavlink/pull/2271

Revert "[PATCH] Fix goto_location sending radians instead of degrees"

---

src/mavsdk/core/mavlink_mission_transfer_client.cpp

I don't think it makes sense to check the current flag for rally points and geofence items.

core: only check current for mission items

---

.github/workflows/main.yml

https://github.com/mavlink/MAVSDK/pull/2482 broke the .deb library generation.
See:
- 3.1.0: https://github.com/mavlink/MAVSDK/actions/runs/13861584250/job/38791176950: ./install is wrong
- 3.2.0: https://github.com/mavlink/MAVSDK/actions/runs/13934248046/job/40004713611: /usr/ runs out of disk space because it wants to package everything
I'm reverting these until we have a proper fix that doesn't want to package the whole system.

Revert library packaging

---

src/mavsdk/plugins/events/events_impl.cpp
src/mavsdk/plugins/events/events_impl.h

This is to avoid a potential segfault on destruction.

events: unsubscribe from events

---

src/mavsdk/core/call_every_handler.cpp
src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/mavsdk_impl.h
src/mavsdk/core/system_impl.cpp
src/mavsdk/core/system_impl.h
src/mavsdk/core/timeout_handler.cpp
src/mavsdk/plugins/camera/camera_impl.cpp
src/system_tests/ftp_download_file.cpp
src/system_tests/ftp_upload_file.cpp

This is a bigger refactor where we no longer do work from the receiver threads but instead copy messages into a queue and work on them subsequently.
This is an attempt to prevent deadlocks where locks are acquired in different orders.
Additional, there are various small fixes to make all system and unit tests pass in address sanitizer and thread sanitizer.
I need to review this with fresh eyes again tomorrow.
Follow up to #2542

Add incoming and outgoing message queue, fixing threading/locking issues

---

src/system_tests/camera_format_storage.cpp
src/system_tests/camera_list_cameras.cpp
src/system_tests/camera_mode.cpp
src/system_tests/camera_storage.cpp
src/system_tests/camera_take_photo.cpp
src/system_tests/camera_take_photo_interval.cpp
src/system_tests/camera_video_stream.cpp

Let's just wait long enough to prevent CI from failing on slow Macs.

system_tests: make camera discovery more robust

---

src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/udp_connection.cpp
src/mavsdk/core/udp_connection.h

When we add a connection with udpout:// we should not remove that remote. Otherwise, we can basically only try to connect for 10s before the remote is removed and we're left without any way to communicate.
This is a cleanup after #2557.

core: don't remove explicit udpout remotes

---

src/mavsdk/plugins/gripper/gripper_impl.cpp

It's not obvious that this would go to a separate winch, so I'm removing this. Hopefully, this makes it work with PX4 like it does for QGC.
Ok with this @dakejahl?

gripper: send command to autopilot by default

---

src/mavsdk/core/param_value.cpp
src/mavsdk/plugins/camera/camera_definition_test.cpp
src/mavsdk/plugins/camera/gazebo_camera.xml

This should fix a reported invalid argument exception.
Closes #2496.

camera: fix invalid argument exception

---

docs/en/cpp/api_reference/classmavsdk_1_1_mission_raw.md
src/mavsdk/plugins/mission/mission_impl.cpp
src/mavsdk/plugins/mission/mission_impl.h
src/mavsdk/plugins/mission_raw/include/plugins/mission_raw/mission_raw.h
src/mavsdk/plugins/mission_raw/mission_raw.cpp
src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp
src/mavsdk/plugins/mission_raw/mission_raw_impl.h
src/mavsdk_server/src/generated/mission_raw/mission_raw.grpc.pb.cc
src/mavsdk_server/src/generated/mission_raw/mission_raw.grpc.pb.h
src/mavsdk_server/src/generated/mission_raw/mission_raw.pb.cc
src/mavsdk_server/src/generated/mission_raw/mission_raw.pb.h
src/mavsdk_server/src/plugins/mission_raw/mission_raw_service_impl.h

- Mission: If the mission state is available we should make good use of it, otherwise we can fallback on what we did previously.
- MissionRaw: Add is_mission_finished method, and copy logic of Mission.
- Mission: PX4 required us to account for RTL items as they were not reported as "reached". This is no longer required in the future, so we need to fix the comparison.
Uses https://github.com/mavlink/mavlink/pull/1869.

Improve handling of mission finished

---

src/mavsdk/plugins/mission/mission_impl.cpp
src/mavsdk/plugins/mission/mission_impl.h
src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp
src/mavsdk/plugins/mission_raw/mission_raw_impl.h

Not sure who decided to invent a separate MissionState that didn't match the MAVLink spec one. Blame AI.
Should fix CI in https://github.com/PX4/PX4-Autopilot/pull/24918.

mission/mission_raw: fixup mission finished

---

docs/en/cpp/guide/build_windows.md
third_party/openssl/CMakeLists.txt

Fixed a build error on windows when not using JOM and updated the windows build documentation.

Build error windows without JOM

---

src/mavsdk/core/mavlink_command_sender.cpp

Lots of MAVSDK output has a lot of noise from these commands, so let's tone it down as it's not really actionable anyway. For development MAVSDK_COMMAND_DEBUGGING can be set to 1.

core: make command sender less verbose

---

src/mavsdk/core/mavlink_request_message.cpp

We often flagged REQUEST_MESSAGE commands as Busy because they were duplicate. However, when we are targetting different component IDs, they are obviously different and need to be done for this to work properly.
This came up when debugging a gimbal not being recognized as the request for GIMBAL_DEVICE_INFORMATION was swallowed.

core: fix REQUEST_MESSAGE drops with multiple components

---

src/mavsdk/core/log.h

While debugging debug output in MAVSDK-Python I realized that error messages like "Invalid connection" just never appear which is very confusing.
I have also seen reports in the past where MAVSDK logs wouldn't show up or show up very late in journalctl (if an application is started via systemd). Again, very confusing.
Given we don't print a lot of stuff, and flushing after each line unlikely has real performance implications, I suggest to use std::endl which includes std::flush instead of only printing a newline.
This replaces #2626. It's currently on top of #2630 for CI testing.

core: flush after each Log* line (take 2)

---

docs/en/cpp/api_reference/classmavsdk_1_1_telemetry.md
src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h
src/mavsdk/plugins/telemetry/telemetry_impl.cpp
src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.h

- ScaledImu: this comes in milliG, milliRad, milliGauss, so we need to translate it.
- RawImu: doesn't have a unit by definition, so we need to add a comment.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/380

telemetry: fix Imu units

---

src/mavsdk/plugins/mavlink_direct/mavlink_direct_impl.cpp

Should fix a thread sanitizer issue discovered in https://github.com/mavlink/MAVSDK/actions/runs/16683659281/job/47227994539?pr=2634.

mavlink_direct: unregister messages on deinit

---

src/mavsdk/CMakeLists.txt

Newer GCC versions (>= 9) include the C++17 filesystem library in libstdc++ by default, so linking stdc++fs explicitly is unnecessary and may cause build errors.
Update the CMake condition to link stdc++fs only when using GCC < 9, while keeping the existing exclusions for Apple, Android, and MSVC.

cmake: only link stdc++fs for GCC < 9

---

src/mavsdk/core/connection.h
src/mavsdk/core/mavlink_receiver.cpp
src/mavsdk/core/serial_connection.cpp
src/mavsdk/core/serial_connection.h
src/mavsdk/core/tcp_client_connection.cpp
src/mavsdk/core/tcp_client_connection.h
src/mavsdk/core/tcp_server_connection.cpp
src/mavsdk/core/tcp_server_connection.h
src/mavsdk/core/udp_connection.cpp
src/mavsdk/core/udp_connection.h
src/system_tests/CMakeLists.txt
src/system_tests/mavlink_direct_forwarding.cpp

This fixes the problem that MAVSDK did not forward messages which it had not seen before. This could happen when:
- A message is added in a later version of MAVLink whchi MAVSDK hasn't shipped with,
- A custom message needs to be forwarded that MAVSDK doesn't know about.

Enable forwarding unknown messages

---

.github/workflows/linux.yml

The latest dockcross android images bring Android 16KB, which is now needed (see e.g. [here in MAVSDK-Java](https://github.com/mavlink/MAVSDK-Java/issues/214)).

Update dockcross image, bringing support for Android 16KB alignment

---

docs/en/cpp/api_reference/classmavsdk_1_1_mavsdk.md
docs/en/cpp/api_reference/structmavsdk_1_1_mavlink_direct_1_1_mavlink_message.md
docs/en/cpp/api_reference/structmavsdk_1_1_mavsdk_1_1_mavlink_message.md
examples/sniffer/sniffer.cpp
src/mavsdk/core/connection.cpp
src/mavsdk/core/connection.h
src/mavsdk/core/include/mavsdk/mavsdk.h
src/mavsdk/core/libmav_receiver.cpp
src/mavsdk/core/libmav_receiver.h
src/mavsdk/core/mavsdk.cpp
src/mavsdk/core/mavsdk_impl.cpp
src/mavsdk/core/mavsdk_impl.h
src/mavsdk/core/system_impl.cpp
src/mavsdk/core/system_impl.h
src/mavsdk/plugins/mavlink_direct/include/plugins/mavlink_direct/mavlink_direct.h
src/mavsdk/plugins/mavlink_direct/mavlink_direct.cpp
src/mavsdk/plugins/mavlink_direct/mavlink_direct_impl.cpp
src/mavsdk/plugins/telemetry_server/telemetry_server_impl.cpp
src/mavsdk_server/src/generated/mavlink_direct/mavlink_direct.pb.cc
src/mavsdk_server/src/generated/mavlink_direct/mavlink_direct.pb.h
src/mavsdk_server/src/plugins/mavlink_direct/mavlink_direct_service_impl.h
src/system_tests/CMakeLists.txt
src/system_tests/intercept.cpp
src/system_tests/mavlink_direct.cpp
src/system_tests/mavlink_direct_forwarding.cpp

This adds a new interception API based on the libmav JSON integration (see https://github.com/mavlink/MAVSDK/pull/2610), avoiding the MAVLink C header depend dependency. The JSON based API will replace the previous one by the next major release.
Currently on top of #2637.

Add new JSON based interception API

---

src/mavsdk/core/system_impl.cpp
src/mavsdk/core/system_impl.h
src/mavsdk/plugins/mavlink_direct/mavlink_direct_impl.cpp
src/mavsdk/plugins/mavlink_direct/mavlink_direct_impl.h
src/system_tests/mavlink_direct.cpp

The message filtering was not correct with 2 or more subscriptions as they would conflict with each other. This should now be fixed with each subscription keeping track of what to filter out.
While doing so we switched to the new and nicer Handle/Subscription API in SystemImpl rather than the ugly void* cookie thing.
Fixes #2648.

mavlink_direct: fix message filtering

---

src/mavsdk/plugins/telemetry/telemetry_impl.cpp

Corrects an issue where `set_rate_unix_epoch_time_async` requested the wrong MAVLINK message. Now it uses `SYSTEM_TIME` to march the message handler.
Tested with SITL

Fix unix epoch async rate setter conflict with Ardupilot

---

src/mavsdk/plugins/mavlink_direct/mavlink_direct_impl.cpp
src/system_tests/intercept.cpp
src/system_tests/mavlink_direct.cpp

It turns out jsoncpp uses isUInt for numbers below 2^32 and isUInt64 for numbers above 2^32.
Fixes #2679.

mavlink_direct: handle (u)int > 2^32
