mavlink/MAVSDK

.gitmodules

This makes cloning of the public dependency easier.

gitmodules: use https link for curl-android-ios

---

README.md

This adds a link to device and device_plugin_container APIs.
Fixes #14.

README: add links to device and device_plugin_container APIs

---

core/dronecore_impl.cpp

This ignores messages from system ID 255 for now.
In the future we might consider checking the heartbeat type field and
check it for MAV_TYPE_GCS, however this might require some refactoring
because devices are created if any messages arrive and not just
heartbeats.
FYI: @sanderux

core: ignore messages from QGC

---

Makefile

This did not actually do what it was supposed to but always ran install.
@hamishwillee this should fix your error:
```
make default Build dir: build/default ninja: error: loading 'build.ninja': No such file or directory Makefile:71: recipe for target 'default' failed make: *** [default] Error 1
```
Can you re-test with this?

Makefile: don't always install

---

example/takeoff_land/takeoff_and_land.cpp

This makes errors show up a little more clear in the output. 
I also added a check for the vehicle being in an armable state, as I think this is a useful thing to show users. Note that none of the checks are necessarily realistic but good for the example (e.g. in real code I might way for armable state rather than exiting).

Colour code errors in example

---

example/fly_mission/CMakeLists.txt
example/takeoff_land/CMakeLists.txt

The fly mission example was linux specific - this adds the required windows compatibility (copied from takeoff_and_land example). It also removes a spurious message for the cmake source directory from the takeoff example. 
1. If we have installed the DroneCore artifacts system wide will the example pick these up instead of the relative path to the include directory that I see defined mid-way up?
2. The instructions we given in  [Install Artifacts](http://localhost:4000/en/contributing/build.html#install-artifacts) state that to install files system wide you do the following when building DroneCore:
```
INSTALL_PREFIX=/usr/local make default install
```
- Won't this only work on linux?
- Does cmake look for this location when creating make files for examples?
- Is there a way to get this …

Make examples have consistent buildfiles

---

CMakeLists.txt
core/curl_wrapper.cpp
core/device_impl.cpp
core/dronecore_impl.cpp
core/global_include.h
core/http_loader_test.cpp
core/integration_test_helper.h
core/log.h
core/mavlink_commands.cpp
core/mavlink_parameters.cpp
core/mavlink_parameters.h
core/mavlink_receiver.cpp
core/serial_connection.cpp
core/tcp_connection.cpp
core/udp_connection.cpp
integration_tests/async_hover.cpp
integration_tests/curl.cpp
integration_tests/mission_change_speed.cpp
plugins/action/action_impl.cpp
plugins/mission/mission_impl.cpp
plugins/mission/mission_item_impl.cpp
plugins/offboard/offboard_impl.cpp
plugins/telemetry/telemetry_impl.cpp

This improves the log output. Instead of only one `Debug()` printf for everything, there are now proper log levels: `LogDebug()`, `LogInfo()`, `LogWarn()`, `LogErr()`.
It also adds file name and file number to the printfs which should help to figure out where stuff went wrong.

Improve debugging printfs

---

CMakeLists.txt
Makefile
core/log.h
core/mavlink_commands.cpp
core/mavlink_commands.h

The reason for the switch is that LLVM supports futures and promises for the architecture armeabi.
This means we can get rid of some (mostly untested) promise code specifically writtern for the armeabi architecture.

Android: link to LLVM stl instead of GNU stl

---

plugins/telemetry/telemetry.h
plugins/telemetry/telemetry_impl.cpp

It is more intuitive to have the flag `available` signalling connected
then `not lost` like previously. Also, the initialization with `false`
makes more sense this way.

telemetry: use available instead of lost for RC

---

core/device_impl.cpp
core/device_impl.h
core/dronecore_impl.cpp
include/dronecore.h
plugins/action/action_impl.cpp

This changes the logic so that you the UUID is used if available but the
mavlink system ID is used as a fallback option. The fallback happens if
3 requests for the autopilot_version are unsuccessful or if the
AUTOPILOT_VERSION.uid field is 0.
This replaces #77.

Fallback to mavlink system ID if no UUID available

---

core/log.h

In order to distinguish Info and Debug, Info is now made blue.
Also, the color is now properly set at the beginning of the line instead
of after the time.

core: make Info printfs blue

---

core/udp_connection.cpp
core/udp_connection.h

It does not really make sense that a device always needs to keep its IP
and port because a wifi connection might drop for a bit and therefore
the IP and port can change. Therefore, we no longer ignore messages
after the IP/port have changed and instead just accept it.
@darioxz this is for you, please review.

UDP connection: allow remote IP and port to change

---

.gitignore
.ycm_extra_conf.py
CMakeLists.txt
core/device_impl.cpp
core/device_impl.h
core/dronecore_impl.cpp
core/locked_list.h
core/locked_list_test.cpp
core/log.h
core/mavlink_commands.cpp
core/mavlink_commands.h
core/timeout_handler.cpp
core/timeout_handler.h
core/timeout_handler_test.cpp
integration_tests/async_hover.cpp

This is a big refactor of the MavlinkCommands class in order to support
multiple commands in parallel. It won't do multiple commands with the
same command ID at the same time in order to prevent conflicts/races
with acks that can't be assigned uniquely.

Support for commands in parallel

---

plugins/mission/mission_impl.cpp

Old debug info text had typo ("success, not "sucess") but in any case was not useful because there was no information about the context of the success.

Improve info text when mission accepted

---

example/fly_mission/fly_mission.cpp
integration_tests/mission.cpp

Thanks for spotting this @hamishwillee.
- Fixed a wrong comment.
- Changed mission progress handling into lambda because it is more readable.

fix comment, use lambdas for mission progress

---

core/device_impl.cpp
core/device_impl.h
core/dronecore_impl.cpp
include/dronecore.h
plugins/action/action_impl.cpp

The PR #80 got lost because it was only merged into another branch.
Therefore, I'm adding it again.

Fallback to mavlink system ID if no UUID available [2]

---

.travis.yml
CMakeLists.txt
appveyor.yml
core/integration_test_helper.h

Run release builds in travis and fix compile errors for release builds.
Closes #92.

travis: add release build

---

integration_tests/simple_hover.cpp

Replaces #98.
This adds some checks to the ActionSimpleHover tests to actually check
what PX4 SITL is executing rather than just checking if we get the
correct responses.
This could be an example for CI tests for PX4 using DroneCore.
@dagar have a look
To test this:
- Start PX4 SITL
- Then start the test:
```
make && build/default/integration_tests_runner --gtest_filter="SitlTest.ActionSimpleHover*"
```
Or if you have Firmware and DroneCore next to each other in a folder:
```
make && AUTOSTART_SITL=1 build/default/integration_tests_runner --gtest_filter="SitlTest.ActionSimpleHover*"
```

integration_tests: add checks to takeoff/land test [2]

---

CMakeLists.txt

By adding SYSTEM before including the additional_includes, we ignore our
cmake warnings which would often break the build.

cmake: ignore our warnings for additional includes

---

integration_tests/info.cpp
plugins/info/info.cpp
plugins/info/info.h
plugins/info/info_impl.cpp
plugins/info/info_impl.h

This adds the vendor and product ID and name back.

info: add vendor and product ID and name

---

integration_tests/telemetry_async.cpp
plugins/telemetry/telemetry_impl.cpp

RC status had no integration tests and also did not work because the subscription was never actually called.

Fix RC status

---

core/log.h

This makes debug printfs green as requested in #103 (closes #103).
Also, the color is now only applied for `[time|type]` instead of the whole line as agreed upon in #86.

Improve debug printfs

---

core/device_impl.cpp
core/device_impl.h

By printing all mavlink statustexts we should get a bit more context
when something goes wrong on the firmware side.
@bkueng do you have a better suggestion how to make sure the `statustext.text` string is null terminated

core: add mavlink statustexts as debug printfs

---

integration_tests/CMakeLists.txt
integration_tests/gimbal.cpp
plugins/gimbal/CMakeLists.txt
plugins/gimbal/gimbal.cpp
plugins/gimbal/gimbal.h
plugins/gimbal/gimbal_impl.cpp
plugins/gimbal/gimbal_impl.h

This adds a plugin which can set pitch and yaw angle of a gimbal.
Currently, the commands are sent to component ID 1, so the assumption is
that the gimbal is connected to the autopilot and not talking mavlink
itself. This could change or be made adaptable in the future.

Added gimbal plugin

---

core/device_impl.cpp

core: correctly capitalize MAVLink

---

CMakeLists.txt
core/call_every_handler.cpp
core/call_every_handler.h
core/call_every_handler_test.cpp
core/device_impl.cpp
core/device_impl.h
core/global_include.cpp
core/global_include.h
example/offboard_velocity/offboard_velocity.cpp
integration_tests/offboard_velocity.cpp
plugins/offboard/offboard.cpp
plugins/offboard/offboard.h
plugins/offboard/offboard_impl.cpp
plugins/offboard/offboard_impl.h

This changes the offboard API so that it is no longer required to send
setpoints at least every 0.5 seconds. Instead, this enables to set a
setpoint once and only set it again when it changes. The implementation
will automatically send it at 20 Hz internally.
If the setpoints need to be sent at a higher rate, e.g. for very smooth
control, that is still possible by just setting the setpoints at high
rate. Whenever a setpoint changes, it is immediately sent to the
vehicle.
Tested in SITL using the integration tests as well as the offboard example.

offboard: automatically send setpoins at set rate

---

.gitmodules
CMakeLists.txt
Makefile
core/connection.cpp

This change speeds up the Android build because we don't always have to
rebuild openssl and curl for Android.
@darioxz was there a good reason we put that there?

Makefile: don't delete prebuilt Android libs

---

.travis.yml
external_example/plugins/example/example_impl.cpp

This brings the external example up to speed. Additionally, the external example is now added to travis to prevent it from breaking in the future.

external_example: fix compile errors

---

.gitignore
.travis.yml
Makefile
appveyor.yml
create_deb.sh
example/fly_mission/CMakeLists.txt
example/offboard_velocity/CMakeLists.txt
example/takeoff_land/CMakeLists.txt
generate_markdown_from_doxygen_xml.py
grpc/server/CMakeLists.txt
travis-docker-build.sh

This is a step towards integration tests for github.com/PX4/Firmware by generating .deb packages on releases.
In order to streamline the .deb generation, I've changed the build to a shared library for Linux and macOS, and made the default install location `/usr/local`.
While doing that I actually realized that libdronecore was not being linked to curl and pthread which required all executable to link against them. This should now be fixed.

Support to generate .deb packages

---

example/fly_mission/fly_mission.cpp
grpc/server/dronecore_server.cpp
integration_tests/mission.cpp
integration_tests/mission_change_speed.cpp
integration_tests/mission_survey.cpp
plugins/mission/mission.cpp
plugins/mission/mission.h
plugins/mission/mission_impl.cpp
plugins/mission/mission_impl.h

This changes the API from `send_mission_async()` to `upload_mission_async()` and adds `download_mission_async`.
This allows missions created with DroneCore to be downloaded from the vehicle. However, DroneCore only supports a subset of the mavlink mission protocol and will fail with the `Result::UNSUPPORTED` for anything it does not know.

Download mission capability

---

core/device_impl.cpp
core/device_impl.h

This adds a lock to receive and send mavlink messages. This can be used
by a plugin to lockdown DroneCore.
The lock is disabled by default, so this change should not have any
effects apart from a few more CPU cycles.

core: add a lock around mavlink communication

---

integration_tests/mission.cpp
plugins/mission/mission_impl.cpp
plugins/mission/mission_item.cpp
plugins/mission/mission_item.h
plugins/mission/mission_item_impl.cpp
plugins/mission/mission_item_impl.h

This adds the possibility to add a delay before taking a picture or
starting a video. This is used to wait for a gimbal to reach its
orientation, or a vehicle to slow down.
The current implementation is not optimal because it is based on the
`LOITER_TIME` waypoint instead of the `NAV_DELAY` command which would be
more appropriate but is not supported (yet).

mission: add delay before camera action

---

example/transition_vtol_fixed_wing/CMakeLists.txt
example/transition_vtol_fixed_wing/transition_vtol_fixed_wing.cpp
integration_tests/transition_multicopter_fixedwing.cpp
plugins/action/action.cpp
plugins/action/action.h
plugins/action/action_impl.cpp
plugins/action/action_impl.h

This follows up on https://github.com/dronecore/DroneCore/pull/150#issuecomment-344140095.

Follow up for VTOL transition additions

---

CMakeLists.txt

~~This gives more flexibility for extensions to set additional_includes.~~
This is just a build output now.

cmake: add info for additional includes

---

.doxygen
Makefile
autogenerate_plugin_container.cmake
generate_docs.sh
generate_markdown_from_doxygen_xml.py
include/device_plugin_container.h.in
include/dronecore.h
plugins/action/action.h
plugins/gimbal/gimbal.h
plugins/logging/logging.h
plugins/mission/mission.h
plugins/telemetry/telemetry.h
travis-docker-build.sh

This removes the `make docs` target and instead adds the script
generate_docs.sh to do a clean build, install locally and run doxygen,
and the generate_markdown_from_doxygen_xml script.
Fixes #159.

Added script to generate docs

---

autogenerate_plugin_container.cmake
include/device_plugin_container.h.in

It turns out that if you add some words after private doxygen is happy.
Fixes #169.

docs: fix warnings

---

CMakeLists.txt
autogenerate_plugin_container.cmake

This changes autogenerate_plugin_container.cmake script to generate the
plugin getter method to be named with an underscore as you would expect.
For instance for the plugin FollowMe this would yield `follow_me`
instead of `followme`.
Tested using #142 and merging in this branch.

cmake: fix plugin getter name

---

CMakeLists.txt
cmake/Modules/FindGRPC.cmake
grpc/python_client/CMakeLists.txt
grpc/server/CMakeLists.txt

I tried to use `find_package` instead of `include`, and `<PACKAGE>_FOUND` instead of checking if a variable is set. I find this easier to read.
I moved the `FindGRPC.cmake` file in `cmake/Modules`, as it seems to me like it is the proposed default that I've seen in different projects (see [here](https://cmake.org/Wiki/CMake:How_To_Find_Libraries#Using_external_libraries_that_CMake_doesn.27t_yet_have_modules_for)).
Other than that, it's only some minor indentation fixes.

cmake: more consistent use of find_package and <PACKAGE>_FOUND

---

core/serial_connection.cpp

We should be able to read in a blocking way on the serial port since it
happens on a separate thread.
Fixes #176.

core: do blocking read on serial port

---

CMakeLists.txt
appveyor.yml
core/tcp_connection.cpp
core/udp_connection.cpp
example/fly_mission/CMakeLists.txt
example/offboard_velocity/CMakeLists.txt
example/offboard_velocity/offboard_velocity.cpp
example/takeoff_land/CMakeLists.txt
example/transition_vtol_fixed_wing/CMakeLists.txt

This should fix the linking on Windows. We now properly link the static library itself to ws2_32.lib.
Also, the examples are now built in CI.
Closes #162.

Fix Windows linking

---

grpc/python_client/CMakeLists.txt
grpc/python_client/async_client.py
grpc/python_client/fly_mission.py
grpc/python_client/sync_client.py

grpc:Update python client for dynamic plugin loading

---

core/serial_connection.h

When _should_exit isn't initialized on an ARM platform (Udoo Dual), it defaults to true and the serial connection receive thread exits immediately. Explicitly initializing the variable solves the issue.

core: SerialConnection Initialize _should_exit with false

---

generate_markdown_from_doxygen_xml.py

This adds support see also tags (sa) and note tags. The sa tag groups all marked lines as bullet points under a heading **See Also** as requested by #180 
The notes render as a gitbook note (ie `> **Note** Some text`). The problem is that you can only have single line notes - multi-line notes render as separate notes. 
It may be better to render these JUST like see also (under their own heading). Thoughts?

Add docs support for sa and note tags

---

Dockerfile

Sometimes the style changes differ between astyle versions 2 and 3,
therefore let's stick to 3.

docker: download astyle 3.0.1

---

generate_docs.sh

generate_doc.sh: Prompting repeatedly to clean build & install directory is annoying.
Fix is to let the script do it for us; we just need to re-run the script.
Added options `--clean` & `--help`
If the script is ran without options, it builds & installs the source and generate docs.
When `--clean` is used, it will perform clean build by deleting install folder.
When the script is ran with invalid/accidental args, help message is shown.

genrate_docs: Removed annoying prompts to clean build/install dir

---

autogenerate_plugin_container.cmake
core/device_impl.cpp
core/device_impl.h
core/device_plugin_container.cpp.in
core/plugin_impl_base.cpp
core/plugin_impl_base.h
external_example/plugins/example/example_impl.cpp
external_example/plugins/example/example_impl.h
include/device_plugin_container.h.in
plugins/action/action_impl.cpp
plugins/action/action_impl.h
plugins/follow_me/follow_me_impl.cpp
plugins/follow_me/follow_me_impl.h
plugins/gimbal/gimbal_impl.cpp
plugins/gimbal/gimbal_impl.h
plugins/info/info_impl.cpp
plugins/info/info_impl.h
plugins/logging/logging_impl.cpp
plugins/logging/logging_impl.h
plugins/mission/mission_impl.cpp
plugins/mission/mission_impl.h
plugins/offboard/offboard_impl.cpp
plugins/offboard/offboard_impl.h
plugins/telemetry/telemetry_impl.cpp
plugins/telemetry/telemetry_impl.h

By providing an enable/disable API for plugins, we can distinguish
between calls that can/need to be made when a plugin is instantiated and
calls that make sense to make once we are conntected to a vehicle.
As an example, it does not make sense for a plugin to try to get a
parameter if no vehicle is conntected. This only produces a lot of
warnings and errors and uses up CPU.
The new API does not need to be implemented by plugins yet. For a
transitional period, runtime warnings are displayed if the methods are
not implemented.

add enable/disable API for plugins

---

core/mavlink_commands.cpp

which warns about every subsequent error case
If I get one MAVLink with the result "command denied" it outputs all 4 possible warnings.

mavlink_commands: fix switch case fall through

---

.travis.yml
create_deb.sh

This involved 14 release tests until it finally worked.
Fixes #71.

Fix .deb package generation

---

core/tcp_connection.cpp
core/tcp_connection.h

This should avoid busy looping when a the TCP connection is dropped.
This could fix #201.

core: try to reconnect TCP connection

---

grpc/proto/dronecore.proto
grpc/python_client/CMakeLists.txt
grpc/python_client/async_client.py
grpc/python_client/fly_mission.py
grpc/python_client/multiple_device_handling.py
grpc/python_client/sync_client.py
grpc/server/dronecore_server.cpp.in
grpc/server/plugins/action/action.proto
grpc/server/plugins/action/actionrpc_impl.h
grpc/server/plugins/dronecore/dronecorerpc_impl.h
grpc/server/plugins/mission/mission.proto
grpc/server/plugins/mission/missionrpc_impl.h
grpc/server/plugins/telemetry/telemetry.proto
grpc/server/plugins/telemetry/telemetryrpc_impl.h

Updates Dronecore Server, grpc plugin api's to consider UUID
Updates Python Client examples to take UUID as a parameter for distinguishing between devices
Adds a common plugin to fetch the list of UUID's discovered by dronecore server
Adds multiple_device_handling.py to illustrate an example for handling multiple devices

grpc: Support multiple device handling

---

.gitmodules
CMakeLists.txt

This requires `git submodule sync` afterwards.

curl-android-ios: swap to dronecore fork

---

plugins/offboard/offboard.h
plugins/telemetry/telemetry.h

Corrected in `Telemetry::flight_mode_async()` and
`Offboard::set_velocity_body()` API description. Possibly these are typos.

Correct API description of Telemetry and Offboard plugins.

---

core/device_impl.cpp
core/device_impl.h
core/mavlink_commands.h
plugins/action/action_impl.cpp
plugins/follow_me/follow_me_impl.cpp
plugins/mission/mission_impl.cpp
plugins/offboard/offboard_impl.cpp

Modifies plugins to use `set_flight_mode` instead of using MAV_CMD_DO_SET_MODE
Issue : #193

Set Flight Mode using new interface set_flight_mode in DeviceImpl

---

start_px4_sitl.sh

Fixes Autostart SITL error during launch of integration tests by correcting second argument to [Tools/sitl_run.sh](https://github.com/PX4/Firmware/blob/master/Tools/sitl_run.sh#L66) as part of [start_px4_sitl.sh](https://github.com/dronecore/DroneCore/blob/develop/start_px4_sitl.sh#L53).

Fix issue: https://github.com/dronecore/DroneCore/issues/227

---

generate_docs.sh

Script [genreate_docs.sh](https://github.com/dronecore/DroneCore/blob/904ba588f554562672e79ea9dcc9449096219d47/generate_docs.sh#L26) is looking for build directory existence; but it should actually check `build/default` directory's contents.
After `make clean`, contents of directory `build/default` will be empty.
So, this PR checks whether `build/default` is empty.
#236

Fix `generate_doc.sh` issue (#236)

---

integration_tests/mission.cpp
plugins/mission/mission_impl.cpp
plugins/mission/mission_impl.h

This fixes the case where a mission item gets lost from the autopilot to
DroneCore and we need to request the same one again.
Previously, we just requested the next one, essentially skipping the one
we missed. This then lead the autopilot to respond with a failure
because the wrong sequence was requested.
These fixes go together with:
mavlink/qgroundcontrol#6059
PX4/Firmware#8750

Robustify mission upload/download

---

core/CMakeLists.txt

Android and iOS were not linking curl but just including it.

build_system: fix android build and make curl include more consistent

---

generate_markdown_from_doxygen_xml.py
plugins/action/action.h
plugins/follow_me/follow_me.h
plugins/gimbal/gimbal.h
plugins/info/info.h
plugins/logging/logging.h
plugins/mission/mission.h
plugins/offboard/offboard.h
plugins/telemetry/telemetry.h

Constructors are no longer "for internal use". This change also adds support for verbatim tag in the source, which allows us to specify arbitrary markdown (used in this doc change).

Fix up plugin constructor docs

---

Makefile

- external is now third_party
- the argument -delete prevents "Files not found" while deleting without
the -depth option

Makefile: fix make clean after make android

---

example/offboard_velocity/offboard_velocity.cpp

Pass in offboard plugin instance rather than creating multiple shared pointers.

Fix offboard plugin creation in example

---

core/CMakeLists.txt

This hack is needed because otherwise the tinyxml2 library gets
installed in a library directory that does not respect the ANDROID_ABI.

cmake: install tinyxml2 library for Android

---

example/follow_me/CMakeLists.txt
example/follow_me/fake_location_provider.h
example/follow_me/follow_me.cpp

Related: ([dronecore/docs/#94](https://github.com/dronecore/docs/pull/94))

Fix linker error and lower Boost version in Follow Me example

---

core/CMakeLists.txt

This should resolve linking issues with examples. Once we have it all
packaged, we can change it again.
Fixes #233.

build_system: create a static lib for Mac for now

---

plugins/mission/mission.h
plugins/mission/mission_item.h

Improves documentation for mission plan import.

Update mission docs

---

core/CMakeLists.txt
plugins/CMakeLists.txt

This is just an interim fix in the meantime.
Should fix #233.

build_system: build statically again for Mac

---

core/device.cpp
core/device.h

Commander gets confused if this bit is not set correctly, so we need to
add it.
Also, the _armed and _hitl_enabled flags should both be atomic in order
to be thread-safe, also we should only update the flags if a heartbeat
originates from the autopilot but ignore other components such as the
camera or gimbal.

core: send HITL bit with DO_SET_MODE command

---

appveyor.yml

Appveyor CI should provide 2 cores, so we can make use of that.
This is also in the docs:
https://github.com/dronecore/docs/pull/98

appveyor: try to run on more than one core

---

cmake/unit_tests.cmake

It seems to me that gtest already does something about that
(not sure how, though), see [1] and [2].
[1]: https://github.com/google/googletest/blob/master/googletest/cmake/internal_utils.cmake#L65
[2]: https://github.com/google/googletest/blob/master/googletest/cmake/internal_utils.cmake#L201

build_system: remove flags for unit tests in windows

---

plugins/telemetry/telemetry.h
plugins/telemetry/telemetry_impl.cpp

We now have an interface for the absolute yaw angle of a camera
(respectively a gimbal).
FYI @sanderux.

telemetry: use absolute yaw for camera attitude

---

core/connection.cpp
core/dronecore.cpp
core/dronecore.h
core/dronecore_impl.cpp
core/dronecore_impl.h
core/tcp_connection.cpp
core/tcp_connection.h
core/udp_connection.cpp
core/udp_connection.h

Fix the DroneCore pImpl (some of the implementation had leaked into the base class).
* Pass strings by reference
* Make const arguments const
* Move some defaults value to the consumer instead of the generic classes
* Remove unused members in udp_connection
* Reorder some headers

core: Move implementation into the pImpl.

---

generate_markdown_from_doxygen_xml.py

@JonasVautherin changes in #290 introduced global enums and functions - before all were scoped within classes. Doxygen generates these in a new file namespacedronecore.xml. This change parses the xml file and creates namespacedronecore.md.
As an aside, while there is a fair bit of successful code reuse for this change, I do need to start thinking about whether this can be simplified/broken up to ease future maintenance.

Enable markdown generation for global functions and enums

---

CMakeLists.txt
cmake/unit_tests.cmake
core/device.cpp
core/mocks/dronecore_mock.h
grpc/server/CMakeLists.txt
grpc/server/src/CMakeLists.txt
grpc/server/src/backend.cpp
grpc/server/src/backend.h
grpc/server/src/cmake/compile_proto.cmake
grpc/server/src/connection_initiator.h
grpc/server/src/core/corerpc_impl.h
grpc/server/src/dronecore_server.cpp
grpc/server/src/plugins/action/actionrpc_impl.h
grpc/server/src/plugins/mission/missionrpc_impl.h
grpc/server/src/plugins/plugins.conf
grpc/server/src/plugins/telemetry/telemetryrpc_impl.h
grpc/server/test/CMakeLists.txt
grpc/server/test/connection_initiator_test.cpp
plugins/mission/mission_impl.h

Refactor dronecore_server in order to have it build as a library (for iOS) and to have the connection unit tested (saved me from a few bugs like having the discover callback called multiple times or me calling `register_on_discover` multiple times.
Connects to #238.

238 refactor dronecore server

---

core/CMakeLists.txt
grpc/server/src/CMakeLists.txt
grpc/server/src/backend.cpp
grpc/server/src/backend.h
grpc/server/src/backend_api.cpp
grpc/server/src/backend_api.h
grpc/server/src/core/corerpc_impl.h
grpc/server/src/module.modulemap

When building for iOS, the backend is now automatically built as an iOS Framework that can be directly added in an Xcode project and used (it only exposes the one `runBackend(port)` function).
There are two small glitches regarding dependencies:
* Json11 has to be built as a static library. I still need to figure what's a good way to do that, but maybe for now I will just fork it.
* Tinyxml2 has to be built as a static library. Here, there is a way to do it, but with a not-so-generic variable (`-DBUILD_STATIC_LIBS`) that we may not want to set for the whole project. So I'd like to build tinyxml2 separately (like grpc and others). For now, I don't link it in iOS.
Fixes #294.

294 ios backend framework

---

example/takeoff_land/takeoff_and_land.cpp

Fixes #307.
Currently, takeoff-land example exits if vehicle is not ready for arming.
It should rather wait, until vehicle is ready.

Takeoff land example: Wait until vehicle is ready

---

grpc/server/src/backend.cpp
grpc/server/src/backend.h

_Continuing the discussion we had on the other PR, but this one is not blocking, so we can take more time :-)._
It seems like the destructor must be defined because keeping the default doesn't compile (something like it creates a default destructor, but doesn't know `Impl` at that time.
The other two were apparently there to define them as `noexcept`, but they can be removed since we don't need it. I can also delete them if I do it in `backend.h`, but I'm not sure we actually want that.

backend: clean pImpl

---

core/device.cpp

Fixes #305 
[Currently](https://github.com/dronecore/DroneCore/blob/f308f020205c08d930e1acaa849b332e365d4965/core/device.cpp#L289) GCS type (in Heartbeat) is [MAV_AUTOPILOT_GENERIC](http://mavlink.org/messages/common/#MAV_AUTOPILOT_GENERIC) (its a type for autopilot! not for GCS).
However, MAVLink documentation recommends to use [MAV_AUTOPILOT_INVALID](http://mavlink.org/messages/common/#MAV_AUTOPILOT_INVALID) for GCS.

Correct Autopilot type of Self (GCS)

---

core/device.cpp

This fix was merged earlier but somehow snuck back.
If we reset this flag but don't set the actual UUID to 0, we won't ever
request it again and therefore won't ever discover a device again that
we have discovered before.
This was already removed in #215 but somehow it came back.
@JonasVautherin maybe in a merge? Or was this on purpose?

device: fix reconnect

---

core/device.cpp

This was missed in an earlier commit.
We need to send this because if the bit is set wrongly, commander will
refuse to switch modes.
Follow up to #280.

core: add HIL flag to SET_MODE

---

backend/test/action_service_impl_test.cpp

Modified the unit tests to use parameterized tests. The code is a bit more complex, but it will certainly scale better :-).

backend: use parameterized tests in action_service_impl_test

---

backend/src/backend.cpp

Very small thing, reminding me that I need to put the backend in the CI :)

fix backend following #314

---

generate_markdown_from_doxygen_xml.py

Addresses https://github.com/dronecore/DroneCore/issues/321. Basically a function parameter type for a reference or pointer will now render with the * or & immediately next to the type.
```
#old
Device * somedevice
Device & somedevice
#new
Device* somedevice
Device& somedevice
```
IFF the type is a pointer, then the "*" is escaped (so markdown doesn't think we want to change case to italic).
Note, I decided on aligning symbol to type rather than name, because this works better in more cases.

Function parameter reference/pointer types fix

---

backend/src/plugins/action/action_service_impl.h
backend/test/action_service_impl_test.cpp
core/connection_result.h
example/fly_mission/fly_mission.cpp
example/fly_qgc_mission/fly_qgc_mission.cpp
example/follow_me/follow_me.cpp
example/offboard_velocity/offboard_velocity.cpp
example/takeoff_land/takeoff_and_land.cpp
example/transition_vtol_fixed_wing/transition_vtol_fixed_wing.cpp
integration_tests/async_hover.cpp
integration_tests/follow_me.cpp
integration_tests/mission.cpp
integration_tests/mission_change_speed.cpp
integration_tests/mission_survey.cpp
integration_tests/offboard_velocity.cpp
integration_tests/simple_hover.cpp
integration_tests/takeoff_and_kill.cpp
integration_tests/transition_multicopter_fixedwing.cpp
plugins/action/CMakeLists.txt
plugins/action/action.cpp
plugins/action/action.h
plugins/action/action_impl.cpp
plugins/action/action_impl.h
plugins/action/action_result.h
plugins/action/mocks/action_mock.h

Just as for `ConnectionResult`, move `Action::Result` out of `Action` in order to make it available to others, like `MockAction`.

action: move Action::Result out of action.h

---

integration_tests/gimbal.cpp
integration_tests/offboard_velocity.cpp
plugins/gimbal/gimbal.cpp
plugins/gimbal/gimbal.h
plugins/gimbal/gimbal_impl.cpp
plugins/gimbal/gimbal_impl.h

This implements ROI to let the gimbal point to a region of interest (lon, lat, alt) with an integration test. The test uses offboard to control the drone's position. @julianoes did I see this correctly, there is no 'fly 3 meters to the right' interface?
The integration test can be run with `make &&./build/default/integration_tests/integration_tests_runner --gtest_filter="SitlTest.GimbalROIOffboard"`
It actually looks pretty cool.
Nice work on the SDK @julianoes!

Gimbal: add ROI command

---

backend/cmake/third_party/protobuf/CMakeLists.txt

It should be fixed anyway, and recent commits break the build of the backend right now.

backend: fix protobuf to a specific git commit

---

plugins/mission/mission_impl.cpp

Before importing mission items from a QGroundControl plan, we've to clear old ones; otherwise they would reside along with new mission items, which is not expected. This commit clears them before importing mission items.
Connects to #348.

mission plugin: Clear old mission items

---

core/mavlink_commands.cpp
core/mavlink_commands.h
core/mavlink_system.cpp
core/mavlink_system.h
plugins/action/action_impl.cpp
plugins/gimbal/gimbal_impl.cpp
plugins/logging/logging_impl.cpp
plugins/mission/mission_impl.cpp
plugins/mission/mission_impl.h
plugins/mission/mission_import_qgc_test.cpp

Adds new types `MAVLinkCommands::CmdInt` and `MAVLinkCommands::CmdLong` types that abstract to those of MAVLink protocol:
- http://mavlink.org/messages/common/#COMMAND_INT
- http://mavlink.org/messages/common/#COMMAND_LONG
Also includes the changes in core and plugins, wherever these commands are used. `COMMAND_INT` is used only in Gimbal plugin as of now for `MAV_CMD_DO_SET_ROI_LOCATION`.

Add support for COMMAND_INT and abstraction for the same including `COMMAND_LONG`

---

CMakeLists.txt
cmake/compiler_flags.cmake

Sources generated by protobuf do not compile otherwise. I tried to set the flag only for the generated files with `set_source_files_properties`, but didn't manage to make it work this way.

build_system: remove unused-parameter flag for AppleClang

---

backend/src/CMakeLists.txt
backend/src/backend.cpp
backend/src/backend.h
backend/src/backend_api.cpp
backend/src/backend_api.h
backend/src/connection_initiator.h
backend/src/dronecore_server.cpp
backend/src/grpc_server.cpp
backend/src/grpc_server.h

This PR adds a callback notifying when the gRPC server is started to the backend C api. This is necessary when the frontend starts the backend on the phone, because it needs to wait for the gRPC server to be started before it can initiate a connection.

backend: improve backend api and initialization

---

backend/src/plugins/telemetry/telemetry_service_impl.h
backend/test/telemetry_service_impl_test.cpp
plugins/telemetry/mocks/telemetry_mock.h
plugins/telemetry/telemetry.cpp
plugins/telemetry/telemetry.h

backend: add health to telemetry

---

core/dronecore.h
core/dronecore_impl.cpp
core/mavlink_system.cpp

This PR changes `register_on_discover` in such a way that it directly publishes the uuids of the systems that are already connected. 
Before that, one had query the list of already connected systems, but it probably never makes sense to register to the callback without wanting to know which ones are already connected.
Working on an integration test from Swift.

core: notify already-connected systems on register_on_discover

---

Makefile

So now it should remove everything except for what is in `build/.../third_party/`. It works on my computer, but it's difficult to test more than that...

build_system: fix make clean

---

backend/src/plugins/telemetry/telemetry_service_impl.h
backend/test/telemetry_service_impl_test.cpp
plugins/telemetry/mocks/telemetry_mock.h
plugins/telemetry/telemetry.cpp
plugins/telemetry/telemetry.h

Add the following features to the telemetry module: 
* SubscribeHome
* SubscribeInAir
* SubscribeArmed
* SubscribeGPSInfo
* SubscribeBattery
The tests for all those functions all seem quite similar, but I did not find a good way to have something more compact (e.g. templates). I am not sure it is actually possible (because of the googlemock macros, for one), and I am open to suggestions :-).

Add telemetry features

---

cmake/compiler_flags.cmake
core/dronecore.h
core/dronecore_impl.cpp
core/serial_connection.cpp
core/serial_connection.h
example/fly_mission/CMakeLists.txt
example/fly_mission/fly_mission.cpp

It recently came up on Slack that it would be good to have support for the serial connection on macOS.

Serial connection support for macOS

---

core/CMakeLists.txt
core/cli_arg.cpp
core/cli_arg.h
core/cli_arg_test.cpp
core/dronecore.cpp
core/dronecore.h
core/dronecore_impl.cpp
core/dronecore_impl.h
core/log.cpp
core/log.h
core/serial_connection.cpp
core/serial_connection.h
core/udp_connection.cpp
core/udp_connection.h
example/fly_mission/fly_mission.cpp
example/takeoff_land/takeoff_and_land.cpp
plugins/follow_me/follow_me_impl.cpp

This adds support for serial connections on Windows.
Todos:

Serial connection support for Windows

---

core/mavlink_parameters.h

With an updated iOS system, the clang version gives a warning for that, that we treat as an error.

core: fix conversion that now generates a warning

---

backend/src/plugins/action/action_service_impl.h
backend/test/action_service_impl_test.cpp
plugins/action/mocks/action_mock.h

I had some time in the plane, and this one was convenient to do. It's adding support for all the remaining actions in the backend.
Fixes #315.

Add action features

---

core/mavlink_system.cpp

If we did not successfully receive a param we should not try to cast it
otherwise it will crash with an abort and we'll be quite unhappy.

core: fix bad-cast on param_get fail

---

CMakeLists.txt
appveyor.yml
cmake/compiler_flags.cmake
cmake/tinyxml2.cmake
core/integration_test_helper.h
integration_tests/CMakeLists.txt

Build tinyxml2 statically (to fix the build for iOS).
It may look a bit hacky, but I did not want to pollute the whole scope with options set only for tinyxml2. One alternative would be to fork tinyxml2 and modify its `CMakeLists.txt`, and another one would be to not build tinyxml2 as a submodule (I would like to do that at some point, some kind of "super-build" scheme).
At least it is contained into `cmake/tinyxml2.cmake` for now.
@julianoes let me know if you think we should link it dynamically for some platforms.

build_system: build tinyxml2 statically

---

core/mavlink_system.h

This is a workaround for now because we are conflicting with a component
using MAV_COMP_ID_SYSTEM_CONTROL.

core: use 251 as compid

---

Makefile

Android armeabi is no longer supported by the latest SDK/NDK, so we
might as well remove it here as well.

build_system: remove build for armeabi

---

core/timeout_handler.cpp
core/timeout_handler.h
core/timeout_handler_test.cpp

This fixes the rare case where the "next" timer was deleted during the timeout callback which caused a segfault when iterating (`++`).

Fix timeout handler segfault

---

core/CMakeLists.txt
core/locked_queue.h
core/locked_queue_test.cpp
core/mavlink_commands.cpp
core/mavlink_commands.h
core/mavlink_parameters.cpp
core/safe_queue.h

These are a bunch of fixes to prevent promises getting set more than
once which triggers an abort.
This needs further cleanup, the changes are rather ugly.

mavlink command fixes

---

core/dronecore.h
core/serial_connection.cpp
core/serial_connection.h

This is following up on @hamishwillee's comments in #375 .

Fix connection comments

---

example/fly_mission/CMakeLists.txt
example/fly_qgc_mission/CMakeLists.txt
plugins/CMakeLists.txt

We need to link to libjson11 as well because libdronecore_mission.so doesn't include it.
@JonasVautherin any better idea? Or should we include json11 inside `libdronecore.a` like tinyxml2 to prevent this?
Fixes #381.

fly_qgc_mission: link to json11

---

plugins/mission/mission_item.cpp

@JonasVautherin is this the right fix, or should we add an enum named `UNKNOWN`?
It's a bit silly but it seems the compiler doesn't realize that all cases are covered and we don't need `default`.
The warning with gcc 8.1.1 is:
```
/home/julianoes/src/DroneCore/plugins/mission/mission_item.cpp: In function ‘std::ostream& dronecore::operator<<(std::ostream&, const dronecore::MissionItem::CameraAction&)’:
/home/julianoes/src/DroneCore/plugins/mission/mission_item.cpp:187:1: warning: control reaches end of non-void function [-Wreturn-type]
}
```

mission: fix warning about missing return

---

core/mavlink_system.cpp
core/mavlink_system.h
example/transition_vtol_fixed_wing/transition_vtol_fixed_wing.cpp

Fix VTOL example

---

example/fly_mission/fly_mission.cpp
example/fly_qgc_mission/fly_qgc_mission.cpp
example/follow_me/follow_me.cpp
example/offboard_velocity/offboard_velocity.cpp
example/takeoff_land/takeoff_and_land.cpp
example/transition_vtol_fixed_wing/transition_vtol_fixed_wing.cpp

Some of the examples used `add_any_connection()` and others used `add_udp_connection()`. This changes all examples to have a usage printout and to use `add_any_connection()`.
Note that it doesn't fix all the problems with the examples. Any that fail before, will still fail afterwards.  All it does is make sure that they are started using the same method, allows them to pass a URL, and tells people the URL for the simulator.

Make all examples use add_any_connection()

---

backend/src/plugins/mission/mission_service_impl.h
backend/test/mission_service_impl_test.cpp
plugins/mission/mocks/mission_mock.h

Mission pause

---

.travis.yml
cmake/compiler_flags.cmake

Clang and MSVC are not agreeing on this issue, so we'll ignore
the clang warning for now.

core: fix macOS warning

---

core/system_impl.cpp
core/system_impl.h
integration_tests/camera_mode.cpp
integration_tests/camera_settings.cpp
integration_tests/camera_take_photo.cpp
integration_tests/camera_take_photo_interval.cpp
integration_tests/camera_test_helpers.cpp
integration_tests/camera_test_helpers.h
plugins/camera/camera.cpp
plugins/camera/camera.h
plugins/camera/camera_impl.cpp
plugins/camera/camera_impl.h

Add a synchronous `set_mode` function to the camera interface.
Connects to #334.

camera: add set_mode (synchronous)

---

core/CMakeLists.txt
core/dronecore.h
core/plugin_base.cpp
core/plugin_base.h
core/system.h
generate_docs.sh
plugins/camera/camera.h
plugins/mission/mission_item.h
plugins/telemetry/telemetry.h

With these changes we trigger a CI fail if any comments of the public library exports are missing or wrong. Basically, the `generate_docs.sh` script will exit with 1 if any doxygen shows any warnings.
This fixes #296.

Public comments improvements

---

core/mavlink_commands.cpp
core/mavlink_commands.h

This fixes a lockup that happened when running `camera::set_mode()` in rapid succession in the integration test. The timing was only right to trigger it when run using valgrind.
The command to reproduce this with E90 was:
```
make && valgrind build/default/integration_tests/integration_tests_runner --gtest_filter="CameraTest.SetMode" --gtest_catch_exceptions=0
```

Fix camera set_mode lockup

---

Jenkinsfile

This should prevent caching issues on Jenkins instances.

Jenkinsfile: use tags for images

---

plugins/mission/mission_impl.cpp

We should not silently change takeoff or land mission items to
waypoints. We should at least warn the user about it, even though PX4 is
supposed to do the right thing.
@shakthi-prashanth-m I know that PX4 handles a missing takeoff item fine but what happens when a land item is changed?
FYI @nicovanduijn
Related to #286.

mission: warn if changing takeoff/land to waypoint

---

CMakeLists.txt
backend/src/CMakeLists.txt
backend/test/CMakeLists.txt
cmake/curl.cmake
cmake/unit_tests.cmake
cmake/zlib.cmake
core/CMakeLists.txt
external_example/integration_tests/CMakeLists.txt
external_example/plugins/example/CMakeLists.txt
integration_tests/CMakeLists.txt
plugins/CMakeLists.txt
plugins/camera/CMakeLists.txt
plugins/mission/CMakeLists.txt

This allows DroneCore to be added to any cmake project just by doing:
```
add_subdirectory(path/to/dronecore)
```

Allow DroneCore to be added to built by a parent cmake project

---

plugins/mission/mission_impl.cpp
plugins/mission/mission_import_qgc_test.cpp

When QGC sets a param as `null` it means unchanged which should
translate to NaN for mavlink mission items.
Fixes #422.

mission: import null as NaN

---

backend/cmake/MacOSXFrameworkInfo.plist.in
backend/src/CMakeLists.txt

We need more fields than what cmake was giving us by default. Without this fix, an app using `backend.framework` (e.g. with the Swift frontend) will not pass the Apple validation.
Connects to https://github.com/dronecore/DroneCore-Swift/issues/58.

backend: fix framework Info.plist

---

integration_tests/camera_mode.cpp
integration_tests/camera_settings.cpp
integration_tests/camera_status.cpp
integration_tests/camera_take_photo.cpp
integration_tests/camera_test_helpers.cpp
plugins/camera/camera.cpp
plugins/camera/camera.h
plugins/camera/camera_impl.cpp
plugins/camera/camera_impl.h

This PR adds missing camera subscription APIs:
Connects to #334.

camera: adding subscription APIs

---

core/mavlink_commands.cpp

This fixes the takeoff async integration test where we locked ourselves
out because the takeoff command actually does two commands in
succession, first a mode change, then the takeoff command. What happened
is that we locked ourselves out because we sent the second command in
the callback of the first command which still had the lock.

core: fix lockup of action::takeoff_async

---

backend/cmake/helpers/build_target.cmake

This commit just sets the number of jobs used by make to the number of cpus in the system. This greatly accelerated builds on my system.
I might have more cores than most, but with all current-gen laptops having at least 8 (hyper-/SMT) threads, this should give a nice boost for most users.
TESTED:
`git clone https://github.com/thomasetter/DroneCore.git --recurse-submodules -j 20 && cd DroneCore/ && mkdir build && cd build && cmake .. && make -j12`

Parallelize the builds of dependencies

---

AUTHORS.md
README.md

The README has not received much love in the past months and it was time to go through it.
- Removed AUTHORS.md, we didn't use or update it anywa.
- Added Jenkins CI badge.
- Various corrections, mostly `Device` -> `System`, and new plugins
- Updated URLs to sdk.dronecode.org.

README cleanup

---

core/global_include.cpp
core/global_include.h
integration_tests/mission.cpp
integration_tests/simple_hover.cpp
plugins/action/CMakeLists.txt
plugins/calibration/CMakeLists.txt
plugins/calibration/calibration_impl.cpp
plugins/camera/CMakeLists.txt
plugins/camera/camera_impl.cpp
plugins/follow_me/CMakeLists.txt
plugins/gimbal/CMakeLists.txt
plugins/info/CMakeLists.txt
plugins/info/info_impl.cpp
plugins/logging/CMakeLists.txt
plugins/mission/CMakeLists.txt
plugins/mission/mission_impl.cpp
plugins/mission/mission_import_qgc_test.cpp
plugins/offboard/CMakeLists.txt
plugins/telemetry/CMakeLists.txt
plugins/telemetry/telemetry.cpp

By oversight we did not have the special warnings enabled for the plugins.
This enables the warnings again and fixes a few that crept in. And one was actually a bug so that confirms that warnings are important!

Add plugin warnings

---

README.md

Appveyor and coveralls URLs stay the same for now.
The appveyor URL just stays as far as I can see unless you tell them to change it manually.
For coveralls, ~the rename doesn't work, see https://github.com/lemurheavy/coveralls-public/issues/1156~ the rename was done manually.

README: fix Jenkins and travis-ci badges.

---

integration_tests/calibration.cpp
plugins/calibration/calibration.cpp
plugins/calibration/calibration.h
plugins/calibration/calibration_impl.cpp
plugins/calibration/calibration_impl.h

This adds an API to calibrate the accelerometer of a gimbal.
The only difference to the normal accelerometer calibration is that the command is sent to the component ID of the gimbal.

Gimbal accelerometer calibration

---

integration_tests/CMakeLists.txt
integration_tests/path_checker.cpp
integration_tests/path_checker.h
integration_tests/rtl.cpp
plugins/action/action.cpp
plugins/action/action.h
plugins/action/action_impl.cpp
plugins/action/action_impl.h

This adds the setting to change the RTL return altitude which is the altitude at which the drone will return if RTL is engaged if it is lower (if higher, it will return at the current higher altitude).
The param system needs some refactoring in order to get this to work properly, see #440.
Todo: an integration test for this would be nice.

action: add RTL return altitude setting

---

core/CMakeLists.txt

This is not used anymore. The plugin add the files to be installed themselves.

cmake: remove unused include variable

---

core/locked_queue_test.cpp
core/thread_pool_test.cpp

This makes the thread pool test 10x faster because it was by far slowest.
On the other hand the locked queue test is slightly slowed down to prevent it from intermittently failing.

Improve unit test timing

---

core/system_impl.cpp
core/system_impl.h
integration_tests/action_hover_async.cpp

This PR tries to clean up some of the methods with (too) many arguments.
The most obvious method were `make_command_flight_mode` and `make_command_msg_rate` which contained a return argument, several input arguments, as well as a by-reference output argument.
Instead of having methods with a return argument as well as by-reference output argument, it is nicer to have one std::optional as the return argument only, however, we don't have C++17 (yet) but we can use std::pair in lieu of it.

Cleanup of methods with many arguments

---

core/thread_pool_test.cpp

There is so much jitter in macOS CI on travis that we need to slow down the thead pool test, yet again.

core: fix macOS CI

---

plugins/telemetry/telemetry_impl.cpp
plugins/telemetry/telemetry_impl.h

The sensors of the hardware are not necessarily calibration during HITL (hardware in the loop) simulation. Therefore, let's just assume the calibration is ok for that case.

telemetry: assume sensor calibration ok in HITL

---

core/system_impl.cpp

This is a bugfix for a bug discovered by Jy.wang.
What happened is that when one plugin would want to clear all its
message handlers, the whole mavlink hander table gets cleared and all
other plugins and the core lose their handlers as well.
This bug only manifests itself in practice if you actually destroy a
plugin before others or the core which happens rarely since mostly
everything together is destroyed at the very end.
Fixes  #464.

core: bugfix for clearing message handlers

---

backend/tools/package_backend_framework.bash
backend/tools/push_backend_framework_to_s3.bash
create_packages.sh
fix_style.sh
generate_docs.sh
start_px4_sitl.sh
stop_px4_sitl.sh
travis-docker-build.sh

They say use /usr/bin/env bash instead of /bin/bash because some OSs don't have bash installed or don't have it installed in /bin/bash.

scripts: change shebang

---

Makefile
travis-docker-build.sh

Internet is sometimes flaky in CI. Therefore, in order to avoid unit
tests from failing intermittently, don't run the cURL tests which
download files from s3.
Fixes #368.

Makefile/travis: run offline tests in CI

---

integration_tests/mission.cpp
integration_tests/mission_change_speed.cpp
integration_tests/mission_rtl.cpp
integration_tests/mission_survey.cpp

This shifts the survey mission to the default PX4 SITL origin.
Fixes #247.

integration_tests: reposition survey mission

---

plugins/telemetry/telemetry_impl.cpp

In the current master, the health check for sensor is always set to false if hitl is not enabled.

hitl: assume sensor calibration ok if hitl is set

---

integration_tests/action_hover_async.cpp
integration_tests/action_hover_sync.cpp
plugins/action/action_impl.cpp

This solves the issue where the landed state is unknown right when the action plugin is instantiated and has not received the landed state yet.
Instead of answering with an error straightaway, we can just wait for a bit hoping that we'll receive an answer.
Fixes #291.

action: wait for landed state before responding

---

cmake/compiler_flags.cmake
core/log.cpp

The iOS console does not support colors, therefore we should omit the color magic.

core: don't use colors for iOS

---

core/locked_queue.h
core/locked_queue_test.cpp

With the old implementation, it was not possible to change the values of an item borrowed from the queue because every borrow received a new shared_ptr of a copy of the item.
By storing the items as shared_ptr from the beginning, we can solve this.

core: allow queue items to be changed

---

core/system_impl.cpp

This should resolve an error where we give up to early and therefore
never receive a autopilot version message and therefore we don't know
whether we can use the mission int mode.

core: retry longer to get autopilot version msg

---

CMakeLists.txt

We don't need to install or package this tool. It's only used at build time.

build system: don't install cpp_rsc

---

plugins/mission/mission_import_qgc_test.cpp

As long as we run the unit test from the root of the Dronecode SDK, the
path is fine hard-coded as is.
This fixes the unit test failing on macOS.

mission: fix mission plan path for macOS

---

backend/src/plugins/camera/camera_service_impl.h
backend/test/camera_service_impl_test.cpp
integration_tests/camera_settings.cpp
plugins/camera/camera.cpp
plugins/camera/camera_impl.cpp
plugins/camera/include/plugins/camera/camera.h

Instead of having separate helpers, we now just include it in the Option and Setting structs.

Add camera descriptions

---

CMakeLists.txt
appveyor.yml

We can set the CMAKE_INSTALL_PREFIX using the Makefile anyway, and this default here is actually not needed.

build system: remove unneeded CMAKE_INSTALL_PREFIX

---

appveyor.yml
example/follow_me/CMakeLists.txt
example/follow_me/fake_location_provider.cpp
example/follow_me/fake_location_provider.h
example/follow_me/follow_me.cpp

I'd rather not have the boost dependency, therefore I replaced the usage of the boost event loop with just a thread with a sleep.

example: use thread instead of boost eventloop

---

backend/src/plugins/camera/camera_service_impl.h
backend/test/camera_service_impl_test.cpp
integration_tests/camera_settings.cpp
plugins/camera/camera.cpp
plugins/camera/camera_impl.cpp
plugins/camera/include/plugins/camera/camera.h

This should address a couple of camera issues:
- Added missing setting option description (reported by @douglaswsilva).
- Double free / segfault on exit.
- Fixed camera settings integration test.

camera: add setting option description

---

core/dronecode_sdk_impl.cpp
core/udp_connection.cpp
core/udp_connection.h

This adds support to command multiple drones that connect e.g. on the UDP port 14540.

core: more than one vehicle on one UDP port

---

backend/cmake/MacOSXFrameworkInfo.plist.in
backend/src/plugins/mission/mission_service_impl.h
backend/tools/push_backend_framework_to_s3.bash

The reason for the crash was probably that we fulfilled the promise more than once. Therefore, let's just never stop giving updates like we do it for telemetry as well.

mission: interim fix for crash on mission progress

---

backend/cmake/MacOSXFrameworkInfo.plist.in
backend/src/plugins/mission/mission_service_impl.h
backend/tools/push_backend_framework_to_s3.bash
plugins/mission/mission_impl.cpp
plugins/mission/mission_impl.h

The filtering was done to early and meant that we would send mission progress with equal values in rapid succession. Presumably this triggered a crash in the backend.
The error in GRPC was: `GRPC_CALL_ERROR_TOO_MANY_OPERATIONS`.

Another try to fix mission progress crash

---

backend/src/plugins/mission/mission_service_impl.h
backend/test/mission_service_impl_test.cpp

SubscribeMissionProgress is now an infinite stream (similar to Telemetry) and we must therefore have a way to cancel it (I'm actually thinking that maybe all stream should be implemented like this :thinking:, but that's for later).

backend: fix SubscribeMissionProgress unit tests

---

integration_tests/mission.cpp
plugins/mission/include/plugins/mission/mission.h
plugins/mission/mission.cpp
plugins/mission/mission_impl.cpp
plugins/mission/mission_impl.h

This adds the option to set/get whether RTL should automatically be executed at the end of a mission.

mission: added RTL after a mission is complete

---

core/system_impl.cpp
core/system_impl.h

The fallback to system ID causes problems on systems with multiple
components that might answer but do not actually mean that a vehicle is
connected. For instance the remote controller might also send heartbeats
and trigger a discovery event when really the drone is not discovered
(yet).
In the future we might add an option for UUID vs. system ID but for now
this should resolve the issues described.

core: disable fallback to system ID for now

---

plugins/telemetry/telemetry_impl.cpp

If we listen to the heartbeats from all components the armed flag will flicker. Therefore let's filter by component ID.

telemetry: only listen to autopilot for armed flag

---

plugins/camera/camera_impl.cpp
plugins/camera/camera_impl.h
plugins/camera/include/plugins/camera/camera.h

The conversion is unfortunately duplicated from telemetry/math_conversions. We should fix this sometime.

camera: added Euler angles for capture image

---

backend/cmake/MacOSXFrameworkInfo.plist.in
backend/tools/push_backend_framework_to_s3.bash
plugins/camera/camera_impl.cpp

This should resolve the error where we don't receive the new current
settings when changing one current setting that does not cause any other
settings to change.

camera: fix notification if current options change

---

backend/src/plugins/camera/camera_service_impl.h

backend: fix crash in SubscribeCameraStatus

---

backend/cmake/MacOSXFrameworkInfo.plist.in
backend/src/plugins/camera/camera_service_impl.h
backend/tools/push_backend_framework_to_s3.bash

Fix race in camera backend

---

backend/cmake/MacOSXFrameworkInfo.plist.in

They didn't like the underscores.
@JonasVautherin is that enough?

backend: rename io.dronecodesdk.backend

---

backend/cmake/MacOSXFrameworkInfo.plist.in
backend/tools/push_backend_framework_to_s3.bash
integration_tests/camera_settings.cpp
plugins/camera/camera_definition.cpp
plugins/camera/camera_definition.h
plugins/camera/camera_definition_test.cpp
plugins/camera/camera_impl.cpp

This resolves the issue where the current settings were not notified
after color mode was updated. This happened because color mode does
not lead to any other setting changes except the color mode itself.
In this case `get_unknown_params()` would not find any unknown params
but still return true. The right solution is to get rid of the confusing
return argument and just check the size of the params vector directly.
This is the correct fix instead of #524.

Fix settings notification again

---

core/dronecode_sdk_impl.cpp

Fixes an issue in which if an application (e.g., offboard_velocity) is started
before the simulator is started, a segmentation fault is caused because it
tries to dereference a null pointer.
Signed-off-by: Gabriel Moreno <gabrielm@cs.cmu.edu>

fix SIGSEGV in is_connected() when no system is connected

---

plugins/mission/mission_impl.cpp
plugins/mission/mission_impl.h

This is a hack to hardcode the gimbal yaw angle to absolute for now,
basically custom for the 3DR and H520 integration.

mission: hack to set gimbal angle absolute for now

---

docker/Dockerfile-Fedora-27
docker/Dockerfile-Fedora-28
docker/Dockerfile-Ubuntu-16.04
docker/Dockerfile-Ubuntu-18.04
docker/sudoers.txt

Add sudo so that root commands can be used now docker image defaults to normal user.
Davids-MacBook-Pro:DronecodeSDK dave$ ./run-docker.sh
dronecode@host:~/DronecodeSDK$ make default
dronecode@host:~/DronecodeSDK$ sudo make default install
dronecode@host:~/DronecodeSDK$ sudo ldconfig
dronecode@host:~/DronecodeSDK$ cd example/takeoff_land/build
dronecode@host:~/DronecodeSDK/example/takeoff_land/build$ make

Add sudo to Docker development image.

---

Jenkinsfile

- set timeout to 1 hour
- throw away old build logs, keep 10
- remove unnecessary pipeline agent, blocking the node
- formatting changes for readability

jenkins: add options

---

.travis.yml
Jenkinsfile
create_packages.sh
docker/Dockerfile-Fedora-27
docker/Dockerfile-Fedora-28
docker/Dockerfile-Ubuntu-16.04
docker/Dockerfile-Ubuntu-18.04
docker/entrypoint.sh
docker/sudoers.txt
travis-docker-build.sh

This includes sudo.
This is a follow up to #557.

Jenkinsfile: update to latest docker tag

---

core/serial_connection.cpp

This fixes a bug introduced in #372.
By adding macOS support for serial, I had accidentally removed setting the baudrate for Linux.
Fixes #563.

core: fix baudrate on Linux

---

backend/src/CMakeLists.txt
backend/src/grpc_server.h
backend/src/plugins/calibration/calibration_service_impl.h
integration_tests/calibration.cpp
plugins/CMakeLists.txt
plugins/calibration/calibration_impl.cpp
plugins/calibration/calibration_impl.h
plugins/calibration/include/plugins/calibration/calibration.h

Because of the Rx language bindings, we cannot have more than one return type (that is, one `Result` that says when there is an error and when the stream completes, and one actual struct containing data). This has to be reflected in the C++ API if we want to auto-generate those headers, too.
Moreover, some languages don't have the notion of `NaN` and default to `0` (which is an issue for e.g. a `progress`). For this reason, the resulting struct has booleans to explicitly say if a value is defined or not.
Finally, I tried to remove some code duplication (see [here](https://github.com/Dronecode/DronecodeSDK/compare/calibration-callback-one-result?expand=1#diff-e2a195cc797105ca574a291666fd69ebR77)). It should behave the same in my understanding.

calibration: return only one struct (and the result)

---

example/follow_me/fake_location_provider.cpp
example/follow_me/fake_location_provider.h
example/follow_me/follow_me.cpp
plugins/follow_me/follow_me_impl.cpp

This fixes #408 and makes the example a bit easier to understand. The path is changed from a semi-circular path (which I had broken in the meantime) to just a square. Also, we're now following from behind which is most intuitive to start with.

Some follow-me fixes

---

Jenkinsfile
example/CMakeLists.txt
run-docker.sh

I forgot to add the local user ID in run-docker.sh.
And we should try to compile the examples in CI.

More docker follow-up

---

external_example/integration_tests/CMakeLists.txt

This fixes the paths for me in a try according to:
https://sdk.dronecode.org/en/guide/sdk_extensions.html

external_example: fix paths

---

example/offboard_velocity/offboard_velocity.cpp
example/takeoff_land/takeoff_and_land.cpp

The examples report landed already before the vehicle is landed which is not so nice... ;-)

Fix landed detection

---

backend/src/plugins/camera/camera_service_impl.h
plugins/camera/camera_impl.cpp

Note: That PR is targetting the camera status PR, and not develop.

camera: propagate camera status fixes to other streams in camera service

---

plugins/camera/camera_impl.cpp

camera: return BUSY not IN_PROGRESS if we're busy

---

core/dronecode_sdk_impl.cpp
example/transition_vtol_fixed_wing/transition_vtol_fixed_wing.cpp

This improves the readability of the VTOL example, and also adds some
more action to it by sending it South using `goto_location`.

Improve VTOL example

---

plugins/action/action_impl.cpp

This should fix the issue where the vehicle turns to face North when trying to land which is unnecessary and confusing.

action: don't change yaw when landing

---

core/mavlink_parameters.cpp
core/mavlink_parameters.h
core/system_impl.cpp
core/system_impl.h
integration_tests/CMakeLists.txt
integration_tests/params_raw.cpp
plugins/CMakeLists.txt
plugins/action/action_impl.cpp
plugins/calibration/calibration_impl.cpp
plugins/calibration/calibration_impl.h
plugins/camera/camera_definition.cpp
plugins/camera/camera_definition.h
plugins/camera/camera_definition_test.cpp
plugins/camera/camera_impl.cpp
plugins/follow_me/follow_me_impl.cpp
plugins/params_raw/CMakeLists.txt
plugins/params_raw/include/plugins/params_raw/params_raw.h
plugins/params_raw/params_raw.cpp
plugins/params_raw/params_raw_impl.cpp
plugins/params_raw/params_raw_impl.h
plugins/telemetry/telemetry_impl.cpp
plugins/telemetry/telemetry_impl.h

This adds a plugin to set/get "raw" mavlink params.
This has been tested against the E90.
When setting int parameters, we get an error but the param change still works. Hopefully, this will be fixed on the Firmware side: https://github.com/PX4/Firmware/pull/10792

Add plugin to set params

---

plugins/calibration/calibration_impl.h

Without that, the plugin may get stuck in a BUSY state.

calibration: state should be initialized to NONE

---

core/mavlink_commands.cpp

Same as #589 for develop branch

Fix deadlock between do_work, reveive_timeout and receive_command_ack

---

plugins/mission/mission_impl.cpp

The problem can be reproduced by:
- comment out the handling of MAVLINK_MSG_ID_MISSION_ITEM_INT on the
autopilot
- run the mission upload example
Result: the async mission callback never gets called.
Output:
```
Uploading mission...
[05:35:39|Debug] Send mission item 0 (mission_impl.cpp:996)
[05:35:39|Debug] Send mission item 0 (mission_impl.cpp:996)
[05:35:40|Debug] Send mission item 0 (mission_impl.cpp:996)
[05:35:40|Debug] Send mission item 0 (mission_impl.cpp:996)
[05:35:40|Debug] Send mission item 0 (mission_impl.cpp:996)
[05:35:40|Debug] Send mission item 0 (mission_impl.cpp:996)
[05:35:41|Debug] Send mission item 0 (mission_impl.cpp:996)
[05:35:41|Debug] Send mission item 0 (mission_impl.cpp:996)
[05:35:41|Debug] Send mission item 0 (mission_impl.cpp:996)
[05:35:41|Debug] Send …
```

fix mission upload timeout: need to report the mission result

---

Makefile

Resolves #610

---

integration_tests/calibration.cpp
plugins/calibration/calibration.cpp
plugins/calibration/calibration_impl.cpp
plugins/calibration/calibration_impl.h
plugins/calibration/include/plugins/calibration/calibration.h

This adds a method to cancel an ongoing calibration.

Add calibration cancel (replaces #624)

---

integration_tests/CMakeLists.txt
integration_tests/offboard_attitude.cpp
plugins/action/action_impl.cpp
plugins/offboard/include/plugins/offboard/offboard.h
plugins/offboard/offboard.cpp
plugins/offboard/offboard_impl.cpp
plugins/offboard/offboard_impl.h

I screwed up with git, so here is #621.

Added SetAttitudeTarget message to the off board implementation (same as #621)

---

core/serial_connection.cpp

Required for TCGETS2/TCSETS2 when building on Alpine Linux.

build: add include to fix build for Alpine Linux

---

core/locked_queue.h
core/locked_queue_test.cpp
core/mavlink_commands.cpp
core/mavlink_commands.h
core/mavlink_parameters.cpp
core/mavlink_parameters.h
integration_tests/params_raw.cpp

This is a further attempt following #590 to prevent potential deadlocks.

Improve locked queue deadlocks

---

integration_tests/info.cpp
plugins/info/include/plugins/info/info.h
plugins/info/info.cpp
plugins/info/info_impl.cpp
plugins/info/info_impl.h

This adds support to query the new UUID using the info plugin.
Vehicles only sending the old UUID (uid) are still supported if the uid2 is all zeros as specified.
@bkueng or @thomasetter please review.

info: expose new UUID (uid2)

---

.travis.yml

We don't need this anymore since we changed the releasing back.

travis: remove CI git tag mechanism again

---

.travis.yml
Jenkinsfile
docker/Dockerfile-Fedora-29
docker/build_and_push_docker_images.sh

Fedora 27 has already been end-of-lifed last year, so we should remove it and add Fedora 28 instead.

Remove Fedora 27 CI build and add Fedora 29

---

plugins/action/action_impl.cpp
plugins/telemetry/telemetry_impl.cpp

Previously, the states TAKEOFF and LANDING would be translated to whatever the previous landed state had been. This lead to the fact that we would call disarm in some integration tests when the vehicle was still flying.
This is related to:
https://github.com/mavlink/mavlink/pull/698

Fix interpretation of MAVLink landed enum

---

core/system_impl.cpp

This fixes the case where on plugin initialization, the `std::vector _mavlink_handler_table` is growing and needs to be re-located, however, the iterator is not invalidated as it should because everything moved and we're accessing garbage.

core: fix segfault on plugin init

---

.ycm_extra_conf.py
integration_tests/CMakeLists.txt
integration_tests/mission_raw_mission_changed.cpp
plugins/CMakeLists.txt
plugins/action/action_impl.cpp
plugins/follow_me/follow_me_impl.cpp
plugins/gimbal/gimbal_impl.cpp
plugins/mission/mission.cpp
plugins/mission/mission_item_impl.cpp
plugins/mission_raw/CMakeLists.txt
plugins/mission_raw/include/plugins/mission_raw/mission_raw.h
plugins/mission_raw/mission_raw.cpp
plugins/mission_raw/mission_raw_impl.cpp
plugins/mission_raw/mission_raw_impl.h

This will be a plugin which enables direct/raw access to MAVLink MISSION_ITEM_INT messages.
See progress here @sanderux.

Add mission raw plugin

---

CMakeLists.txt

So that tags like v0.14.0 become 0.14.0 and are valid for Info.plist

cmake: remove the 'v' at the beginning of version tags

---

plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp

When being destructed we should stop to intercept all the messages.

mavlink_passthrough: reset intercepting messages

---

plugins/mission/mission_impl.cpp

This changes the callback used in the case of a timeout while trying to download the mission items. Before we used the wrong one, so never got notified.
This was not caught by the integration tests because they
generally only test the happy path given we had no hooks yet for a lossy link where these things happen.
Found as part of https://github.com/Auterion/mavlink-testing-suite/pull/10.

mission: use correct callback for download timeout

---

plugins/mission/mission_impl.cpp
plugins/telemetry/telemetry_impl.cpp

We  should not get rid of pending timeouts just because the system is reported to be timed out which can happen if we miss a couple of heartbeats in a row due to a lossy connection. We still want to get the notification that our current transaction timed out, otherwise we'll wait for an answer indefinitely (unless the user of the API checks for a timeout again which shouldn't be required).
Found as part of https://github.com/Auterion/mavlink-testing-suite/pull/10.

Plugins: don't remove pending timeouts on disconnect

---

backend/src/plugins/mission/mission_service_impl.h
plugins/mission/mission_impl.cpp

This should fix https://github.com/Dronecode/DronecodeSDK-Python/issues/46 as well as a couple of other potential mission crashes.

Fix mission gRPC server crash

---

core/mavlink_parameters.cpp
plugins/camera/camera_definition_files/e90.xml

This fixes an issue reported by @douglaswsilva.
As part of this pull request I've also updated to the latest E90 camera definition file.
@Stifael or @potaito maybe you can send me the latest E50, ET, etc. camera definition files, so I can add them here.

Fix param set issue

---

CMakeLists.txt

The last argument of STRING REPLACE, which is a variable, has to be
inside double quotes otherwise it may be misinterpreted.

cmake: fix bug in STRING REPLACE

---

plugins/mission/mission_impl.cpp
plugins/mission/mission_impl.h

Previously, the mission protocol was not implemented correctly. What happened was that the activity state did not reflect the different states while uploading or downloading a mission and therefore if a timeout occured we didn't know if we have to retry sending a`MISSION_COUNT` or a `MISSION_REQUEST_INT`; we always defaulted to retrying a `MISSION_REQUEST_INT` which mostly worked except if we had dropped messages in the `MISSION_COUNT` step and so we would request mission item -1 (the initial value of this variable) which is not something that exists.
Found during https://github.com/Auterion/mavlink-testing-suite/pull/10.

mission: extend activity states to retry correctly

---

backend/cmake/third_party/boringssl/CMakeLists.txt
backend/cmake/third_party/cares/CMakeLists.txt
backend/cmake/third_party/grpc/CMakeLists.txt
backend/cmake/third_party/protobuf/CMakeLists.txt
cmake/zlib.cmake

* For some reason, Android now needs zlib to be compiled with -fPIC.
* Update grpc dependencies (BoringSSL was failing to build on Android, and we were stuck on 1 year old dependencies :sweat_smile:)
Builds on linux (default + android), macOS (default, ios, ios_simulator), passes the unit tests and apparently runs the examples fine on linux and iPad (e.g. telemetry, takeoff and land, mission, ...).
Notes:
* Android-NDK r19b requires [this fix](https://android-review.googlesource.com/c/platform/ndk/+/907834) to build. It will come with r19c.
* Still pointing to https://github.com/dronecore/grpc, but [I opened a PR](https://github.com/grpc/grpc/pull/18151) that may help us go back to using upstream.

cmake: fix android build and update grpc dependencies

---

core/global_include.h

No need to min max macro in C++. These functions are defined
in algorithm header in the standard library.

Remove MIN MAX C style macro.

---

backend/test/CMakeLists.txt

NOTE: That's apparently required only for the unit tests target, I'm not sure why it's not failing for the actual binary.

backend: remove warnings from protobuf-generated files

---

core/system_impl.cpp

My first pr to open source project.  Picked from github issues tagged with `beginner`  
**Fixes** #609 
Another solution is to invoke `_parent.is_connected()`  inside `SystemImpl::send_heartbeat()`, which I less preferred: only need to send heartbeats when the system is connected to remote devices. But let the project owner decide :) 
Tested with integration test `AUTOSTART_SITL=1 make run_integration_tests`: 
Before: 
```
[09:29:27|Info ] DronecodeSDK version: 0.14.1 (dronecode_sdk_impl.cpp:25)
[09:29:29|Debug] New: System ID: 0 Comp ID: 0 (dronecode_sdk_impl.cpp:285)
[09:29:29|Error] No known remotes (udp_connection.cpp:130)
[09:29:29|Error] send fail (dronecode_sdk_impl.cpp:91)
Waiting to be ready...
Waiting to be ready...
[09:29:30|Error] No known remotes (udp_connection.cpp:130) …
```

issue#609: only send heartbeat after discovering vehicles

---

plugins/action/include/plugins/action/action.h

Currently, PX4 does not let us specifiy absolute altitudes for goto, so AMSL (above mean sea level) is all we have.
Closes #691.

action: improve docs for goto altitude

---

plugins/mission/mission_impl.cpp

This way we make sure the callback object does not go out of scope before it gets called.
This is a potential fix for #698.

mission: thread safety fixes

---

plugins/camera/camera_impl.cpp
plugins/camera/camera_impl.h

This tries to robustify the thread-safety of the camera plugin. Some of the callbacks and some shared data were not protected by mutexes.
Also, all callbacks are not called from the thread pool workers reducing the chances for deadlocks.
This work is in response to the stacktrace in #698.

camera: thread-safety fixes

---

core/include/dronecode_sdk/connection_result.h
core/serial_connection.cpp
core/serial_connection.h

In order to simplify and to enable the build in manylinux1 it makes sense to go back to termios instead of termios2.

core: get rid of termios2, use termios on Linux

---

core/locked_queue.h
core/locked_queue_test.cpp
core/mavlink_parameters.cpp
core/mavlink_parameters.h
core/system_impl.cpp
core/system_impl.h
plugins/action/action_impl.cpp
plugins/camera/camera.cpp
plugins/camera/camera_impl.cpp
plugins/camera/camera_impl.h
plugins/camera/include/plugins/camera/camera.h
plugins/follow_me/follow_me_impl.cpp
plugins/telemetry/telemetry_impl.cpp

As part of testing against the camera-manager, various issues are coming up.

Various camera improvements

---

backend/cmake/third_party/grpc/CMakeLists.txt

Just point gRPC to a new branch on our fork, fixing the warning. I am trying to bring that fix upstream, but I am not sure if they will accept it because `if(IOS)` is defined by our iOS toolchain, and is maybe not considered a standard thing.

backend: fix 'pointer not aligned' warning in iOS (inside gRPC)

---

plugins/mission/mission_impl.cpp

We need to make sure we set the callback to nullptr while we have the lock. This way we make sure we only ever call the callback once and don't upset the API user.
Fixes #698.

mission: fix double call of result callback

---

core/dronecode_sdk.cpp
core/dronecode_sdk_impl.cpp
core/dronecode_sdk_impl.h
core/include/dronecode_sdk/dronecode_sdk.h
core/mavlink_commands.cpp
core/mavlink_parameters.cpp
core/system_impl.cpp
core/system_impl.h
plugins/camera/camera_impl.cpp
plugins/follow_me/follow_me_impl.cpp
plugins/log_files/log_files_impl.cpp
plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
plugins/mission/mission_impl.cpp
plugins/mission_raw/mission_raw_impl.cpp
plugins/offboard/offboard_impl.cpp

This adds a configuration option in order to set the system and component ID of the SDK, as well as correctly set the MAV_TYPE.
FYI @bkueng @cmic0.

Add configuration option

---

plugins/telemetry/include/plugins/telemetry/telemetry.h
plugins/telemetry/telemetry.cpp

Signed-off-by: Omar Shrit <shrit@lri.fr>

Overload operator<< to print position and velocity ned

---

plugins/mission/include/plugins/mission/mission_item.h
plugins/mission/mission_item.cpp
plugins/mission/mission_item_impl.cpp
plugins/mission/mission_item_impl.h

1. adds _acceptance_radius member variable to MissionItemImpl class
2. adds functions to set and get the acceptance radius
3. changes the get_mavlink_param2() function to return the acceptance radius if it is set,
if it is not, it will return the predefined values (3 or 1 meter) depending on the _fly_through boolean, as it was before
Resolves #713.

Add possibility to set an arbitrary acceptance radius 

---

core/mavlink_parameters.cpp
core/mavlink_parameters.h
plugins/log_files/log_files_impl.cpp

This fixes a char array overflow in strlen in string compare. This happened because the case where the MAVLink param name has length 16 and is not handled correctly. The MAVLink field is not 0 terminated which means that we need to copy to bytes to a 0 terminated buffer first before using it.
Thanks for reporting @douglaswsilva!

mavlink_parameters: fix timeout for 16 char params

---

core/locked_queue.h

Somehow, on one machine these changes were needed in order to avoid MSVC complaining about:
```
warning C4346: 'iterator': dependent name is not a type
```

core: fix MSVC compiler error

---

backend/src/backend.cpp
backend/src/backend.h
backend/src/backend_api.cpp
backend/src/backend_api.h
backend/src/connection_initiator.h
backend/src/dronecode_sdk_server.cpp
backend/test/connection_initiator_test.cpp
core/mocks/dronecode_sdk_mock.h

This allows the backend_bin to be started with any connection URL.
Resolves #587.

Enable backend to accept connection URL

---

backend/test/camera_service_impl_test.cpp

Sometimes TryCancel's best effort is not good enough and it does not seem to be able to cancel it. This means that the promise is blocked in the ServiceImpls and destruction hangs.
Fixes #731.

backend: remove sometimes failing unit tests

---

example/offboard_velocity/offboard_velocity.cpp
plugins/offboard/include/plugins/offboard/offboard.h
plugins/offboard/offboard.cpp
plugins/offboard/offboard_impl.cpp
plugins/offboard/offboard_impl.h

Wanted to include the attitude control in off board mode.
It's implemented. The test is currently included in the offboard_velocity example. 
One could consider renaming and modifying the offboard_velocity example to be called offboard and include attitude_rate as well.
Was unsure about the naming of Attitude, should it be Attitude_ned?
Resolves #473.

Adding attitude control too off board.

---

core/system_impl.cpp
core/system_impl.h
integration_tests/mavlink_passthrough.cpp
plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp

This fixes #740. For more details check commits messages.

Fix MAVLink Passthrough unsubscription

---

backend/src/plugins/offboard/offboard_service_impl.h
backend/test/offboard_service_impl_test.cpp
plugins/offboard/include/plugins/offboard/offboard.h
plugins/offboard/mocks/offboard_mock.h
plugins/offboard/offboard.cpp

`set_attitude` method was added recently to `offboard` plugin and it is not supported in resent `offboard` grpc backend introduced with great [pull request](https://github.com/Dronecode/DronecodeSDK/pull/735) So this adds set_attitude support.

backend support for offboard/set_attitude

---

core/udp_connection.cpp

If we don't ignore the heartbeats from QGC we keep getting the warning that the remote changed on every heartbeat. Eventually we probably need a proper routing fix but this should do for now.
FYI @DanielePettenuzzo

core: hack to ignore messages from QGC for now

---

core/mavlink_parameters.h

This fixes the warning that appeared with GCC 9:
```
core/system_impl.cpp:877:73: error:
implicitly-declared
‘dronecode_sdk::MAVLinkParameters::ParamValue::ParamValue(const
dronecode_sdk::MAVLinkParameters::ParamValue&)’ is deprecated
[-Werror=deprecated-copy]
```
Fedora 30 says hi :smile:!

core: fix deprecated-copy warning in GCC 9

---

appveyor.yml
integration_tests/mission_transfer_lossy.cpp

- The timing checks are relaxed because they were too strict.
- Only mission transfer messages are filtered which should lead to more  consistent test results because other (high rate) messages won't  impact the mission transfers.
Should fix CI in #724.

integration_tests: fix failing mission transfer

---

README.md

Now that DronecodeSDK has been renamed to MAVSDK and has been moved to the mavlink GitHub org, we need to fix the README and badges to reflect this change.

README: rename DronecodeSDK to MAVSDK, fix badges

---

src/plugins/camera/CMakeLists.txt
src/plugins/camera/camera_definition_files/e10t.xml
src/plugins/camera/camera_impl.cpp

This adds support for the [E10T](https://www.yuneec.com/en_GB/accessories/cameras/e10t/specs.html) thermal camera for the Yuneec H520.
Still needs testing.

camera: add support for Yuneec E10T

---

src/integration_tests/offboard_attitude.cpp

I wanted to improve the attitude and altitude control but realized that altitude control was not working well with just the P controller.
Therefore, instead of implementing attitude control using attitude rate using offboard mode it probably makes more sense to implement flips which is what's likely used for rate control.
For attitude or altitude control it's generally easier to actually use the attitude control or altitude (velocity) control API directly.

integration_tests: add attitude rate flips

---

src/backend/src/plugins/camera/camera_service_impl.h
src/backend/test/camera_service_impl_test.cpp
src/plugins/camera/camera.cpp
src/plugins/camera/camera_impl.cpp
src/plugins/camera/camera_impl.h
src/plugins/camera/include/plugins/camera/camera.h

It turns out we can no longer set streams using MAVLink but we can only receive the information.
Resolves #755.

camera: update mavlink and remove stream settings

---

DronecodeSDKConfig.cmake.in
src/backend/src/CMakeLists.txt
src/backend/test/CMakeLists.txt

Let's install `backend_bin` in `<INSTALL_PREFIX>/bin`, alongside `libs` and `include`. So that later it will be possible to fetch that as release artifacts.

install backend_bin with libs and includes

---

.travis.yml
tools/create_packages.sh
tools/travis-docker-build.sh

- Deploy manylinux backend binary
- Deploy macos backend binary
- Fix rpm/deb deployment (that I broke when reorganizing the deps)
Notes:
- The rpm/deb packages now include `backend_bin` (which I believe we should rename, e.g. to `mavsdk_backend`, but I will open another PR to discuss that).
- I removed a few `Debug` builds, as it doubles the build time and that's important when building with `-DBUILD_BACKEND=ON`. If we really need to build in Debug mode, we could make a nightly build, IMO.
- `create_packages.sh` is now called by `travis-docker-build.sh`, which IMO makes it cleaner since the later also calls `fix_style.sh` and `generate_docs.sh`.
- `create_packages.sh` takes arguments now. The intent is to make it easier to use without relying on a convention like: "install into …

Improve travis deployment

---

src/backend/src/CMakeLists.txt
src/backend/test/CMakeLists.txt

Note: it is conflicting with #769 (which assumes `backend_bin`)!
When installing mavsdk on the system, one will currently have `/usr/lib/libbackend.so` and/or `/usr/bin/backend_bin`. We should probably make that a bit more explicit. This PR proposes `/usr/lib/libmavsdk_backend.so` and `/usr/bin/mavsdk_backend_bin`.
Other ideas could be `mavsdk_server`, `mavsdk_bin`. @julianoes what do you think?

backend: rename for packaging

---

.travis.yml

Otherwise Travis tries to deploy `backend_bin`, which does not exist anymore.

Fix deployment after backend_bin got renamed to mavsdk_server

---

src/backend/src/core/core_service_impl.h
src/backend/src/plugins/telemetry/telemetry_service_impl.h

Write should not be called again before it is finished.
That can happen with our thread pool, hence the mutex.
It seems like it was not crashing before, and the recent
update of grpc made it visible when running on iOS.
Resolves [this issue](https://github.com/mavlink/MAVSDK-Swift/issues/133).

fix race condition in grpc streams

---

example/multiple_drones/multiple_drones.cpp

Before, there was just a boolean variable that would be set to true, even if one drone is discovered and the program wouldn't exit. Now, I made it so all the systems specified in command line arguments must be found, otherwise, the program will exit.

Error checking fixed for multiple-drones

---

src/plugins/camera/camera_impl.cpp
src/plugins/camera/camera_impl.h

We have been seeing deadlocks connected with the camera plugin presumably due to deadlocks which then block the receiving thread.
On inspection I found a couple of callbacks from the camera plugin which had not been using the thread pool. Hopefully fixing these to all use the thread pool might fix the issues.
Hopefully fixes: https://github.com/mavlink/MAVSDK-Swift/issues/138.

camera: fixes to prevent deadlocks

---

src/backend/src/plugins/mission/mission_service_impl.h
src/backend/test/mission_service_impl_test.cpp

Seems like this field was just ignored...
Resolves [this issue in Swift](https://github.com/mavlink/MAVSDK-Swift/issues/137).
@byuarus @douglaswsilva: FYI

bugfix: camera_photo_interval is not set correctly

---

src/plugins/telemetry/telemetry_impl.cpp
src/plugins/telemetry/telemetry_impl.h

This adds a timeout to actually set local and global position health flags to false if we lose GPS.
This implementation is still clunky until we have the events interface.
Fixes https://github.com/mavlink/MAVSDK-Python/issues/94.

telemetry: fix position health flags on GPS loss

---

src/core/serial_connection.cpp

When nothing weas being received over serial the destruction of the serial connection hung waiting for a read to complete.
By using a timeout every second, we can recover after one second. It's not optimal but better than stalling completely.

core: fix destruction of serial connection

---

src/core/mavlink_include.h
src/plugins/mavlink_passthrough/CMakeLists.txt
src/plugins/mavlink_passthrough/include/plugins/mavlink_passthrough/mavlink_passthrough.h

The mavlink_include.h file contains a pragma to ignore warnings which is helpful when the MAVLink include is used by library users through the mavlink_passthrough plugin.
This came up in https://github.com/Auterion/mavlink-testing-suite/pull/23#discussion_r305914857.

mavlink_passthrough: re-use mavlink_include.h

---

src/plugins/action/action_impl.cpp

After https://github.com/mavlink/mavlink/pull/1162
we need to add a magic number to the disarm command in order to disarm the vehicle even if in-air.

action: use magic number to kill

---

src/core/system_impl.cpp
src/plugins/telemetry/include/plugins/telemetry/telemetry.h

This restores the functionality for messages to be stopped entirely or the rate set to the default which was lost a while ago. Also, it's now documented in the telemetry API docstrings.

Allow messages to be stopped or rate set to default

---

src/backend/src/plugins/offboard/offboard_service_impl.h
src/backend/test/offboard_service_impl_test.cpp

This is fixing a typo in the `mavsdk_server`. That typo was first fixed [in the offboard proto file](https://github.com/mavlink/MAVSDK-Proto/pull/94).
@codekalyan: FYI

Fix NED -> Ned typo in mavsdk_server

---

src/core/mavlink_parameters.h
src/plugins/camera/camera.cpp
src/plugins/camera/camera_definition.cpp
src/plugins/camera/camera_definition.h
src/plugins/camera/camera_definition_test.cpp
src/plugins/camera/camera_impl.cpp
src/plugins/camera/camera_impl.h
src/plugins/camera/include/plugins/camera/camera.h

The information whether a parameter is a range parameter was not yet properly exposed. This makes sure we don't just expose it in `SettingOptions` but also in `Setting`.

Camera: add is_range flag

---

src/core/CMakeLists.txt
src/integration_tests/CMakeLists.txt

CMakeLists integration_tests: use relative cmake path
CMakeLists core: include binary dir to get version.h

CMake changes to support MAVSDK as submodule

---

src/plugins/gimbal/include/plugins/gimbal/gimbal.h

This should clarify the reference frame for the yaw angle, now that we have support for the gimbal mode.

gimbal: comment for reference frame for yaw angle

---

src/plugins/mission/mission_impl.cpp
src/plugins/mission/mission_impl.h

This solves an edge case where we thought a mission was already finished because we still had the previous mission progress stored.
Also, this adds a change so we don't act on mission acks that we did not expect.
@douglaswsilva I found this while debugging `mission_clear`.

Fix mission progress edge case

---

src/core/system_impl.cpp

I think we can remove this because we no longer check for any heartbeat to see if something is connected but we should actually check for `has_autopilot()` or `has_camera` to determine what we have available.
FYI @MatejFranceskin

core: don't filter from UDP_BRIDGE anymore

---

src/core/serial_connection.cpp

This PR adds a serial config option `O_NONBLOCK`. This solves the problem of the serial configuration haning when run on a Pocket Beagle.
P.S. This issue was not present when testing on a intel Nuc, and only visible on the pocket beagle.
@julianoes

Add O_NONBLOCK to the serial config for LINUX

---

src/backend/src/CMakeLists.txt

For some reason, MSVC is the only one not allowing us to generate `mavsdk_server` as both an executable and a library.
Resolves #814.

generate mavsdk_server_bin.exe instead of mavsdk_server.exe with MSVC

---

src/core/mavlink_parameters.cpp

This could workaround a potential problem with E90 where the MAVLink parameter type does not match the xml type.
@byuarus please test. I ran out of time to test this against an E90 but I thought it was worth a shot.

mavlink_parameters: workaround for param mismatch

---

src/core/mavlink_parameters.cpp
src/core/mavlink_parameters.h
src/core/system_impl.cpp

Due to [this](https://github.com/mavlink/MAVSDK/issues/736#issuecomment-522110195) conversation:
- Seems that MAVSDK has no way to know that parameter was changed on UAV after reboot or using console or QGC, for example
- Use cases of MAVSDK probably does not include real necessity of fast frequency parameters values polling (which may require cache using)

Remove caching in params module

---

src/integration_tests/integration_test_helper.h
tools/start_px4_sitl.sh
tools/stop_px4_sitl.sh

We should not sleep and wait for the simulator if we're not even using the start/stop scripts.

integration_tests: only sleep if required

---

src/core/udp_connection.cpp

Some messages like [ATT_POS_MOCAP](https://mavlink.io/en/messages/common.html#ATT_POS_MOCAP) don't have `target_system` field.
For these messages [`mavlink_get_msg_entry()`](https://github.com/mavlink/c_library_v2/blob/a66f06dd300338aef7da306b403941bd9c0dd3a8/mavlink_helpers.h#L491) returned struct [`mavlink_msg_entry`](https://github.com/mavlink/c_library_v2/blob/a66f06dd300338aef7da306b403941bd9c0dd3a8/mavlink_types.h#L289) with field `target_system_ofs` setted to `0` (see [comment](https://github.com/mavlink/c_library_v2/blob/a66f06dd300338aef7da306b403941bd9c0dd3a8/mavlink_types.h#L287) and for example  [`MAVLINK_MESSAGE_CRCS`](https://github.com/mavlink/c_library_v2/blob/a66f06dd300338aef7da306b403941bd9c0dd3a8/common/common.h#L27) entry for msg `#138`).
So we need to check is this …

Target system ID check fix

---

src/CMakeLists.txt

It looks like this was not needed anymore.

cmake: remove unneded version define

---

src/core/CMakeLists.txt
src/core/geometry.cpp
src/core/geometry.h
src/core/geometry_test.cpp

This adds functionality to convert from local coordinates in meters to global latitude/longitude and back.
This will be used to easily create tests missions without hard-coded latitude/longitude coordinates.

core: add geometry file for global/local frames

---

.travis.yml

That's actually one of the benefits of versioning the generated source files, and somehow I forgot to propagate it to CI :sweat_smile:.

Remove default build in ios and ios_simulator in CI

---

third_party/libressl/CMakeLists.txt

So that we don't need a different for iOS anymore.

Update libressl to 3.0.1

---

src/integration_tests/mavlink_passthrough.cpp

Depending on timing, we sometimes tried to fulfil the promise twice which leads to an abort.
This should fix the intermittent CI failure for the MavlinkPassthrough test:
```
HIGHRES_IMU.temperature [1] (100)32 degrees C (mavlink_passthrough.cpp:61)
terminate called after throwing an instance of 'std::system_error'
what():  Resource deadlock avoided
```
This happened for instance here: http://ci.px4.io:8080/blue/organizations/jenkins/mavlink%2FMAVSDK/detail/PR-881/2/pipeline/#step-354-log-2082

integration_tests: fix intermittent test fail

---

.travis.yml

Should release `mavsdk_server_linux-armv7`, too.
Fixes #680.

add linux-armv7 to travis

---

src/core/system_impl.cpp
src/core/system_impl.h
src/plugins/action/action_impl.cpp
src/plugins/action/action_impl.h
src/plugins/telemetry/telemetry_impl.cpp
src/plugins/telemetry/telemetry_impl.h

This removes most of the workaround where we switch to HOLD before arming. This was mostly out of precaution but as discussed in #50 it can hopefully safely get dropped now.
This also includes some refactoring and cleanup of the action plugin.
For reviewing, please check the individual commits and messages.
Fixes #50, fixes #614, fixes #855.

Remove switching to HOLD mode before arm and takeoff

---

.travis.yml

It turns out we're currently building a 32 bit Windows exe. It seems to work in Python 64 bit and 32 bit, so for now that's good enough.
```
.\sigcheck64.exe .\mavsdk_server_bin.exe
Sigcheck v2.73 - File version and signature viewer
Copyright (C) 2004-2019 Mark Russinovich
Sysinternals - www.sysinternals.com
C:\Users\MaEtUgR\Downloads\mavsdk_server_bin.exe:
Verified:       Unsigned
Link date:      13:39 31.10.2019
Publisher:      n/a
Company:        n/a
Description:    n/a
Product:        n/a
Prod version:   n/a
File version:   n/a
MachineType:    32-bit
```

travis: change name of exe as it's 32 bit

---

src/plugins/action/action_impl.cpp

Looking at [`action_impl.cpp`](https://github.com/mavlink/MAVSDK/blob/develop/src/plugins/action/action_impl.cpp#L48-L50), I see:
```cpp
void ActionImpl::enable()
{
...
_parent->get_param_float_async(TAKEOFF_ALT_PARAM, nullptr, this);
_parent->get_param_float_async(MAX_SPEED_PARAM, nullptr, this);
_parent->get_param_float_async(TAKEOFF_ALT_PARAM, nullptr, this);
}
```
First, it seems like `TAKEOFF_ALT_PARAM` is called twice :see_no_evil:. Second, I believe that this is superfluous, as it is queried again in [`get_takeoff_altitude`](https://github.com/mavlink/MAVSDK/blob/develop/src/plugins/action/action_impl.cpp#L377).
Maybe that was used to populate the cache in the past, and we forgot to remove it?

Remove superfluous GET_PARAM in action plugin

---

src/plugins/camera/camera_impl.cpp

This fixes a few potential deadlocks for users of the API trying to do another API call within the callback as well as one deadlock reported in https://github.com/mavlink/MAVSDK-Swift/issues/160.
Fixes https://github.com/mavlink/MAVSDK-Swift/issues/160.
Could you test this one @douglaswsilva?

Fix camera settings deadlocks

---

src/backend/src/core/core_service_impl.h
src/backend/src/plugins/shell/shell_service_impl.h

`set_allocated_*` and `release_*` should only be used in rare cases as their usage is error-prone.
My intuition is that there is not currently a valid use-case for these functions in MAVSDK.
Protos can also be returned by value, which can avoid some heap allocations compared to `unique_ptr`-wrapped values and will use move assignment for things like this:
```C++
MySubMessage build_submessage();
MyMessage build_message() {
MyMessage result;
*result.mutable_submessage() = build_submessage();
return result;
}
```

Fix an unnecessary use of set_allocated 

---

.clang-format

This seems to be necessary with Clang 9.

clang-format: prevent style changes

---

src/backend/src/plugins/telemetry/telemetry_service_impl.h
src/plugins/telemetry/mocks/telemetry_mock.h

This was missing. Fixes https://github.com/mavlink/MAVSDK-Python/issues/135.

backend: added missing server part for LandedState

---

src/core/system_impl.cpp
src/core/system_impl.h
src/integration_tests/info.cpp
src/plugins/info/include/plugins/info/info.h
src/plugins/info/info.cpp
src/plugins/info/info_impl.cpp
src/plugins/info/info_impl.h

The flight information mavlink message was so far available only in the camera plugin. In this plugin the user can extract the flight_uuid as part of the folder name that the SDK creates for your photos. This will only work if you have a camera hooked up. 
This pr adds the flight information to the info plugin. The plugin automatically starts and periodically sends the mavlink command to get the flight information. The use can then pull out this info with the get_flight_information()  method. 
@julianoes if you confirm that this makes sense I will add comments everywhere to keep the same structure as the other oomments in the header files.

add flight information to Info plugin

---

src/plugins/telemetry/telemetry_impl.cpp
src/plugins/telemetry/telemetry_impl.h

It's only possible to get attitude information via quaternion messages with the actual implementation.
There is vehicles that the default attitude message is ATTITUDE and not ATTITUDE_QUATERNION.
This patch allow both messages to be used. 
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

telemetry_impl: Add process_attitude call

---

src/core/mavlink_parameters.h

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

core: Fix if else typo in mavlink_parameters

---

src/core/mavsdk.h
src/core/mavsdk_impl.cpp
src/core/udp_connection.cpp

This adds a way for MAVSDK to advertise itself as an autopilot.
@julianoes: I hardcoded the system id to 1. Is that a valid first implementation, or should I look into having it as a parameter somewhere?

Add configuration to run MAVSDK on the autopilot side

---

src/backend/src/backend.cpp
src/backend/src/backend.h
src/backend/src/backend_api.cpp
src/backend/src/backend_api.h
src/backend/src/connection_initiator.h
src/backend/src/grpc_server.cpp
src/backend/src/grpc_server.h
src/backend/src/mavsdk_server.cpp

The new default is to leave `mavsdk_server` choose a free port for the gRPC server.
The port can be set with `-p <port>`, for instance:
```
./mavsdk_server -p 50051 udp://:14540
```
The next step would be to send the port over the callback of `runBackend(...)`, so that bindings like Swift or Python can actually directly know it and easily start multiple instances of `mavsdk_server`.

Set listening port of mavsdk_server in order to run multiple instances in parallel

---

src/backend/src/CMakeLists.txt

Same as for iOS, we want `libmavsdk_server.so` for Android. Also we don't want to build `mavsdk_server`, which I believe fails at the moment anyway.

Only build libmavsdk_server.so for Android (and not mavsdk_server)

---

src/core/system_impl.cpp
src/core/system_impl.h

This should fix a segfault due to a race which seldomly happened, about 1/100 or 1/1000 cases.
The events leading to the segfault are as follows:
1. A plugin is constructed and calls register_plugin.
2. register_plugin calls enable() of the plugin which does all message registrations/subscriptions.
3. While the plugin is still initializing, MAVLink messages are already being received and distributed to the plugins.
4. Before the callbacks are called from the _mavlink_handler_table the lock is released and acquired again after the callback.
5. If it now happens that a new message is registered right at the moment after the unlock before the callback is called, the iterator might be invalidated. (For instance if the vector data is moved
because its capacity needs to be doubled.)
6. We then …

core: fix segfault on register_plugin

---

tools/generate_changelog.py

Right now it crashes if a PR does not have a label. With this change, it will complain and print the url of the PR.

Improve error handling in changelog generator script

---

src/core/system_impl.cpp
src/core/system_impl.h
src/plugins/telemetry/include/plugins/telemetry/telemetry.h
src/plugins/telemetry/telemetry.cpp
src/plugins/telemetry/telemetry_impl.cpp

Hello,
Based on this #912 , there is a gap for PX4 modes to get flight modes from telemetry plugin. I added on PR but there is also problem about this PR. I'm using very old version (about 5 months ago), so there are some changes for implementation in current version. 
For example;
https://github.com/bozkurthan/MAVSDK/blob/782022d72be38ed30e77308e0336de511245733a/src/plugins/telemetry/telemetry_impl.cpp#L885-L908
I didn't change this function. I can also add these lines and test this on SiTL. But currently it's working for me.

Additional Flight Modes

---

src/plugins/action/action.cpp
src/plugins/action/action_impl.cpp
src/plugins/action/action_impl.h
src/plugins/action/include/plugins/action/action.h

This allows to shut an autopilot (including additional onboard components) cleanly down. As the existing reboot action has the same corner cases (regarding an in-flight state) the overall expected design pattern is that the autopilot has authority over wether it reboots / shuts down or not in safety critical conditions (e.g. while being armed).

Add shutdown action

---

.github/workflows/main.yml
.travis.yml
tools/run-sitl-tests.sh

All our Travis jobs are here except for manylinux1-x64, which requires a custom image (because of perl). I believe we could move to manylinux2010-x64 for the next release, and it should not affect our python users. Also, I am not sure about the coverage (maybe more work is needed there).
In my limited experience with github actions, I'm quite impressed. Jobs are always starting directly, all in parallel, the config syntax is actually pretty nice (I find it even more compact than Travis), and it is more integrated into github (e.g.  deployment [seems fairly easy](https://github.com/marketplace/actions/github-action-publish-binaries)). Moreover, it apparently allows self-hosted nodes, but I haven't tried that.
I believe that this will allow us to deploy `mavsdk_server.framework` from the CI …

Add build and tests in github actions (no deployment)

---

src/plugins/shell/include/plugins/shell/shell.h

The docs build took the '\n' to literal.

shell: fix docs build

---

src/plugins/mocap/mocap_impl.cpp

To continue my work on microservice versioning (See https://github.com/PX4/Firmware/pull/13565 and https://github.com/mavlink/qgroundcontrol/pull/8065), I need to use my own custom MAVLink C library. However, the latest MAVLink message definition adds a new field to a message. I have updated MAVSDK to cope with this, and also updated to the latest MAVLink C library.

Updated MAVLink C library and fixed issue with mocap

---

src/plugins/mission/mission_impl.cpp

This was broken in the previous fix. The activity state would always be NONE if it is changed before it is used/checked.
Thanks @douglaswsilva!

mission: fix timeout notification

---

src/plugins/offboard/offboard_impl.cpp

If we don't stop the call_every calls before destruction, we can run into segfaults where the method is destructed but still called.

offboard: fix crash on plugin destruction

---

.github/workflows/main.yml

If we don't build on pull_request, then pull requests from forks are not built. By only building pushes to master and develop though we get rid of the duplicate builds otherwise.

workflows: build PRs from forks too

---

src/core/mavlink_parameters.cpp
src/core/mavlink_parameters.h
src/plugins/telemetry/telemetry_impl.cpp

Follow up to #970.
Manually tested against SITL with a lossy link.

Add mavlink parameter retry (follow up)

---

.github/workflows/main.yml

Before this we would also try to publish the `develop` branch because the ref contains a `v`.

workflows: only publish if actual version tag

---

tools/run-sitl-tests.sh

We need to include the passthrough plugin for the lossy mission transfer test.

Add lossy mission transfer test to CI

---

example/fly_multiple_drones/fly_multiple_drones.cpp

The comments in the `fly_multiple_drone` example seems to contain outdates paths.
This PR fixes the comments to run the example correctly

Fix fly_multiple_drone example comments

---

src/backend/src/plugins/action/action_service_impl.h
src/backend/test/action_service_impl_test.cpp

In response to [this issue](https://github.com/mavlink/MAVSDK-Python/issues/85) in mavsdk-python.
I'm not entirely sure what's the contributing flow here.
Are there any unit tests to be updated?
Should I just compile & check if it works? @JonasVautherin

fixed SetTakeoffAltitude to include action result in response

---

src/cmake/compiler_flags.cmake

This is required for `log.h` to enable logcat (I probably removed that when refactoring a while ago).

add compiler definition for Android

---

src/backend/src/backend.cpp
src/backend/src/backend.h
src/backend/src/backend_api.cpp
src/backend/src/backend_api.h
src/backend/src/grpc_server.cpp
src/backend/src/grpc_server.h
src/backend/src/mavsdk_server.cpp

This changes the C API from having only `runBackend()` to having `runBackend()`, `getPort()`, `attach()` and `stopBackend()`.
`runBackend()` is not blocking anymore, and that's replaced by `attach()`.
I had to remove the namespaces because that's not working with the C API. The alternative would be to have ifdefs in the API file (to differentiate between `struct MavsdkServer*` and `mavsdk::backend::MavsdkServer*`, and I am not sure what's worse. Here I find the `backend_api.h` file quite clear, at the cost of losing the namespaces only for the API files (`backend_api.*` and `backend.*`).
The limitation now is that if you register to an infinite stream and try to `stopBackend()`, then it will hang forever, waiting for the stream to finish (which won't happen since it is infinite). I fixed …

Add api to stop `mavsdk_server`

---

src/core/mavlink_mission_transfer.cpp
src/core/mavlink_mission_transfer.h
src/core/mavlink_mission_transfer_test.cpp
src/plugins/mission/include/plugins/mission/mission.h
src/plugins/mission/mission_impl.cpp

this feature has been removed in commit c6f67067c160759b4a738aabf3a9443e0e48c055. It allows to set the current item in a mission (async)
related to issue #1003

Add mission set current item feature

---

src/integration_tests/mission_raw_mission_changed.cpp
src/plugins/mission_raw/include/plugins/mission_raw/mission_raw.h
src/plugins/mission_raw/mission_raw.cpp
src/plugins/mission_raw/mission_raw_impl.cpp
src/plugins/mission_raw/mission_raw_impl.h

This is a first draft and it just compiles yet but it bothers me that it is just copy/paste (but not exactly) from Mission....
I feel it would do more sense to do a `MissionRawItem` rather than `MissionRaw`. For me, `MissionRaw` is just a lower level than `MissionItem`. And `MissionItem` would just use `MissionRawItem`. If we want high level functionalities we'll use `MissionItem` and for more advanced settings like I need we can work with `MissionRawItem`.
also the `MavlinkMissionItemInt` is exactly a `MAVLinkMissionTransfer::ItemInt` so I don't get the purpose to create another struct for that

Upload mission raw

---

examples/fly_mission/fly_mission.cpp
examples/fly_multiple_drones/fly_multiple_drones.cpp
examples/fly_qgc_mission/fly_qgc_mission.cpp
examples/follow_me/follow_me.cpp
examples/mavlink_ftp_server/mavlink_ftp_server.cpp
examples/multiple_drones/multiple_drones.cpp
examples/offboard_velocity/offboard_velocity.cpp
examples/takeoff_land/takeoff_and_land.cpp
examples/transition_vtol_fixed_wing/transition_vtol_fixed_wing.cpp
src/plugins/follow_me/include/plugins/follow_me/follow_me.h

When Action got changed with the autogeneration of gRPC bindings, etc, Action::Result enum values changed from uppercase to title case - this PR reflects those changes in the examples. It also fixes the mavlink_ftp_server example, which was broken when I implemented the new Configuration system a short while back.

Update examples based on recent Action class renaming

---

src/core/timesync.cpp
src/core/timesync.h

The timesync protocol expects clock offsets to be constant (or at least have constant skew), however the MAVSDK has an initial big change when syncing with the flight controller. This can confuse other systems on the mavlink network.
This prevents the MAVSDK from responding to other timesync messages until its own timesync with the autopilot time has been determined.
This is a ~~fix~~ cover up for #1033 . The real fix is to allow the flight controller, MAVROS, etc to have multiple different external systems timesynced at the same time.
FYI @irsdkv  @DanielePettenuzzo @JonasVautherin 
Fixes #1033.

Don't respond to timesync until time known

---

templates/mavsdk_server/enum.j2
templates/plugin_cpp/enum.j2
templates/plugin_h/enum.j2

This is slightly simplifying the templates, and at least making the whole thing more consistent over all language bindings.

Handle the enum prefix logic in the protoc plugin

---

templates/plugin_h/stream.j2

That's typically the case if it is a finite stream (e.g. in the `calibration` plugin)

Stream callback may need to return a result 

---

tools/fix_style.sh

If not available on the system, the suggestion is to use it from docker.
This is required because Arch Linux already went to clang-format 10 and these versions don't ever seem to be backward compatible :angry:.

tools: force usage of clang-format version 9

---

src/backend/src/generated/calibration/calibration.pb.cc
src/backend/src/generated/calibration/calibration.pb.h
src/backend/src/plugins/calibration/calibration_service_impl.h
src/integration_tests/calibration.cpp
src/plugins/calibration/calibration.cpp
src/plugins/calibration/calibration_impl.cpp
src/plugins/calibration/include/plugins/calibration/calibration.h

This makes the streams more generic: 
* SUCCESS means that the stream ended successfully
* NEXT means that a new element is being sent (hence the stream is continuing)
* Everything else is an error and raises/throws an exception

Replace IN_PROGRESS and INSTRUCTION by NEXT in finite streams

---

examples/mavlink_ftp_client/mavlink_ftp_client.cpp
src/integration_tests/mavlink_ftp.cpp
src/plugins/mavlink_ftp/include/plugins/mavlink_ftp/mavlink_ftp.h
src/plugins/mavlink_ftp/mavlink_ftp.cpp
src/plugins/mavlink_ftp/mavlink_ftp_impl.cpp
src/plugins/mavlink_ftp/mavlink_ftp_impl.h

In my view it makes more sense to have a function to compare a local to a remote file instead of exposing the internal crc32 checking.
@MatejFranceskin let me know what you think.

mavlink_ftp: remove crc calls, add compare call

---

examples/ftp_client/ftp_client.cpp
examples/ftp_server/ftp_server.cpp

I think these are left overs after the last renaming that was done for the mavlinkftp classes. These prevented me from building both the client and the server.

Fix ftp examples compile issues

---

src/plugins/info/info_impl.cpp

I had this issue that when I update to the latest mavsdk the last character in my uid2 was not included in the hardware_uid in the info plugin. This is because snprintf doesn n-1 in the length argument. 
FYI @JonasVautherin

fix to include the last byte in the uid2 in the hardware_uid string

---

src/CMakeLists.txt
third_party/grpc/CMakeLists.txt
third_party/grpc/absl-workaround.patch

This should fix a stall that we have seen in the backend unit test.
Now really fixes #977.

third_party: update gRPC

---

tools/generate_camera_definitions.sh
tools/generate_from_protos.sh

Follow up to #1090.
This is because -S is not supported yet with cmake 3.5.1 on Ubuntu 16.04.
Found by @TSC21.

tools: consistently use cmake -H

---

src/backend/src/plugins/calibration/calibration_service_impl.h
src/backend/src/plugins/camera/camera_service_impl.h
src/backend/src/plugins/ftp/ftp_service_impl.h
src/backend/src/plugins/log_files/log_files_service_impl.h
src/backend/src/plugins/mission/mission_service_impl.h
src/backend/src/plugins/mission_raw/mission_raw_service_impl.h
src/backend/src/plugins/shell/shell_service_impl.h
src/backend/src/plugins/telemetry/telemetry_service_impl.h
src/backend/test/camera_service_impl_test.cpp
templates/mavsdk_server/stream.j2

This should fix a race condition that can happen for streams.
It seems to me what happened was that:
1. The promise is set.
2. The wait at the end of the function returns and the function goes out of scope.
3. Therefore the lock is now destructed.
4. And finally now the lock_guard goes out of scope, again trying to unlock the lock.
I think this only happened intermittently and sometimes in valgrind.
Fixes #1091.

backend: fix race condition for unlock

---

src/plugins/telemetry/telemetry_impl.cpp

When using the MAVSDK examples with the SIH, the system never gets ready with `health_all_ok`, because the accelerometer, gyro and compass are seen as uncalibrated. 
I'm refering to [1100_rc_quad_x_sih.hil](https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d/airframes/1100_rc_quad_x_sih.hil#L17)

hitl can be 1, or 2 when using the SIH

---

src/backend/src/grpc_server.cpp

Otherwise it hangs when `stopBackend()` is called.

Stop all plugins when stopping server

---

src/core/cli_arg.cpp
src/core/cli_arg.h
src/core/cli_arg_test.cpp
src/core/mavsdk.cpp
src/core/mavsdk.h
src/core/mavsdk_impl.cpp
src/core/mavsdk_impl.h
src/core/serial_connection.cpp
src/core/serial_connection.h

Tested on Linux, not entirely sure about the Windows part.
Can be used as `serial_flowcontrol://<device>`

serial: add support for flow control

---

src/backend/src/backend.cpp
src/backend/src/backend_api.cpp
src/backend/src/backend_api.h
src/backend/src/mavsdk_server.cpp

This improves `libmavsdk_server.so`'s API by not blocking until a drone is discovered, and by not relying on a callback and context to return the status. Now the lifecycle looks like this (thanks to previous PRs as well, but this is finishing the work):
1. `runBackend(string system_address = udp://:14540, mavsdkServerPort = 0)`: Starts `mavsdk_server` and return (don't block until a drone is discovered).
2. `getPort()`: get the port on which the gRPC server was started.
3. `attach()`: attach to the process, effectively blocking until `mavsdk_server` is stopped.
4. `stopBackend()`: cancel all subscriptions and stop `mavsdk_server`.
The behavior of `mavsdk_server`, the binary we embed e.g. in MAVSDK-Python, should not change at all.
Those changes are useful for Android and iOS, where the …

Improve libmavsdk_server API

---

src/backend/src/backend_api.cpp
src/backend/src/backend_api.h
src/backend/src/mavsdk_server.cpp

Hoping that this interface will now be stable, because that's breaking iOS and Android :see_no_evil:.

Add prefix to C API, because there is no namespacing

---

.github/workflows/main.yml

Though iOS shows it as an archive, a `*.framework` is actually a folder. I think we should upload the zip instead. We'll see with the next release.

Release mavsdk_server_ios.zip

---

tools/generate_from_protos.sh

`protoc-gen-dcsdk` is now called `protoc-gen-mavsdk`, and available on pypi (`pip install protoc-gen-mavsdk`).

Move from protoc-gen-dcsdk to protoc-gen-mavsdk

---

src/plugins/telemetry/telemetry_impl.cpp

For the case where the altitude is known but the global position is not, the message is sent with lat = 0 and lon = 0.
Still depends on the decision in https://github.com/PX4/Firmware/pull/15308.

telemetry: handle lat = 0 lon = 0 correctly

---

.github/workflows/main.yml
docker/Dockerfile-Fedora-32
docker/Dockerfile-Ubuntu-18.04
docker/Dockerfile-Ubuntu-20.04
docker/Dockerfile-Ubuntu-20.04-PX4-SITL-v1.11
docker/build_and_push_docker_images.sh

This should fix the coveralls error that we have been seeing:
```
Run coverallsapp/github-action@master
with:
github-token: ***
path-to-lcov: ./lcov.info
coveralls-endpoint: https://coveralls.io
Using lcov file: ./lcov.info
[error] "2020-07-16T13:40:56.682Z"  'error from getOptions'
fatal: Not a valid object name 3ce4b7b924ef507acc7570dce933938da28d9be9
```
See: https://github.com/coverallsapp/github-action/issues/55

workflows: use checkout action v2

---

src/integration_tests/offboard_attitude.cpp

This test is implemented in a stupid way, so if it misses some telemetry updates during a (fast) flip, it will continue forever and make CI time out.
This change disables it because in CI only "SitlTest.*" are run.

integration_tests: disable flip test for now

---

src/plugins/telemetry/telemetry_impl.cpp

Reverts mavlink/MAVSDK#1144
This is not following the MAVLink spec and was merged too quickly. The MAVLink spec will not be changed to include incorrect discontinuities, ever.

Revert "telemetry: handle lat = 0 lon = 0 correctly"

---

docker/Dockerfile-Ubuntu-20.04-PX4-SITL-v1.11
src/integration_tests/mavlink_passthrough.cpp

This is a workaround to prevent CI from being stuck for hours. Instead this should fail immediately if gzserver is not running.
To include https://github.com/PX4/Firmware/pull/15399.

docker: use PX4 master for now

---

src/core/system.cpp
src/core/system.h
src/core/system_impl.cpp
src/core/system_impl.h
src/core/timesync.cpp
src/core/timesync.h

It's not completely clear to me when timesync should be enabled: it seems like it is a broadcast, so I'm not sure if all the components should send it or only the autopilot.
I disabled it by default, so those who use it (e.g. @irsdkv) should enable it with `system.enable_timesync()`.

Disable timesync by default

---

src/plugins/mission/mission_impl.cpp
src/plugins/mission/mission_impl.h
src/plugins/mission/mission_import_qgc_test.cpp
src/plugins/mission/qgroundcontrol_sample_with_survey.plan

Currently the import_qgroundcontrol_mission function can only import simple items (waypoints).
QGC also supports surveys, corridor scans and structure scans.
This pull should fix the first two and allow importing surveys and corridor scans.
See https://github.com/mavlink/MAVSDK/issues/1116
It's not tested as I have problems connecting the server with my python-mavsdk scripts. (Timeout issues).
But it compiles at least.

Added QGC complex mission item importing

---

src/core/cli_arg.cpp

on windows, for serial port > 9, "\\\\.\\" is needed before "COM"
These characters are also compatible with port <= 9
more details here: https://stackoverflow.com/questions/27909666/createfile-serial-communication-issue

Fix serial connection on windows

---

src/core/mavlink_parameters.cpp

Only required change was to set `trimmed` to 0 in `mavlink_parameters.cpp`.

Update MAVLink lib

---

src/core/mavsdk.cpp
src/core/mavsdk.h
src/core/mavsdk_impl.cpp

This regards issue #1158.
I think there are maybe two things here, closely related.
One is that the user ultimately doesnt have full control over the Mavsdk::Configuration object. This object basically exists to contain three parameters: system_id, component_id, and usage_type .. and, as far as I can tell, to help suggest good settings for them. Eg if the user provides a usage_type it'll set system_id and component_id automatically based on best guesses, and vice versa. The problem is that the user can't independently set them to arbitrary values, and I think this should be an option, for users with custom situations/requirements (as I seem to have).
The second issue is that even if a user is able to construct the right Configuration object, as it is you can only use it to set a …

Update Configuration for indep. control of sysid, compid, usage_type.

---

examples/battery/battery.cpp

Fixes examples, which were broken by an extension in the recent MAVLink update.
Resolves #1178.

Fix examples following mavlink update

---

src/core/udp_connection.cpp
src/core/udp_connection.h

Until this PR, a UDP remote is identified by an `<ip, port, sysid>`. This means that if two systems exist on the same `UDPConnection` (which typically happens when you have an onboard component connecting to both the FCU and a ground station), two remotes will be created. As a consequence, broadcast messages (such as `HEARTBEAT` or `TIMESYNC`) will be sent twice on that `<ip, port>`, because of the different `sysid`s. This should not happen.
This PR removes the `sysid` from the remotes, so that they are now identified with `<ip, port>`. I believe that the only consequence of that (apart from not sending duplicated messages) is that directed messages will be sent to all remotes instead of being filtered by `target_system_id`. I believe this is fine, because that's anyway the case for all …

Remove sysid from UDP remotes, which induced duplicated messages

---

src/core/mavsdk.cpp
src/core/mavsdk.h
src/plugins/log_files/log_files_impl.cpp

I have always an error at the end of downloading a log file :
I use a mavsdk_server compiled on develop branch on Windows.
After digging a bit, I found that if log part size in not a multiple of MAVLINK_MSG_LOG_DATA_FIELD_DATA_LEN 
(it seems that there is no reason to be of a particular size),
chunks_received size must be "part_size / MAVLINK_MSG_LOG_DATA_FIELD_DATA_LEN +1"

log_files: fix chunks_received size in download_log_file

---

.github/workflows/main.yml

I think it's mostly confusing if that's not available, so I suggest to add it by default.

workflows: enable Passthrough plugin for deb/rpm packages

---

src/core/udp_connection.cpp

Whoops, my bad. `send_message` should send the message even if target_system_id is not 0
I don't get how this even passed the CI :thinking:.

Fix regression in UDP `send_message`

---

src/plugins/mission/mission_impl.cpp

I have seen a segfault happen in current_mission_item() and this is the only thing that potentially could have caused it, I think.

mission: fix potential segfault

---

src/plugins/telemetry/telemetry_impl.cpp
src/plugins/telemetry/telemetry_impl.h

Early on I forgot to protect the callbacks from access by different threads. This could lead to segfaults when a callback is subscribed or unsubscribed while being executed.

telemetry: protect callbacks with mutex

---

src/core/system.cpp
src/core/system.h

This helps to distinguish various systems.

system: add getter for MAVLink system ID

---

docker/Dockerfile-Ubuntu-20.04-PX4-SITL-v1.11

This hopefully fixes the integration tests.
Uses https://github.com/PX4/Firmware/pull/15808.

integration_tests: fix takeoff and hover test with PX4 v1.11.0

---

.github/workflows/main.yml
examples/CMakeLists.txt
examples/battery/CMakeLists.txt
examples/calibrate/CMakeLists.txt
examples/fly_mission/CMakeLists.txt
examples/fly_multiple_drones/CMakeLists.txt
examples/fly_qgc_mission/CMakeLists.txt
examples/follow_me/CMakeLists.txt
examples/ftp_client/CMakeLists.txt
examples/ftp_server/CMakeLists.txt
examples/geofence_inclusion/CMakeLists.txt
examples/multiple_drones/CMakeLists.txt
examples/offboard_velocity/CMakeLists.txt
examples/takeoff_land/CMakeLists.txt
examples/transition_vtol_fixed_wing/CMakeLists.txt
examples/tune/CMakeLists.txt
src/cmake/compiler_flags.cmake

I think it's a better idea to only use -Werror in CI because:
- This way the build is more robust when built for unknown environments with unknown compilers and compiler versions.
- Many developers get confused by warnings and are blocked assuming they are actual errors.
Fixes #611.

cmake: remove -Werror

---

src/backend/src/generated/param/param.grpc.pb.cc
src/backend/src/generated/param/param.grpc.pb.h
src/backend/src/generated/param/param.pb.cc
src/backend/src/generated/param/param.pb.h
src/backend/src/plugins/param/param_service_impl.h
src/core/mavlink_parameters.cpp
src/core/mavlink_parameters.h
src/core/system_impl.cpp
src/core/system_impl.h
src/integration_tests/param.cpp
src/plugins/param/include/plugins/param/param.h
src/plugins/param/param.cpp
src/plugins/param/param_impl.cpp
src/plugins/param/param_impl.h

This PRs aim to introduce a GetAllParams function, as already started in [MAVSDK-Proto PR#175](https://github.com/mavlink/MAVSDK-Proto/pull/175). 
The only testing I have done so far is the integration test I have added. Therefore I keep it a draft for now.

Add GetAllParams function

---

src/cmake/compiler_flags.cmake
src/core/CMakeLists.txt
src/core/mavlink_statustext_handler.cpp
src/core/mavlink_statustext_handler.h
src/core/mavlink_statustext_handler_test.cpp
src/core/system_impl.cpp
src/core/system_impl.h
src/plugins/calibration/calibration_impl.cpp

This adds proper support for multi chunk statustext messages, and finally fixes the calibration as raised in https://github.com/mavlink/MAVSDK-Python/issues/257.

Support statustext with multiple chunks, fix calibration

---

src/plugins/mavlink_passthrough/include/plugins/mavlink_passthrough/mavlink_passthrough.h
src/plugins/mavlink_passthrough/mavlink_passthrough.cpp
src/plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
src/plugins/mavlink_passthrough/mavlink_passthrough_impl.h
src/plugins/telemetry/telemetry_impl.cpp

This makes it possible to re-use the command retransmission in the passthrough plugin.
In the future we could also consider adding a plugin to send commands.

MavlinkPassthrough: add API to send commands

---

examples/battery/battery.cpp

This is due to the mavlink extension change.

examples: fix battery examples

---

src/backend/tools/package_backend_framework.bash

Fat binaries are now replaced by xcframeworks, which seem like a better way to do it (it actually looks like the way Android handles multiple architectures).
The main point here is that we are moving mavsdk-swift to using SwiftPM instead of Carthage, and we need an xcframework instead of a fat binary there.
The good thing is that it should not affect the release process, as the output is the same: `mavsdk_server_ios.zip`.

iOS: build xcframework instead of fat binary

---

examples/gimbal_device_tester/gimbal_device_tester.cpp

This adds more gimbal device tests:
- pitch rate only
- yaw rate only
- pitch rate and angle

gimbal_device_tester: tests for angular rate

---

src/core/mavsdk_impl.cpp

Otherwise code like this never triggers if the system is detected before the callback is set:
```python
print("Waiting for drone to connect...")
async for state in drone.core.connection_state():
if state.is_connected:
print(f"Drone discovered")
break
```

Immediately call new_system_callback if a system is already present

---

src/backend/src/generated/mission/mission.pb.cc
src/backend/src/generated/mission/mission.pb.h
src/plugins/mission/mission.cpp
src/plugins/mission/mission_impl.cpp
src/plugins/mission/mission_impl.h
src/plugins/telemetry/telemetry_impl.cpp
src/plugins/telemetry/telemetry_impl.h

This enables:
- attitude feedback for the gimbal v2 protocol
- mission items using gimbal v2 protocol

Add gimbal v2 status and mission items

---

src/plugins/mission/mission_impl.cpp

Fix the API problem introduced by https://github.com/mavlink/MAVSDK/pull/1233 in https://github.com/mavlink/MAVSDK/pull/1233/files#diff-b667ca284e1b075f788d382e50bd878119c4cbd2b239d91c3e6d4189211bc1a8R53.

plugins: mission_impl: update MAVLinkCommands to MavlinkCommandSender to fix build

---

src/plugins/camera/camera_definition.cpp
src/plugins/camera/camera_impl.cpp
src/plugins/camera/camera_impl.h

* Remove hack that seems obsolete and creates unwanted warnings
* First try to download the camera definition file, then fallback to stored files
* Only load camera definition once (it was doing it repeatedly before)

Fix camera definition loading

---

third_party/curl/CMakeLists.txt
third_party/curl/curl.patch

If trying to use CMAKE_USE_OPENSSL in curl, the build fails with this error
```
[100%] Linking C executable curl
/work/install/lib/libcrypto.a(getentropy_linux.c.o): In function `getentropy_fallback':
/work/build/linux-armv6/third_party/libressl/libressl/src/libressl/crypto/compat/getentropy_linux.c:357: undefined reference to `clock_gettime'
/work/build/linux-armv6/third_party/libressl/libressl/src/libressl/crypto/compat/getentropy_linux.c:427: undefined reference to `clock_gettime'
collect2: error: ld returned 1 exit status
```
Added patch file for curl when using **CMAKE_USE_OPENSSL**, this forces linking against rt when building curl.
This now allows HTTPS URLs with curl -- tested on a raspberry pi successfully.

curl: patch file for libressl librt linking

---

src/core/mavsdk.cpp
src/core/mavsdk.h
src/core/mavsdk_impl.cpp
src/core/mavsdk_impl.h
src/core/system_impl.cpp
src/core/system_impl.h

It actually did not make sense to send heartbeats in the System class because it's the Mavsdk MAVLink node that sends them as broadcast and not per vehicle.
The change was required in order to enable sending heartbeats without first discovering a system. That's needed if MAVSDK is used on a companion or as an autopilot instead of as a ground station.
A few specifics for the change:
- Move call_every_handler from SystemImpl to MavsdkImpl.
- Add config option to always send heartbeats, and not just when a vehicle has been discovered.
- Remove duplicate system_id/component_id vars in MavsdkImpl and use vars in configuration instead.

core: move sending heartbeats to Mavsdk class

---

tools/start_px4_sitl.sh

Instead of having an env variable for PX4 v1.11 and later, it makes more sense having to set it for older versions and assume v1.11 and later by default.
FYI @TSC21

tools: invert version logic, assume v1.11/later

---

examples/gimbal_device_tester/gimbal_device_tester.cpp

This adds checks for sysid/compid as well as the heartbeat.type.

gimbal_device_tester: additional MAVLink checks

---

src/core/mavlink_commands.cpp
src/core/mavlink_parameters.cpp
src/plugins/camera/camera_impl.cpp

* If camera definition defines `CAM_MODE`, save it with the right type when coming from `CAMERA_SETTINGS`
* Pass shared_ptr<promise> by value instead of reference, so that it behaves like one would expect
* Send correct result in the `InProgress` callback, so that it can properly be ignored (otherwise the promise is resolved twice when it happens)

Fix cam mode warnings

---

src/plugins/telemetry/telemetry_impl.cpp

**Problem encountered:**
Segfault when subscribing to actuator_output_status message.
Its impossible to access elements in a vector of size 0 with [].
**Fix:**
We use .push_back() to build the vector instead of [].
**Test:**
With px4_fmu-v4_default.

Fix segfault in TelemetryImpl::process_actuator_output_status

---

examples/fly_multiple_drones/fly_multiple_drones.cpp
examples/follow_me/follow_me.cpp
examples/multiple_drones/multiple_drones.cpp
examples/takeoff_land/takeoff_and_land.cpp

In _examples/fly_multiple_drones/fly_multiple_drones.cpp_ and _examples/multiple_drones/multiple_drones.cpp_
`if (systems.size() < num_systems_discovered)` should be if `(systems.size() > num_systems_discovered)` otherwise 
``if (num_systems_discovered != total_ports_used)`` is always evaluated true and code aborts. 
```
for (auto system : mavsdk.systems()) {
std::thread t(&takeoff_and_land, std::ref(system));
threads.push_back(std::move(t));
sleep_for(seconds(1));
}
```
If there is no time interval between thread creation it seems that the first vehicle rejects the initial command sent to it and the thread aborts resulting in only one vehicle executing the example.
In _examples/takeoff_land/takeoff_and_land.cpp_ access vehicle after discovering it.
In _examples/follow_me/follow_me.cpp_ …

fix examples to work with 0.34.0

---

src/plugins/manual_control/manual_control_impl.cpp
src/plugins/manual_control/manual_control_impl.h

For #1173
Essentially just implements the same thing that offboard does with `Mode::NotActive` for this by adding` enum class Input { NotSet, Set } _input = Input::NotSet`. 
One thing that I am not sure about is that offboard has a `stop_sending_setpoints()` method to reset the `_mode` to `Mode::NotActive` after it has been set by some other method. I dont know if this is also needed for manual control. If it is need I will need some insights to implement it.
Tested this by calling the `start_position_control()` without setting any setpoints first with `set_manual_control_input()` with the following result 
```
[01:45:25|Info ] MAVSDK version: v0.34.0-6-g5c2031d9 (mavsdk_impl.cpp:20)
Waiting to discover system...
[01:45:25|Info ] New system on: 127.0.0.1:14580 (with sysid: 1) …
```

No setpoint manual control

---

src/core/call_every_handler.cpp
src/core/call_every_handler.h
src/core/call_every_handler_test.cpp

Instead of waiting for one interval we now call a new call every callback immediately in the first round. This is achieved by setting the initial time to now and subtract the interval.
This should fix the problem where the takeoff and hover test fails due to the vehicle going into failsafe. This happened because the vehicle had not received any heartbeats yet at the time of the takeoff.

core: immediately call new entry

---

src/backend/src/generated/manual_control/manual_control.pb.cc
src/backend/src/generated/manual_control/manual_control.pb.h
src/backend/src/generated/telemetry/telemetry.grpc.pb.cc
src/backend/src/generated/telemetry/telemetry.grpc.pb.h
src/backend/src/generated/telemetry/telemetry.pb.cc
src/backend/src/generated/telemetry/telemetry.pb.h
src/backend/src/plugins/manual_control/manual_control_service_impl.h
src/backend/src/plugins/telemetry/telemetry_service_impl.h
src/plugins/manual_control/include/plugins/manual_control/manual_control.h
src/plugins/manual_control/manual_control.cpp
src/plugins/telemetry/include/plugins/telemetry/telemetry.h
src/plugins/telemetry/mocks/telemetry_mock.h
src/plugins/telemetry/telemetry.cpp
src/plugins/telemetry/telemetry_impl.cpp
src/plugins/telemetry/telemetry_impl.h

This adds support for GPS_GLOBAL_ORIGIN through MAV_CMD_REQUEST_MESSAGE.
Note: depends on https://github.com/mavlink/MAVSDK-Proto/pull/187

Add support for getting the gps global origin

---

.github/workflows/main.yml
docker/Dockerfile-Fedora-33
docker/Dockerfile-Ubuntu-18.04-PX4-SITL-v1.10
docker/Dockerfile-Ubuntu-20.04-PX4-SITL-v1.11
docker/build_and_push_docker_images.sh

See commits. Docker images are already regenerated and pushed to dockerhub.

Update docker: PX4 releases and bump Fedora version

---

src/core/system_impl.cpp

We should set the connected state correct before calling the callback.

core: fix potential race on discovery

---

src/plugins/manual_control/manual_control_impl.cpp
src/plugins/manual_control/manual_control_impl.h

A result/error of unknown is not a good user feedback. Instead we need
to communicate the actual reason.
Closes #1173.

manual_control: use proper result if input not set

---

src/core/mavlink_statustext_handler_test.cpp
third_party/curl/CMakeLists.txt
third_party/curl/curl.patch

Because we don't necessarily have patch on Win.

third_party: use git apply, not patch

---

.github/workflows/main.yml

This splits the iOS jobs in order to run them in parallel. That requires a third job, that gets the frameworks built by each, package them into an xcframework, and deploys it (if it is a release).
If that works, it will divide the CI time by a factor of 2.

CI: Run iOS jobs in parallel

---

third_party/cmake/build_target.cmake

Does that make any sense? It seems to work.

Fix Windows build when MAVSDK with SUPERBUILD is external project

---

.github/workflows/main.yml
src/backend/src/CMakeLists.txt
src/backend/tools/package_backend_framework.bash

For Python, we need `mavsdk_server` as a macOS (almost-)static binary (the equivalent of manylinux).
For Swift, the idea would be to add macOS into the xcframework, such that it would "just work" with SwiftPM. That is what this PR is about.
It needs some testing with MAVSDK-Swift, and then the artifact would be rename from `mavsdk_server_ios.zip` to maybe `mavsdk_server.xcframework.zip`, or something like that.

Add option to build macos framework

---

templates/plugin_h/call.j2
templates/plugin_h/request.j2

A `Result` needs to be treated differently than other types in the templates. This is fixing the templates when `Result` is used as a parameter to a function.
@TSC21: FYI

Handle Result as parameter

---

src/core/system_impl.h

This is an attempt to prevent the race between the _connected flag and calling the on_change subscription.

core: attempt to fix connection race

---

src/integration_tests/follow_me.cpp
src/mavsdk_server/src/generated/action/action.grpc.pb.cc
src/mavsdk_server/src/generated/calibration/calibration.grpc.pb.cc
src/mavsdk_server/src/generated/camera/camera.grpc.pb.cc
src/mavsdk_server/src/generated/core/core.grpc.pb.cc
src/mavsdk_server/src/generated/failure/failure.grpc.pb.cc
src/mavsdk_server/src/generated/follow_me/follow_me.grpc.pb.cc
src/mavsdk_server/src/generated/ftp/ftp.grpc.pb.cc
src/mavsdk_server/src/generated/geofence/geofence.grpc.pb.cc
src/mavsdk_server/src/generated/gimbal/gimbal.grpc.pb.cc
src/mavsdk_server/src/generated/info/info.grpc.pb.cc
src/mavsdk_server/src/generated/log_files/log_files.grpc.pb.cc
src/mavsdk_server/src/generated/manual_control/manual_control.grpc.pb.cc
src/mavsdk_server/src/generated/mission/mission.grpc.pb.cc
src/mavsdk_server/src/generated/mission_raw/mission_raw.grpc.pb.cc
src/mavsdk_server/src/generated/mocap/mocap.grpc.pb.cc
src/mavsdk_server/src/generated/offboard/offboard.grpc.pb.cc
src/mavsdk_server/src/generated/param/param.grpc.pb.cc
src/mavsdk_server/src/generated/shell/shell.grpc.pb.cc
src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.cc
src/mavsdk_server/src/generated/tune/tune.grpc.pb.cc
third_party/cares/CMakeLists.txt
third_party/grpc/CMakeLists.txt
tools/ios.toolchain.cmake

Using latest version from https://github.com/leetal/ios-cmake

Fix iOS simulator build following update to Xcode 12

---

.github/workflows/main.yml

Trying to use the [cache action](https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows). This should do the following:
1. Try to find a cached directory matching key `${{ github.job }}-${{ hashFiles("./third_party/**") }}`, where `github.job` is the unique name of the job (e.g. 'iOS'), and `hashFiles("./third_party/**")` computes one hash representing all the files in `third_party/`, which are CMakeLists and patches for our dependencies. Therefore, this should be a unique key for the job and for that set of dependencies.
2. If there is a cache hit, it means that `./build/ios/third_party/install` has been saved for that job, which would be e.g. all the dependencies for the 'iOS' job. In that case, we want to disable the superbuild and use …

Add cache to github workflows (for dependencies)

---

src/core/mavsdk_impl.cpp

Hopefully this will fix the issue where CI fails because the on_change callback is called, however, the system is not actually connected yet.
I believe the issue we saw was a race between the on_change callback being registered and the moment when a system is added to the list but has not been set to connected yet.

core: fix CI connection race issues
