mavlink/MAVSDK

- CMakeLists.txt
- README.md
- core/curl_include.h
- core/curl_wrapper.cpp
- core/curl_wrapper_types.h
- integration_tests/mission_change_speed.cpp
- integration_tests/mission_survey.cpp
- integration_tests/waypoints.cpp
- plugins/mission/mission_impl.cpp
This addresses #6.
More fixes are needed.
> Fix Windows build

- .travis.yml
- README.md
This should enable the default build using tavis-ci.
> Add travis CI build

- docs/build.md
We've 2 examples in folder example.
1. takeoff_land
2. fly_mission
TODO: Need to update the links to them once the [corresponding PR](https://github.com/dronecore/DroneCore/pull/39) is merged.
> doc update reflecting folder name change

- CMakeLists.txt
- core/dronecore.cpp
- core/serial_connection.cpp
- core/serial_connection.h
- core/tcp_connection.cpp
- core/tcp_connection.h
- example/takeoff_land/CMakeLists.txt
- include/dronecore.h
> Tcp and Serial connection Support, Fix Install Errors on Windows [2]

- generate_markdown_from_doxygen_xml.py
- plugins/action/action.h
- plugins/info/info.h
@julianoes As discussed, this now makes it clear that the action commands send a message and complete with result of acknowledgement from vehicle - ie the actual "action" does not complete when a function returns.
> Update action docs to make clear how action commands work

- CMakeLists.txt
- Makefile
- core/global_include.h
- core/global_include_test.cpp
- core/mavlink_commands.cpp
- integration_tests/telemetry_async.cpp
- plugins/mission/mission_impl.cpp
This brings some small fixes that have accumulated over the last few weeks.
Fixes #43.
> Upstreaming various small internal fixes

- README.md
- appveyor.yml
We should verify the Windows build in CI.
Closes #44.
> Add appveyor CI

- CMakeLists.txt
- core/serial_connection.cpp
- core/tcp_connection.cpp
- core/tcp_connection.h
With this flag, the clang build lead to many linking errors on a Linux
such as Fedora.
> various clang fixes

- .gitignore
- integration_tests/telemetry_modes.cpp
Changes other than printing flight mode string are due to `make fix_style`.
> integration_test: telemetry_modes: printing human readable flight modes

- core/device_impl.cpp
This somehow got out of sync in the recent merges.
> core: fixed wrong variable

- core/mavlink_parameters.cpp
- core/mavlink_parameters.h
- core/udp_connection.cpp
A few printfs and a param fix.
> Various small fixes

- integration_tests/simple_hover.cpp
For the high takeoff the landing time was on the low end.
> integration_tests: fix landing time

- plugins/info/info.h
> Fix is_complete to mention Product

- grpc/server/dronecore_server.cpp.in
Fixed the segementation fault issue while running droneserver, it was due to
conf file path issue.
> Fix to segmentation fault issue

- grpc/python_client/CMakeLists.txt
- grpc/python_client/async_client.py
- grpc/python_client/fly_mission.py
- grpc/python_client/sync_client.py
- grpc/server/CMakeLists.txt
- grpc/server/dronecore_server.cpp.in
These are follow up fixes after #143 and 173.
Currently, the Python client does not work for me:
```
./grpc/python_client/sync_client.py
Traceback (most recent call last):
File "./grpc/python_client/sync_client.py", line 9, in <module>
import action_pb2_grpc
ImportError: No module named action_pb2_grpc
```
> gRPC follow up fixes

- plugins/telemetry/telemetry.h
> telemetry: fix missing param description

- generate_markdown_from_doxygen_xml.py
- plugins/follow_me/follow_me.h
This adds a few missing strings to follow_me.h and improves the rendering handling of the docs generator script.
> Fix up issues with doc strings and doc string generator tool

- core/device_impl.cpp
This adds some functionality to debug incoming and outgoing messages. The printfs are not compiled in by default though and need to be enabled with a define.
> Message debugging

- .gitignore
- appveyor.yml
- integration_tests/follow_me.cpp
- plugins/follow_me/follow_me.cpp
- plugins/follow_me/follow_me.h
- plugins/follow_me/follow_me_impl.cpp
- plugins/follow_me/follow_me_impl.h
Improved Follow Me API signature as per [this](https://github.com/dronecore/DroneCore/issues/191) issue.
> Improve Follow Me plug-in

- core/device_impl.cpp
> Keep previous uuid when Device disconnects

- .gitmodules
- CMakeLists.txt
- Makefile
- appveyor.yml
- cmake/zlib.cmake
- core/CMakeLists.txt
- external_example/integration_tests/CMakeLists.txt
- external_example/integration_tests/hello_world.cpp
- external_example/plugins/CMakeLists.txt
- external_example/plugins/example/CMakeLists.txt
- external_example/plugins/example/example.cpp
- external_example/plugins/example/example.h
- external_example/plugins/example/example_impl.cpp
- external_example/plugins/example/example_impl.h
- integration_tests/CMakeLists.txt
- plugins/CMakeLists.txt
- plugins/action/CMakeLists.txt
- plugins/follow_me/CMakeLists.txt
- plugins/gimbal/CMakeLists.txt
- plugins/info/CMakeLists.txt
- plugins/logging/CMakeLists.txt
- plugins/mission/CMakeLists.txt
- plugins/offboard/CMakeLists.txt
- plugins/telemetry/CMakeLists.txt
After the last refactor, external plugins were not included any longer.
However, it is as easy as including the folder where there should be the
next CMakeLists.txt to use.
> Enable external plugins again

- core/CMakeLists.txt
This is another hack like #252 but for iOS.
> cmake: add tinyxml2 install hack for Mac

- Jenkinsfile
http://ci.px4.io:8080/blue/organizations/jenkins/DroneCore/detail/pr-jenkins/1/pipeline
> [WIP] initial Jenkinsfile using docker

- docker/Dockerfile-Fedora-27
- docker/Dockerfile-Ubuntu-16.04
Thanks @hamishwillee for trying. Both docker builds were broken in the meantime.
> Fix docker builds

- core/CMakeLists.txt
- plugins/follow_me/CMakeLists.txt
- plugins/gimbal/CMakeLists.txt
- plugins/info/CMakeLists.txt
- plugins/logging/CMakeLists.txt
- plugins/offboard/CMakeLists.txt
I'm just trying to get the iOS build (without gRPC) back and probably need these changes.
> Fix iOS (non gRPC) build

- fix_style.sh
I am on astyle 3.1 on Arch Linux.
> style: add support for astyle 3.1

- example/fly_qgc_mission/fly_qgc_mission.cpp
Update path of sample plan: `plugins/mission/qgroundcontrol_sample.plan`.
Fixes #272
> Update file path of QGC sample plan in the example

- appveyor.yml
- example/follow_me/CMakeLists.txt
- example/follow_me/fake_location_provider.cpp
Adds examples follow_me and fly_qgc_mission to `appveyor.yml`.
> Appveyor: Add examples follow_me and fly_qgc_mission

- core/dronecore.cpp
- core/dronecore.h
- example/takeoff_land/takeoff_and_land.cpp
Supports TCP, UDP, Serial connection interfaces
Updates takeoff_land example
Issue: #244
> Add support for Connection URL arguments to Dronecore Applications

- generate_markdown_from_doxygen_xml.py
Makes default values link better. 
For example, in previous version over overview prototype only `add_any_connection` would link - there would be no link to the definition of default value `DEFAULT_UDP_CONNECTION_URL`
```
add_any_connection (const std::string & connection_url=DEFAULT_UDP_CONNECTION_URL)
````
Furthermore, the definition for DEFAULT_UDP_CONNECTION_URL did not include the default value, making it pretty useless. This fixes a bug that was stopping the default value being displayed.
> Fix initializers for attribute prototypes

- core/connection_result.h
> Add missing docs for ConnectionResult and connection_result_str

- backend/src/cmake/compile_proto.cmake
- backend/src/plugins/telemetry/telemetry_service_impl.h
- backend/test/telemetry_service_impl_test.cpp
- plugins/telemetry/mocks/telemetry_mock.h
- plugins/telemetry/telemetry.cpp
- plugins/telemetry/telemetry.h
Adding the remaining features to telemetry.
> Finish telemetry features

- appveyor.yml
I had updated the submodule source, but forgot to update the commit -_-.
> mission: use latest commit of json11's fork

- backend/src/plugins/mission/mission_service_impl.h
- backend/test/mission_service_impl_test.cpp
- plugins/mission/mocks/mission_mock.h
> backend: add mission finished

- core/mavlink_commands.cpp
- integration_tests/camera_status.cpp
- plugins/camera/camera.h
- plugins/camera/camera_definition.cpp
This includes a couple of fixes that I found while running the camera tests against the E90.
> Various fixes found doing camera tests

- core/CMakeLists.txt
- core/mavlink_system.cpp
- core/mavlink_system.h
- core/thread_pool.cpp
- core/thread_pool.h
- core/thread_pool_test.cpp
This adds a thread pool to use for user callbacks and replaces the `std::async` used before.
> Add thread pool

- backend/src/plugins/camera/camera_service_impl.h
- backend/test/camera_service_impl_test.cpp
- plugins/camera/mocks/camera_mock.h
Adding the following features:
* StartPhotoInterval
* StopPhotoInterval
* StartVideo
* StopVideo
* StartVideoStreaming
* StopVideoStreaming
Connects to #334.
> Implement camera backend

- .travis.yml
- Jenkinsfile
- docker/Dockerfile-Fedora-27
- docker/Dockerfile-Fedora-28
- docker/Dockerfile-Ubuntu-16.04
- docker/Dockerfile-Ubuntu-18.04
As brought up by @hamishwillee we need to change the docker working directory. This required to rebuild the docker images and therefore also update the tags in the Jenkinsfile.
> Fix docker working directory

- backend/src/plugins/camera/camera_service_impl.h
- backend/test/camera_service_impl_test.cpp
- backend/test/mission_service_impl_test.cpp
- integration_tests/camera_test_helpers.cpp
- plugins/camera/camera.cpp
- plugins/camera/camera.h
- plugins/camera/mocks/camera_mock.h
> 334 finish camera backend

- core/system_impl.cpp
> core: remove unused variable

- core/log.cpp
- core/log.h
- plugins/mission/CMakeLists.txt
A couple of build issues for Android came up.
Presumably we should add the Android build to CI if we don't already do it.
Fixes #452.
> Fix Android build issues

- backend/cmake/MacOSXFrameworkInfo.plist.in
- backend/tools/push_backend_framework_to_s3.bash
Bump version number of `backend.framework` to 0.0.2.
> backend: version backend.framework on s3

- README.md
> README: fix Jenkins badge

- integration_tests/camera_settings.cpp
I got the description tets pretty wrong actually.
> integration_tests: fix the description tests

- backend/cmake/MacOSXFrameworkInfo.plist.in
- backend/src/plugins/camera/camera_service_impl.h
- backend/test/camera_service_impl_test.cpp
- integration_tests/camera_settings.cpp
- plugins/camera/camera.cpp
This should fix the bug reported by @douglaswsilva.
> Fix camera option description in SettingOptions

- backend/tools/push_backend_framework_to_s3.bash
> backend: bump version correctly

- plugins/camera/camera_impl.cpp
- plugins/camera/include/plugins/camera/camera.h
It is convenient to receive the video recording time.
> camera: added video recording time

- backend/src/plugins/mission/mission_service_impl.h
- backend/test/mission_service_impl_test.cpp
> Add waypoint delay

- integration_tests/camera_status.cpp
- plugins/calibration/calibration_impl.cpp
- plugins/camera/camera.cpp
- plugins/camera/camera_impl.cpp
- plugins/camera/camera_impl.h
- plugins/camera/include/plugins/camera/camera.h
This adds the camera media folder, as well as a getter for the camera vendor and model name.
> Add camera media folder name

- integration_tests/CMakeLists.txt
- integration_tests/camera_format.cpp
- plugins/camera/camera.cpp
- plugins/camera/camera_impl.cpp
- plugins/camera/camera_impl.h
- plugins/camera/include/plugins/camera/camera.h
This adds the capability to format an SD card of a camera.
> camera: added command to format storage

- backend/cmake/MacOSXFrameworkInfo.plist.in
- backend/tools/push_backend_framework_to_s3.bash
Adding the SubscribeCameraStatus fix.
> backed: bump to 0.2.2

- core/system_impl.cpp
- core/system_impl.h
This is not needed anymore, time to get rid of it.
> core: remove communication lock

- Jenkinsfile
- docker/Dockerfile-Fedora-27
- docker/Dockerfile-Fedora-28
- docker/Dockerfile-Ubuntu-16.04
- docker/Dockerfile-Ubuntu-18.04
- docker/build_and_push_docker_images.sh
Let's see how long this takes.
> Jenkins: try to build backend as well

- backend/src/plugins/calibration/calibration_service_impl.h
Small issue in the C++ auto-generation.
> backend: fix calibration build on macos

- backend/src/plugins/mission/mission_service_impl.h
> backend: fix crash in mission

- backend/src/plugins/calibration/calibration_service_impl.h
- backend/src/plugins/mission/mission_service_impl.h
- backend/src/plugins/telemetry/telemetry_service_impl.h
- backend/test/mission_service_impl_test.cpp
- backend/test/telemetry_service_impl_test.cpp
Update proto submodule and fix compilation
> proto: update submodule

- backend/src/grpc_server.cpp
- backend/src/grpc_server.h
- backend/src/plugins/calibration/calibration_service_impl.h
This is adding the calibration plugin to the backend.
> calibration: enable plugin and fix backend code

- run-docker.sh
This is a patch suggested by pablojr on
http://discuss.px4.io/t/run-docker-sh-error-bin-su/8651
> run-docker.sh fixes

- CMakeLists.txt
- Jenkinsfile
- docker/Dockerfile-Fedora-28
- docker/Dockerfile-Fedora-29
- docker/Dockerfile-Ubuntu-16.04
- docker/Dockerfile-Ubuntu-18.04
- docker/entrypoint.sh
- run-docker.sh
Here are a few minor things that might help improve build times on Jenkins.
> Jenkins enable CCACHE, post cleanup, and add ninja-build to docker

- backend/src/core/core_service_impl.h
Nothing to add. I'm not super proud of that, but it's trivial so that's okay.
> core: update some hard-coded values in backend

- README.md
I forgot this when removing the Jenkinsfile in #655.
> README: remove Jenkins badge

- .doxygen
- generate_docs.sh
- plugins/mavlink_passthrough/include/plugins/mavlink_passthrough/mavlink_passthrough.h
- plugins/mission_raw/CMakeLists.txt
- plugins/mission_raw/include/plugins/mission_raw/mission_raw.h
- plugins/params_raw/CMakeLists.txt
Addresses @hamishwillee's notes in #657.
> Some doc and install fixes

- CMakeLists.txt
I'm having issues with this CMake thing...
> cmake: fix tag extraction, again

- integration_tests/CMakeLists.txt
- integration_tests/offboard_position.cpp
- plugins/offboard/include/plugins/offboard/offboard.h
- plugins/offboard/offboard.cpp
- plugins/offboard/offboard_impl.cpp
- plugins/offboard/offboard_impl.h
Following up on our little chat about the opportunity to add offboard position control in the Local Cartesian (NED) frame (see: [here](http://discuss.px4.io/t/offboard-frames-question/8181))
> plugin offboard: support for position-ned

- backend/src/plugins/action/action_service_impl.h
- plugins/action/mocks/action_mock.h
- Add reboot action to wrapper.
> Add reboot action.

- plugins/mission/mission_impl.cpp
This fixes a crash that happened when a mission upload was cancelled.
What happened is that the mission result callback ended up being called
twice on upload after a cancellation.
The reason for the two callback calls are, I believe, as follows:
- The autopilot is still in upload mode. Therefore, it will continue to
send mission items continuing where we sent cancel. This means we will
continue happily uploading from there and eventually report SUCCESS.
- However, since the autopilot is still in upload mode, it doesn not
acknowledge our message indicating the count of the mission items.
We receive this nack and report an error.
The fix for now is to abort immediately if we receive a nack.
The proper fix is for the mission plugin as well as the PX4 side to
implement mission cancelling …
> mission: fix mission upload cancel crash

- README.md
I also removed the mention and link to action_result.h as I believe it doesn't exist anymore?
> Update README.md - fix broken links

- core/any_test.cpp
- integration_tests/camera_settings.cpp
- plugins/camera/camera_definition.cpp
- plugins/camera/camera_definition.h
This should fix potential thread safety issues in `CameraDefinition`. It might fix #712.
> Fix camera thread-safety

- integration_tests/CMakeLists.txt
- integration_tests/geofence_inclusion.cpp
- plugins/CMakeLists.txt
- plugins/geofence/CMakeLists.txt
- plugins/geofence/geofence.cpp
- plugins/geofence/geofence.h
- plugins/geofence/geofence_impl.cpp
- plugins/geofence/geofence_impl.h
- plugins/geofence/include/plugins/geofence/geofence.h
This open-sources some Yuneec internal work. It's a first stab and needs some fixing and testing.
> [WIP] Added geofence plugin

- example/fly_mission/fly_mission.cpp
- example/fly_qgc_mission/fly_qgc_mission.cpp
- example/takeoff_land/takeoff_and_land.cpp
- src/plugins/mission/include/plugins/mission/mission.h
- src/plugins/mission_raw/include/plugins/mission_raw/mission_raw.h
- tools/generate_markdown_from_doxygen_xml.py
This was hardcoded for namespace doc file that is built. Now updated to use the new namespace file.
> Fix up generation of namespace docs

- src/backend/tools/package_backend_framework.bash
- src/backend/tools/push_backend_framework_to_s3.bash
Fixing the packaging and deployment to AWS following renaming from `backend` to `mavsdk_server`.
> backend: fix ios deployment scripts

- src/backend/cmake/MacOSXFrameworkInfo.plist.in
- src/backend/src/module.modulemap
> mavsdk_server: fix framework modulemap

- README.md
I could not find a smaller png, so I used the html tag to resize it.
> README: add new MAVSDK logo

- tools/run-docker.sh
This was incorrectly set after the rename.
> tools: choose correct dockerhub repo

- Jenkinsfile
- docker/Dockerfile-Ubuntu-18.04-PX4-SITL
- docker/README.md
- src/integration_tests/action_takeoff_and_kill.cpp
- src/plugins/telemetry/telemetry_impl.cpp
This includes a couple small fixes and a workaround to get CI happy again.
> Fix docker scripts and CI integration tests

- example/multiple_drones/multiple_drones.cpp
I had merged this too early without checking CI properly.
> example: small style fix

- Jenkinsfile
- docker/Dockerfile-Ubuntu-18.04-PX4-SITL
- src/integration_tests/action_hover_sync.cpp
Hopefully this will stabilize the integration tests.
> integration_tests: workaround PX4 takeoff bug

- third_party/grpc/CMakeLists.txt
Our patches should now be upstream, let's see what the CI says.
> update grpc to 1.22.0 (going back to upstream release)

- src/core/CMakeLists.txt
- src/core/mavsdk.cpp
- src/core/mavsdk.h
- src/core/mavsdk_impl.cpp
- src/core/mavsdk_impl.h
- src/core/mavsdk_test.cpp
Because that's common for a library to implement.
> core: added getter for version

- src/integration_tests/telemetry_sync.cpp
- src/plugins/telemetry/include/plugins/telemetry/telemetry.h
- src/plugins/telemetry/telemetry.cpp
Just some things I noticed and wanted to improve while using it.
> Small improvements to telemetry plugin and test

- src/backend/src/CMakeLists.txt
- src/backend/src/grpc_server.cpp
- src/backend/src/grpc_server.h
- src/plugins/geofence/include/plugins/geofence/geofence.h
Note: I had to invert the results in the C++ code, because they were not in the same order as the proto files.
@coderkalyan: FYI
> Enable geofence in mavsdk_server

- src/backend/src/generated/action/action.grpc.pb.cc
- src/backend/src/generated/action/action.grpc.pb.h
- src/backend/src/generated/calibration/calibration.grpc.pb.cc
- src/backend/src/generated/calibration/calibration.grpc.pb.h
- src/backend/src/generated/camera/camera.grpc.pb.cc
- src/backend/src/generated/camera/camera.grpc.pb.h
- src/backend/src/generated/core/core.grpc.pb.cc
- src/backend/src/generated/core/core.grpc.pb.h
- src/backend/src/generated/geofence/geofence.grpc.pb.cc
- src/backend/src/generated/geofence/geofence.grpc.pb.h
- src/backend/src/generated/gimbal/gimbal.grpc.pb.cc
- src/backend/src/generated/gimbal/gimbal.grpc.pb.h
- src/backend/src/generated/gimbal/gimbal.pb.cc
- src/backend/src/generated/gimbal/gimbal.pb.h
- src/backend/src/generated/info/info.grpc.pb.cc
- src/backend/src/generated/info/info.grpc.pb.h
- src/backend/src/generated/mission/mission.grpc.pb.cc
- src/backend/src/generated/mission/mission.grpc.pb.h
- src/backend/src/generated/offboard/offboard.grpc.pb.cc
- src/backend/src/generated/offboard/offboard.grpc.pb.h
- src/backend/src/generated/param/param.grpc.pb.cc
- src/backend/src/generated/param/param.grpc.pb.h
- src/backend/src/generated/telemetry/telemetry.grpc.pb.cc
- src/backend/src/generated/telemetry/telemetry.grpc.pb.h
- third_party/grpc/CMakeLists.txt
- tools/generate_from_protos.sh
It requires to recompile the proto files, and also to checkout with git, because they added a new submodule...
> Update grpc to 1.24.0

- tools/generate_changelog.py
To get the changelog for e.g. `v0.21.0`, run:
```sh
python generate_changelog.py --tag v0.21.0 --token <your_github_token>
```
Note: you need the `gql` python package (for GraphQL).
> Add script to generate changelog

- src/backend/src/plugins/shell/shell_service_impl.h
Fix result allocation. And typo.
I apologize
> Segmentation fault fix

- src/core/system_impl.cpp
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>
> core: Use std::any_of in system_impl

- src/core/serial_connection.h
- src/core/tcp_connection.h
- src/core/udp_connection.h
Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>
> core: Add missing override for tcp, udp and serial connection

- .travis.yml
This can potentially be handy. I don't see a reason why not to add this.
> travis-ci: add arm64 mavsdk_server build

- .travis.yml
- src/backend/src/CMakeLists.txt
If that works (i.e. including testing on an Android device), I will add android-arm and deploy that as an artifact.
> Add android-arm64 to Travis

- src/plugins/shell/include/plugins/shell/shell.h
- src/plugins/shell/shell_impl.cpp
Add line feed due to https://github.com/mavlink/MAVSDK/issues/940
> shell: add automatic line feed

- example/CMakeLists.txt
- example/mavshell/CMakeLists.txt
- example/mavshell/mavshell.cpp
Add example for the shell plugin.
Also, somehow the examples/ CMakeLists was not a root project, so I fixed that.
> Add mavshell example

- src/plugins/mission/mission_impl.cpp
The timeout was not implemented for clearing the mission. This meant that if the autopilot did not ack mission clear we would be stuck in the MISSION_CLEAR activity stay and be busy for the rest.
Reported by @douglaswsilva.
> mission: retry to clear the mission

- .github/workflows/main.yml
- src/backend/src/backend_api.cpp
- src/backend/src/backend_api.h
- src/backend/src/mavsdk_server.cpp
- src/backend/src/plugins/telemetry/telemetry_service_impl.h
- src/core/global_include.cpp
- src/core/system_impl.cpp
- src/core/udp_connection.cpp
- src/plugins/telemetry/telemetry_impl.cpp
Looks like we didn't have a style check anymore.
> Fix style and add to CI again

- src/plugins/telemetry/include/plugins/telemetry/telemetry.h
This fixes broken docs.
@julianoes @JonasVautherin Historically broken docs stopped commits merging. Can we re-enable that? This took a while to identify.
> fix telemetry docs

- .github/workflows/main.yml
In this pull request I want to fix #977. First step is to enable the backend test to see if it reproduces as well. Then, we can hopefully update the gRPC version to fix it.
> Fix gRPC stall

- .github/workflows/main.yml
This got lost when moving from Jenkins to travis.
> workflows: add docs check again

- .github/workflows/main.yml
- docker/Dockerfile-Fedora-31
- docker/Dockerfile-Ubuntu-18.04-PX4-SITL-v1.10
- docker/Dockerfile-Ubuntu-18.04-PX4-SITL-v1.9
- docker/build_and_push_docker_images.sh
This adds testing against the latest PX4 v1.10 as well as a docker image for Fedora 31.
> Update docker images

- src/plugins/telemetry/telemetry_impl.cpp
This fixes undefined behaviour discovered by the undefined behaviour sanitizer (using GCC).
The reported error/warning was:
```
src/third_party/mavlink/include/mavlink/v2.0/protocol.h:278:1:
runtime error:
load of misaligned address 0x61300000004d for type 'const uint64_t', which requires 8 byte alignment
```
This happened when using getters based on the pointer into the mavlink_message_t instead of the decode function otherwise.
The culprit is that packed structs are used everywhere inside the mavlink header which should probably be changed in the future.
For now, I suggest, not to use the getter functions.
> telemetry: fix load of misaligned address

- src/core/serial_connection.cpp
On an intel nuc running ubuntu 18.04 I had issues where my sdk example
(mavlink_ftp_client) was returning 1 in the main but the serial connection
thread was blocked because of the blocking read call.
My setup was an intel nuc connected to the telem2 port of a Pixhawk 4.
Also the "close" of the file descriptor in the stop method was called before
joining the receive thread which could lead to undefined behavior.
> add pollin to serial connection read

- examples/offboard_velocity/offboard_velocity.cpp
This pull request addresses using the takeoff process using landed state instead of sleep.
> Takeoff landed state

- src/backend/src/generated/action/action.grpc.pb.h
- src/plugins/action/include/plugins/action/action.h
Update proto files following a minor change in the documentation (action.proto)
> Update proto files

- src/plugins/mission_raw/include/plugins/mission_raw/mission_raw.h
- src/plugins/mission_raw/mission_raw.cpp
- src/plugins/mission_raw/mission_raw_impl.cpp
- src/plugins/mission_raw/mission_raw_impl.h
I added multiple features for MissionRaw:
start/pause/clear/set_current/mission_finished/subscribe_progress/cancel upload/download
I still need to manage if a RTL command is sent. This is mostly copy/paste from Mission class.
Tests are still required
> MissionRaw: add multiples features

- src/plugins/log_files/include/plugins/log_files/log_files.h
- src/plugins/log_files/log_files.cpp
- src/plugins/log_files/log_files_impl.cpp
- src/plugins/log_files/log_files_impl.h
This now works properly over serial as well as over UDP. For more information, check commit messages.
Tested against Pixracer and SITL jMAVSim.
> Log file download improvements and fixes

- src/backend/src/generated/ftp/ftp.pb.cc
- src/backend/src/generated/ftp/ftp.pb.h
- src/backend/src/generated/offboard/offboard.pb.cc
- src/backend/src/generated/offboard/offboard.pb.h
- src/backend/src/plugins/action/action_service_impl.h
- src/backend/src/plugins/camera/camera_service_impl.h
- src/backend/src/plugins/follow_me/follow_me_service_impl.h
- src/backend/src/plugins/ftp/ftp_service_impl.h
- src/backend/src/plugins/info/info_service_impl.h
- src/backend/src/plugins/log_files/log_files_service_impl.h
- src/backend/src/plugins/mission/mission_service_impl.h
- src/backend/src/plugins/mission_raw/mission_raw_service_impl.h
- src/backend/src/plugins/offboard/offboard_service_impl.h
- src/backend/src/plugins/param/param_service_impl.h
- src/backend/test/offboard_service_impl_test.cpp
- src/integration_tests/ftp.cpp
- src/integration_tests/offboard_position.cpp
- src/integration_tests/offboard_velocity.cpp
- src/plugins/ftp/ftp.cpp
- src/plugins/ftp/ftp_impl.cpp
- src/plugins/ftp/ftp_impl.h
- src/plugins/ftp/include/plugins/ftp/ftp.h
- src/plugins/offboard/include/plugins/offboard/offboard.h
- src/plugins/offboard/mocks/offboard_mock.h
- src/plugins/offboard/offboard.cpp
- src/plugins/offboard/offboard_impl.cpp
- src/plugins/offboard/offboard_impl.h
- templates/mavsdk_server/request.j2
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/147.
> Remove two unneeded results from API

- .github/workflows/main.yml
- examples/battery/battery.cpp
- examples/calibrate/calibrate.cpp
- examples/fly_mission/fly_mission.cpp
- examples/fly_multiple_drones/fly_multiple_drones.cpp
- examples/fly_qgc_mission/fly_qgc_mission.cpp
- examples/follow_me/follow_me.cpp
- examples/ftp_server/ftp_server.cpp
- examples/geofence_inclusion/geofence_inclusion.cpp
- examples/mavshell/mavshell.cpp
- examples/multiple_drones/multiple_drones.cpp
- examples/offboard_velocity/offboard_velocity.cpp
- examples/takeoff_land/takeoff_and_land.cpp
- examples/transition_vtol_fixed_wing/transition_vtol_fixed_wing.cpp
This adds building the examples to CI. Fixes #1027, fixes #677.
> Build examples in CI

- src/integration_tests/action_goto.cpp
hi. This is a test pull request to confirm if this is what i have to do for rest of the files or anything else.
> Rename dc to mavsdk

- .gitignore
- tools/.doxygen
- tools/generate_markdown_from_doxygen_xml.py
It doesn't look like I actually have to change anything for the "new" typedefs to work.
> Minor docs fixes

- tools/generate_changelog.py
> tools: don't crash on empty tags

- .github/workflows/main.yml
> workflows: fix artifact name of Windows exe

- src/backend/src/generated/calibration/calibration.grpc.pb.cc
- src/backend/src/generated/calibration/calibration.grpc.pb.h
- src/backend/src/generated/calibration/calibration.pb.cc
- src/backend/src/generated/calibration/calibration.pb.h
- src/backend/src/generated/log_files/log_files.pb.cc
- src/backend/src/generated/log_files/log_files.pb.h
- src/backend/src/plugins/calibration/calibration_service_impl.h
- src/backend/src/plugins/log_files/log_files_service_impl.h
- src/integration_tests/CMakeLists.txt
- src/integration_tests/calibration.cpp
- src/integration_tests/log_files.cpp
- src/plugins/calibration/calibration.cpp
- src/plugins/calibration/calibration_impl.cpp
- src/plugins/calibration/calibration_impl.h
- src/plugins/calibration/include/plugins/calibration/calibration.h
- src/plugins/log_files/include/plugins/log_files/log_files.h
- src/plugins/log_files/log_files.cpp
- src/plugins/log_files/log_files_impl.cpp
Adds level horizon calibration to the backend.
> calibration: add generated from proto board level horizon calibration

- .github/workflows/main.yml
- src/core/serial_connection.cpp
- src/plugins/ftp/fs.cpp
I would like to have a CI test to make sure we don't go too far away from musl support :innocent:.
> Make MAVSDK build with musl

- src/core/call_every_handler.h
- src/core/mavlink_message_handler.h
- src/core/mavlink_parameters.h
- src/core/mavsdk_impl.h
- src/core/system_impl.h
- src/core/timeout_handler.h
- src/plugins/camera/camera_definition.cpp
- src/plugins/camera/camera_definition.h
- src/plugins/camera/camera_definition_test.cpp
- src/plugins/camera/camera_impl.cpp
- src/plugins/log_files/log_files_impl.h
- src/plugins/mission/mission_impl.cpp
- src/plugins/mission/mission_impl.h
Fixes https://github.com/mavlink/MAVSDK/issues/1103
> Changed map to unordered_map

- src/integration_tests/mission_change_speed.cpp
- src/plugins/mission/mission_impl.cpp
- src/plugins/mission/mission_impl.h
This is the follow up to @roangel's PR #1105.
Also fixes #1031.
> Fix mission indices

- src/core/mavsdk_impl.cpp
- src/core/udp_connection.cpp
- src/core/udp_connection.h
> Attempt to remove some UDP connection hacks

- templates/cmake/file.j2
- templates/plugin_impl_cpp/call.j2
- templates/plugin_impl_cpp/file.j2
- templates/plugin_impl_cpp/request.j2
- templates/plugin_impl_cpp/stream.j2
- templates/plugin_impl_cpp/struct.j2
- templates/plugin_impl_h/call.j2
- templates/plugin_impl_h/file.j2
- templates/plugin_impl_h/request.j2
- templates/plugin_impl_h/stream.j2
- tools/generate_from_protos.sh
The `generate_from_protos.sh` script can now bootstrap everything needed to add a new plugin. It does so by looking for new proto definitions in `proto/protos` and using templates for the `_impl.h` and `_impl.cpp` parts.
> Bootstrapping of plugins from proto

- src/core/mavsdk_impl.cpp
I think this was forgotten when removing the other connection hacks.
> Do not ignore QGC messages

- src/plugins/telemetry/telemetry_impl.cpp
This flas was actually just fake before and a duplicate of the GPS available flag.
Hopefully this will help with https://github.com/PX4/Firmware/issues/14835.
FYI @kamilritz
> telemetry: fix local position health flag

- src/cmake/unit_tests.cmake
- src/plugins/telemetry/CMakeLists.txt
- src/plugins/telemetry/math_conversions.cpp
- src/plugins/telemetry/math_conversions_test.cpp
> Unit tests for angle conversions and fix conversion

- examples/geofence_inclusion/geofence_inclusion.cpp
- src/backend/src/generated/geofence/geofence.pb.cc
- src/backend/src/generated/geofence/geofence.pb.h
- src/backend/src/generated/gimbal/gimbal.pb.cc
- src/backend/src/generated/gimbal/gimbal.pb.h
- src/backend/src/plugins/geofence/geofence_service_impl.h
- src/backend/src/plugins/gimbal/gimbal_service_impl.h
- src/core/mavlink_commands.cpp
- src/core/mavlink_commands.h
- src/core/system_impl.cpp
- src/core/system_impl.h
- src/integration_tests/geofence_inclusion.cpp
- src/integration_tests/gimbal.cpp
- src/plugins/geofence/geofence.cpp
- src/plugins/geofence/geofence_impl.cpp
- src/plugins/geofence/include/plugins/geofence/geofence.h
- src/plugins/gimbal/CMakeLists.txt
- src/plugins/gimbal/gimbal.cpp
- src/plugins/gimbal/gimbal_impl.cpp
- src/plugins/gimbal/gimbal_impl.h
- src/plugins/gimbal/gimbal_protocol_base.h
- src/plugins/gimbal/gimbal_protocol_v1.cpp
- src/plugins/gimbal/gimbal_protocol_v1.h
- src/plugins/gimbal/gimbal_protocol_v2.cpp
- src/plugins/gimbal/gimbal_protocol_v2.h
- src/plugins/gimbal/gimbal_v1.cpp
- src/plugins/gimbal/gimbal_v1.h
- src/plugins/gimbal/include/plugins/gimbal/gimbal.h
This is work in progress to add support for the new gimbal protocol.
See docs: https://mavlink.io/en/services/gimbal_v2.html
This will conflict with #1022 and we'll have to find a way to resolve that.
> Steps towards gimbal protocol v2

- .github/workflows/main.yml
Seems too easy to be true :see_no_evil:
> add manylinux2014-aarch64 build to CI

- tools/generate_from_protos.sh
This mainly adds a hint about how to install `protoc-gen-mavsdk`, plus two small cleanups, see commits.
Closes  #1139.
> Slight improvements to generate_from_protos.sh

- .github/workflows/main.yml
- docker/Dockerfile-Ubuntu-18.04-PX4-SITL-v1.11
- docker/build_and_push_docker_images.sh
- tools/start_px4_sitl.sh
This adds v1.11 to CI and docker.
> Add PX4 v1.11.0 (rc1) to CI

- src/plugins/ftp/ftp_impl.cpp
Details in commit messages.
FYI @MatejFranceskin, @cmic0.
> MAVLink FTP bugfixes

- src/plugins/telemetry/math_conversions.cpp
- src/plugins/telemetry/telemetry_impl.cpp
> Fix bugs in telemetry attitude

- examples/manual_control/manual_control.cpp
> manual_control example improvements

- src/plugins/ftp/ftp_impl.cpp
- src/plugins/ftp/ftp_impl.h
For more details, check commits.
I would appreciate a review @MatejFranceskin.
FYI @cmic0
> Delete empty file if remote file does not exist

- src/backend/src/CMakeLists.txt
- src/backend/src/grpc_server.cpp
- src/backend/src/grpc_server.h
Resolves https://github.com/mavlink/MAVSDK-Python/issues/243
> Added Manual Control Module in Service

- src/core/mavsdk.cpp
- src/core/mavsdk.h
- src/integration_tests/integration_test_helper.h
- src/integration_tests/telemetry_modes.cpp
> Fix CI yet again

- src/plugins/mission/mission_impl.cpp
> Fixed loiter time (hold time) being ignored on QGC mission import.

- docker/Dockerfile-Ubuntu-20.04-PX4-SITL-v1.11
- src/integration_tests/action_hover_sync.cpp
The release is out, so we should use it!
> Update docker image to PX4 v1.11.0

- src/backend/src/generated/action/action.grpc.pb.cc
- src/backend/src/generated/action/action.grpc.pb.h
- src/backend/src/generated/action/action.pb.cc
- src/backend/src/generated/action/action.pb.h
- src/backend/src/plugins/action/action_service_impl.h
- src/plugins/action/action.cpp
- src/plugins/action/action_impl.cpp
- src/plugins/action/action_impl.h
- src/plugins/action/include/plugins/action/action.h
- src/plugins/action/mocks/action_mock.h
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/163
> Add terminate

- src/core/system_impl.cpp
> Add support for statustext sequences

- .github/workflows/main.yml
- docker/Dockerfile-Ubuntu-18.04
- docker/Dockerfile-Ubuntu-20.04
- examples/battery/battery.cpp
- src/backend/src/core/core_service_impl.h
- src/core/geometry.cpp
- src/core/mavlink_mission_transfer.cpp
- src/plugins/geofence/geofence_impl.cpp
- src/plugins/mission/mission_impl.cpp
- tools/fix_style.sh
- tools/run-docker.sh
This is because we can build on Ubuntu 20.04 now, not 18.04 anymore.
> tools: update to clang-format-10

- src/plugins/telemetry/telemetry_impl.cpp
Type in implementation setting `new_fixedwing_metrics.throttle_percentage` and `new_fixedwing_metrics.climb_rate_m_s`
> #1203 type in process_fixedwing_metrics impl

- .github/workflows/main.yml
> Fix iOS release path in CI

- .github/workflows/main.yml
- src/backend/src/CMakeLists.txt
- src/backend/test/CMakeLists.txt
- src/core/geometry_test.cpp
@JonasVautherin here is your work according to https://stackoverflow.com/questions/61799147/link-libc-statically.
> backend: build statically with musl

- .github/workflows/main.yml
> workflows: try to fix upload of artefacts

- examples/gimbal_device_tester/gimbal_device_tester.cpp
A collection of improvements for the tester. For more info check commits.
> Gimbal device tester improvements

- src/plugins/offboard/offboard_impl.cpp
> Filter heartbeat in Offboard plugin to consider only autopilot heartbeats

- src/integration_tests/gimbal.cpp
Build and run with:
```
cmake -Bbuild/default -H.
cmake --build build/default -j8 && build/default/src/integration_tests/integration_tests_runner --gtest_filter="SitlTestGimbal.GimbalAngles" 
```
> integration_tests: add gimbal angle test

- src/plugins/mission/mission_impl.cpp
Closes #1101, replacing MAV_CMD_NAV_LOITER_TIME with MAV_CMD_NAV_DELAY. Additionally, added checks for whether or not speed actually changed when inserting MAV_CMD_DO_CHANGE_SPEED mission items.
> Mission: use NAV_DELAY instead of LOITER_TIME

- .github/workflows/main.yml
- src/integration_tests/action_transition_multicopter_fixedwing.cpp
Latest PX4 versions do not support transitioning anymore while still in Takeoff mode. Therefore, we need to wait until we have reached Hover before issueing the transition command.
> integration_tests: fix transition test

- src/core/mavlink_mission_transfer.cpp
- src/core/mavlink_mission_transfer_test.cpp
- src/integration_tests/CMakeLists.txt
- src/integration_tests/mission_set_current.cpp
This tests that mission_set_current does what it promises and returns with a result.
> integration_tests: add test for mission_set_current

- examples/gimbal_device_tester/CMakeLists.txt
> gimbal_device_tester: switch to C++17 as well

- templates/plugin_cpp/call.j2
- templates/plugin_cpp/request.j2
I had fixed the `.h` files, but forgot the generated `.cpp` :facepalm:
> Fix result template cpp

- src/core/mavlink_commands.h
> core: fix missing private access modifier

- tools/run-docker.sh
This was accidentally changed to podman beforehand. I'm now changing it back to docker but also supporting podman if available.
> tools: support docker and podman

- tools/run-docker.sh
> tools: use correct docker image version

- src/plugins/mission/mission_impl.cpp
- src/plugins/mission_raw/mission_raw_impl.cpp
> Reset mission progress on clear and mission upload

- templates/cmake/file.j2
> template: fix VERSION/SOVERSION

- src/plugins/offboard/offboard_impl.cpp
Check invididual commits.
Related to #1307.
> Various offboard improvements

- templates/plugin_impl_cpp/request.j2
- templates/plugin_impl_cpp/stream.j2
- templates/plugin_impl_h/stream.j2
I found this while working on #1336.
> templates: impl fixes

- src/core/mavsdk_impl.cpp
PX4 is now forwarding messages between the SDK link on UDP port 14540 and the QGC link on UDP port 1550. This causes examples, integration tests, and existing implementations to break as they discover 2 systems
when they are only expecting one.
Therefore, I suggest to add a workaround to filter messages coming from QGC for the case where MAVSDK is used in the default configuration, so as a ground station.
The correct fix will be to properly discover the system by checking if it `has_autopilot()` but it will take some time for that to take place, so I suggest this workaround in the meantime.
This is how examples and integration tests have to change: #1328.
> core: add filter for messages from QGC

- src/plugins/telemetry/telemetry_impl.cpp
> telemtry: fixed small type oversight

- examples/CMakeLists.txt
- examples/camera/CMakeLists.txt
- examples/camera/camera.cpp
- examples/camera_settings/CMakeLists.txt
- examples/camera_settings/camera_settings.cpp
This is mostly a copy of @JonasVautherin's [Python example](https://github.com/mavlink/MAVSDK-Python/blob/main/examples/camera_params.py), just not as nice.
FYI @TSC21
> Add example to set camera settings

- src/core/CMakeLists.txt
- src/core/ringbuffer.h
- src/core/ringbuffer_test.cpp
- src/plugins/info/info_impl.cpp
- src/plugins/info/info_impl.h
It turns out that the timestamps vary quite a lot and our filtering did not give accurate results, we actually need to integrate the simulated and real time. I decided to use a circular buffer for the integration, although some online integrator would have probably been easier, a well.
> Improve realtime factor estimate

- src/integration_tests/CMakeLists.txt
- src/integration_tests/offboard_acceleration.cpp
- src/mavsdk_server/src/generated/offboard/offboard.grpc.pb.cc
- src/mavsdk_server/src/generated/offboard/offboard.grpc.pb.h
- src/mavsdk_server/src/generated/offboard/offboard.pb.cc
- src/mavsdk_server/src/generated/offboard/offboard.pb.h
- src/mavsdk_server/src/plugins/offboard/offboard_service_impl.h
- src/plugins/offboard/include/plugins/offboard/offboard.h
- src/plugins/offboard/mocks/offboard_mock.h
- src/plugins/offboard/offboard.cpp
- src/plugins/offboard/offboard_impl.cpp
- src/plugins/offboard/offboard_impl.h
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/216
> Add acceleration to offboard plugin

- src/cmake/unit_tests.cmake
> cmake: fix MSVC release build with shared libs

- src/mavsdk_server/src/generated/camera/camera.pb.cc
- src/mavsdk_server/src/generated/camera/camera.pb.h
- src/mavsdk_server/src/plugins/camera/camera_service_impl.h
- src/plugins/camera/camera.cpp
- src/plugins/camera/camera_impl.cpp
- src/plugins/camera/include/plugins/camera/camera.h
Based on @JonasVautherin work in https://github.com/mavlink/MAVSDK-Proto/pull/219.
> camera: add sensor information

- tools/generate_changelog.py
This fixes the case where the last PR of the previous release sneaks into the current release as well due to what seems to be an inclusive time range. It looks like by shifting it by one minute we can avoid that.
> tools: fix duplicate changelog entires

- src/mavsdk_server/cmake/MacOSXFrameworkInfo.plist.in
Now that the CI builds with version 13, the Info.plist needs to reflect that
> Bump MinimumOSVersion to 13.0 in Info.plist

- src/integration_tests/CMakeLists.txt
Those lines seem weird to me, I think they can go away
> Remove wrongly-included files in CMakeLists.txt

- README.md
> readme: update old links

- src/plugins/offboard/offboard_impl.cpp
And fix offboard build fixes related to it.
> mavlink: update submodule

- examples/battery/battery.cpp
- examples/fly_mission/fly_mission.cpp
- examples/fly_qgc_mission/fly_qgc_mission.cpp
- examples/geofence_inclusion/geofence_inclusion.cpp
- examples/set_actuator/set_actuator.cpp
The examples still need an overall pass to modernize it all and make it nicer.
> examples: cleanup and fixes for GCC11

- src/plugins/camera/camera_definition.cpp
Happened to me recently, and I would have liked to see the name of the setting :innocent:
> Minor logging improvement

- examples/gimbal_device_tester/gimbal_device_tester.cpp
I found it when I ran the example with valgrind.
> examples: fix uninitialized data

- src/core/mavsdk.h
The behavior of add_any_connection had changed in:
https://github.com/mavlink/MAVSDK/pull/1418
> core: improve connection docstring

- src/core/mavlink_commands.cpp
- src/core/mavlink_commands.h
- src/core/mavlink_mission_transfer.cpp
- src/core/mavlink_mission_transfer.h
- src/core/mavlink_mission_transfer_test.cpp
- src/core/mocks/sender_mock.h
- src/core/system_impl.cpp
- src/core/system_impl.h
- src/plugins/action/action_impl.cpp
- src/plugins/calibration/calibration_impl.cpp
- src/plugins/camera/camera_impl.cpp
- src/plugins/failure/failure_impl.cpp
- src/plugins/gimbal/gimbal_impl.cpp
- src/plugins/gimbal/gimbal_protocol_v1.cpp
- src/plugins/gimbal/gimbal_protocol_v2.cpp
- src/plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
- src/plugins/mission/mission_impl.cpp
- src/plugins/telemetry/telemetry_impl.cpp
This is much nicer for two reasons:
- No re-compilation required.
- All code paths are built in CI.
> core/plugins: detect autopilot at runtime

- src/core/system_impl.cpp
This was obviously very wrong.
> core: fix autopilot detection

- src/core/mavlink_mission_transfer_test.cpp
> core: fix mission transfer unit tests

- src/core/mavlink_commands.cpp
- src/core/mavlink_commands.h
- src/core/mavlink_include.h
- src/core/mavlink_mission_transfer.cpp
- src/core/mavlink_mission_transfer.h
- src/core/mavlink_mission_transfer_test.cpp
- src/core/mavsdk_impl.cpp
- src/core/timeout_handler.cpp
- src/plugins/camera/camera_impl.cpp
- src/plugins/gimbal/gimbal_impl.cpp
- src/plugins/mission/mission_impl.cpp
- src/plugins/telemetry/telemetry_impl.cpp
- src/plugins/telemetry/telemetry_impl.h
Check individual commits for more information.
Fixes #1499.
> Various commication fixes

- src/plugins/action_server/action_server_impl.cpp
- src/plugins/action_server/action_server_impl.h
Small one to prevent crashing on unused callbacks :)
> Null check action callbacks

- src/integration_tests/geofence_inclusion.cpp
- src/mavsdk_server/src/generated/geofence/geofence.grpc.pb.cc
- src/mavsdk_server/src/generated/geofence/geofence.grpc.pb.h
- src/mavsdk_server/src/generated/geofence/geofence.pb.cc
- src/mavsdk_server/src/generated/geofence/geofence.pb.h
- src/mavsdk_server/src/plugins/geofence/geofence_service_impl.h
- src/plugins/geofence/geofence.cpp
- src/plugins/geofence/geofence_impl.cpp
- src/plugins/geofence/geofence_impl.h
- src/plugins/geofence/include/plugins/geofence/geofence.h
This adds the functionality to clear geofence existing on the vehicle.
Fixes #1508.
> geofence: add method to clear fence

- src/plugins/camera/camera_impl.cpp
> camera: fix variable shadowing

- src/plugins/mission_raw_server/mission_raw_server_impl.cpp
- src/plugins/mission_raw_server/mission_raw_server_impl.h
Caught myself not checking for null callbacks again. Fixed that
> Mission raw server callbacks nullptr check

- src/mavsdk_server/src/generated/mission/mission.pb.cc
- src/mavsdk_server/src/generated/mission/mission.pb.h
- src/mavsdk_server/src/plugins/mission/mission_service_impl.h
- src/plugins/mission/include/plugins/mission/mission.h
- src/plugins/mission/mission.cpp
This will be added again once it's ready.
> mission: remove VehicleAction for now

- src/plugins/mission/mission_impl.cpp
> Fix mission download

- src/core/mavlink_mission_transfer_test.cpp
- src/mavsdk_server/src/grpc_server.h
- src/mavsdk_server/test/core_service_impl_test.cpp
- src/plugins/action/mocks/action_mock.h
- src/plugins/telemetry/telemetry_impl.cpp
A few fixes as suggested by clang.
> Fix clang warnings

- src/core/mavlink_commands.cpp
- src/core/mavlink_commands.h
Fixes #1527. For review, see commits.
> core: fix calling callback multiple times

- src/plugins/action/action_impl.cpp
Go-To's are only processed in PX4 if in Hold mode. So one needs to enforce changing to this mode first before sending the DO_REPOSITION Mavlink command.
> plugins: action: change to Hold mode before sending DO_REPOSITION

- src/core/mavlink_commands.cpp
> Small command fixes

- src/mavsdk_server/src/CMakeLists.txt
- src/mavsdk_server/src/generated/param_server/param_server.pb.cc
- src/mavsdk_server/src/generated/param_server/param_server.pb.h
- src/mavsdk_server/src/grpc_server.cpp
- src/mavsdk_server/src/grpc_server.h
- src/mavsdk_server/src/plugins/param_server/param_server_service_impl.h
- src/plugins/param_server/include/plugins/param_server/param_server.h
- src/plugins/param_server/param_server.cpp
This updates the server to include all the recently added server plugins.
> mavsdk_server: add missing plugins

- src/mavsdk_server/src/generated/mission/mission.pb.cc
- src/mavsdk_server/src/generated/mission/mission.pb.h
- src/mavsdk_server/src/plugins/mission/mission_service_impl.h
- src/plugins/mission/include/plugins/mission/mission.h
- src/plugins/mission/mission.cpp
- src/plugins/mission/mission_impl.cpp
This enables to set the distance for distance based photo triggering.
> mission: enable setting photo trigger distance

- src/core/mavlink_commands.h
- src/plugins/camera/camera_impl.cpp
> Robustify photo list

- src/mavsdk_server/tools/package_mavsdk_server_framework.bash
> Fix CI permissions when generating xcframework

- .github/workflows/main.yml
- src/mavsdk_server/tools/package_mavsdk_server_framework.bash
This should make the process easier to publish the Swift updates.
> Publish checksum for xcframework

- src/integration_tests/mission.cpp
- src/plugins/mission/mission_impl.cpp
We forgot to test and do that previously which would result in an Unsupported result.
> mission: fix downloading SET_CAM_TRIGG_DIST

- src/plugins/camera/camera_impl.cpp
Because of the logic how last_advertised_image_index was initialized we missed the very first image captured callback. These changes should fix that.
> camrea: fix first capture callback

- src/plugins/camera/camera_impl.cpp
Currently, the camera plugin assumes that the system was an autopilot and always requests flight information. However it may be the case that the system is not an autopilot, e.g. a stand-alone camera.
This adds a condition to check that the system is an autopilot before sending the request.
> camera: only request flight info when system has autopilot

- src/core/CMakeLists.txt
- src/core/mavlink_commands.cpp
- src/core/mavlink_commands.h
- src/core/request_message.cpp
- src/core/request_message.h
- src/core/system_impl.cpp
- src/core/system_impl.h
- src/integration_tests/CMakeLists.txt
- src/integration_tests/telemetry_gps_origin.cpp
- src/plugins/action/action_impl.cpp
- src/plugins/calibration/calibration_impl.cpp
- src/plugins/camera/camera_impl.cpp
- src/plugins/failure/failure_impl.cpp
- src/plugins/gimbal/gimbal_impl.cpp
- src/plugins/gimbal/gimbal_protocol_v1.cpp
- src/plugins/gimbal/gimbal_protocol_v2.cpp
- src/plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
- src/plugins/mission/mission_impl.cpp
- src/plugins/telemetry/telemetry_impl.cpp
This adds a new class which abstracts around MAV_CMD_REQUEST_MESSAGE.
I suggest to review it commit by commit.
@JonasVautherin you are absolutely right in that MAV_CMD_REQUEST_MESSAGE is actually very tricky once you try to implement it to work reliable.
> New RequestMessage class to help with requesting a single message

- src/plugins/failure/failure_impl.cpp
- src/plugins/failure/failure_impl.h
> Fix failure enums (do not cast enum values directly)

- src/plugins/mission/mission_impl.cpp
It turns out that you can enable distance-based triggering just using the command SET_CAM_TRIGG_DIST and you don't have to explicitly start and stop the triggering with TRIGGER_CONTROL.
This makes the logic simpler, removes some overhead of mission items having to be sent, and moves it closer to the implementation of QGroundControl.
FYI @RomanBapst
> mission: remove TRIGGER_CONTROL

- src/plugins/telemetry/telemetry_impl.cpp
- src/plugins/telemetry/telemetry_impl.h
PX4 by now sends the calibration state out using SYS_STATUS. This is to be preferred as it updates after a calibration unlike the params which are only fetched on startup.
Hopefully in the future, we can deprecate support for older PX4 versions and get rid of these params completely.
> telemetry: use SYS_STATUS to determine calibration

- src/core/mavlink_mission_transfer.cpp
This will help debugging this issue the next time it happens.
> core: error message if INT messages not supported

- templates/plugin_h/file.j2
- tools/generate_from_protos.sh
This wasn't entirely correct, and I had not regenerated it from proto in the previous PR #1638.
> templates: fixup after directory restructure

- .github/workflows/main.yml
> workflows: fetch git tags for version

- tools/generate_from_protos.sh
This allows to have other paths than build/default.
> tools: add option to pass build dir

- src/mavsdk/plugins/camera/camera.cpp
- src/mavsdk/plugins/camera/camera_impl.cpp
- src/mavsdk/plugins/camera/include/plugins/camera/camera.h
- src/mavsdk_server/src/generated/camera/camera.pb.cc
- src/mavsdk_server/src/generated/camera/camera.pb.h
- src/mavsdk_server/src/plugins/camera/camera_service_impl.h
This makes it easier to reason about available storage.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/271.
> camera: add storage ID and type

- .github/workflows/main.yml
Otherwise the dependencies don't seem to work.
> workflows: make arm libs shared

- docker/build_and_push_docker_images.sh
> docker: fix tags

- .github/workflows/main.yml
- tools/create_packages.sh
This should:
- reset the cache for arm builds
- use the correct name for library packages
- fix the arm package architecture
> tools: fix package generation

- src/mavsdk/core/include/mavsdk/log_callback.h
- src/mavsdk/core/log.cpp
- src/mavsdk/core/log.h
> core: fix linking on Windows

- src/mavsdk/plugins/ftp/ftp_impl.cpp
This fixes a bug that could cause sender and receiver to get out of sync.
When the ack from receiver is delayed, the sender re-transmits the package. When the ack then arrives anyways, the sender continues with the next package. Since we already re-sent the previous package, another ack for the previous package is received. This makes the sender again move to the next package. From here on, the receiver and sender are out of sync.
This is generally not an issue, but when now an ack gets lost, the sender no longer realizes, since it is already ahead of time and receives enough acks to finish.
This PR fixes the issue by checking the sequence number of the ack. If the ack is for a package with a sequence number lower than our current, the ack is ignored, since we already must have received a …
> mavlink-ftp: Do not continue on receiving an old ack

- .github/workflows/main.yml
- src/mavsdk/plugins/ftp/ftp_impl.cpp
> workflows: bump MSVC version

- src/integration_tests/camera_mode.cpp
- src/integration_tests/camera_settings.cpp
- src/integration_tests/camera_take_photo.cpp
- src/integration_tests/camera_test_helpers.cpp
- src/integration_tests/camera_test_helpers.h
I was able to simplify this a bit.
> integration_tests: camera helper cleanup

- src/mavsdk/plugins/transponder/include/plugins/transponder/transponder.h
- src/mavsdk/plugins/transponder/transponder.cpp
- src/mavsdk/plugins/transponder/transponder_impl.cpp
- src/mavsdk_server/src/generated/transponder/transponder.pb.cc
- src/mavsdk_server/src/generated/transponder/transponder.pb.h
- src/mavsdk_server/src/plugins/transponder/transponder_service_impl.h
Credits go to @chep.
Replacing #1730.
> Plugin/transponder: add tslc in AdsbVehicle struct

- .github/workflows/main.yml
Let's see if this fixes it...
Related to https://github.com/actions/checkout/issues/760.
> workflows: workaround for git trust CI issue

- src/mavsdk/core/mavlink_parameters.cpp
- src/mavsdk/core/mavlink_parameters.h
- src/mavsdk/core/system_impl.cpp
- src/mavsdk/core/system_impl.h
- src/mavsdk/plugins/param/include/plugins/param/param.h
- src/mavsdk/plugins/param/param.cpp
- src/mavsdk/plugins/param/param_impl.cpp
- src/mavsdk/plugins/param/param_impl.h
- src/mavsdk/plugins/param_server/include/plugins/param_server/param_server.h
- src/mavsdk/plugins/param_server/param_server.cpp
- src/mavsdk/plugins/param_server/param_server_impl.cpp
- src/mavsdk/plugins/param_server/param_server_impl.h
- src/mavsdk_server/src/generated/param/param.grpc.pb.cc
- src/mavsdk_server/src/generated/param/param.grpc.pb.h
- src/mavsdk_server/src/generated/param/param.pb.cc
- src/mavsdk_server/src/generated/param/param.pb.h
- src/mavsdk_server/src/generated/param_server/param_server.grpc.pb.cc
- src/mavsdk_server/src/generated/param_server/param_server.grpc.pb.h
- src/mavsdk_server/src/generated/param_server/param_server.pb.cc
- src/mavsdk_server/src/generated/param_server/param_server.pb.h
- src/mavsdk_server/src/plugins/param/param_service_impl.h
- src/mavsdk_server/src/plugins/param_server/param_server_service_impl.h
This is a backport of the custom params feature out of #1733.
> Add custom params

- .github/workflows/main.yml
> workflows: reset CI cache for Windows build

- src/mavsdk/core/mavlink_request_message_handler.cpp
- src/mavsdk/core/mavlink_request_message_handler.h
- src/mavsdk/core/server_component_impl.cpp
- src/mavsdk/core/server_component_impl.h
- src/mavsdk/plugins/component_information_server/component_information_server_impl.cpp
> Two small improvements of server component

- .github/workflows/main.yml
- docker/Dockerfile-Ubuntu-20.04-PX4-SITL-v1.13
- docker/build_and_push_docker_images.sh
> docker/workflows: add PX4 v1.13 beta to CI

- docker/build_and_push_docker_images.sh
That's more how it's supposed to be, right? :thinking:
> Fix build_and_push_docker_images.sh

- third_party/tinyxml2/CMakeLists.txt
- third_party/tinyxml2/cmake-3.10.2.patch
> Update tinyxml2 to 9.0.0

- src/integration_tests/mission_rtl.cpp
Also I believe this may fix a potential crash where the promise is fulfilled twice.
> Fix warning and improve integration test

- src/mavsdk/core/mavlink_command_sender.cpp
When a send_message calls fails we should give up entirely instead of setting a timeout and trying again later.
This could least to the "promise called twice" problem.
> core: prevent timeout after callback

- src/mavsdk_server/src/CMakeLists.txt
- src/mavsdk_server/src/grpc_server.cpp
- src/mavsdk_server/src/grpc_server.h
This had been forgotten earlier.
> mavsdk_server: add missing Rtk plugin

- src/mavsdk/plugins/mavlink_passthrough/include/plugins/mavlink_passthrough/mavlink_passthrough.h
- src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough.cpp
- src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough_impl.cpp
- src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough_impl.h
A nice addition by @devbharat.
> create ack packet and send it

- examples/gimbal_device_tester/CMakeLists.txt
Copy paste mistake.
Thanks @reedev!
> examples: fix build of gimbal_device_tester

- src/mavsdk/plugins/gimbal/include/plugins/gimbal/gimbal.h
- src/mavsdk/plugins/mission/include/plugins/mission/mission.h
- src/mavsdk/plugins/mission/mission.cpp
- src/mavsdk/plugins/mission/mission_impl.cpp
- src/mavsdk/plugins/mission_raw/include/plugins/mission_raw/mission_raw.h
- src/mavsdk/plugins/mission_raw/mission_raw.cpp
- src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp
- src/mavsdk_server/src/generated/mission/mission.pb.cc
- src/mavsdk_server/src/generated/mission/mission.pb.h
- src/mavsdk_server/src/generated/mission_raw/mission_raw.pb.cc
- src/mavsdk_server/src/generated/mission_raw/mission_raw.pb.h
- src/mavsdk_server/src/plugins/mission/mission_service_impl.h
- src/mavsdk_server/src/plugins/mission_raw/mission_raw_service_impl.h
We shouldn't just rely on the debug side effects.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/295.
> mission/mission_raw: more results

- src/mavsdk/plugins/mission_raw/include/plugins/mission_raw/mission_raw.h
- src/mavsdk/plugins/mission_raw/mission_import.cpp
- src/mavsdk/plugins/mission_raw/mission_import.h
- src/mavsdk/plugins/mission_raw/mission_raw.cpp
- src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp
- src/mavsdk/plugins/mission_raw/mission_raw_impl.h
- src/mavsdk_server/src/generated/mission_raw/mission_raw.grpc.pb.cc
- src/mavsdk_server/src/generated/mission_raw/mission_raw.grpc.pb.h
- src/mavsdk_server/src/generated/mission_raw/mission_raw.pb.cc
- src/mavsdk_server/src/generated/mission_raw/mission_raw.pb.h
- src/mavsdk_server/src/plugins/mission_raw/mission_raw_service_impl.h
Rebased/updated version of #1615.
> mission_raw: Add support for geofence and rally points

- src/mavsdk/core/mavlink_mission_transfer.cpp
- src/mavsdk/plugins/mission_raw/mission_import.cpp
- src/mavsdk/plugins/mission_raw/mission_import.h
- src/mavsdk/plugins/mission_raw/mission_import_test.cpp
- src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp
> [backport v1.4] mission_raw: add home position at 0 for ArduPilot

- src/mavsdk/core/mavlink_command_sender.cpp
- src/mavsdk/core/mavsdk_impl.cpp
- src/mavsdk/plugins/telemetry/telemetry_impl.cpp
> Remove some noise

- src/mavsdk/core/CMakeLists.txt
- src/mavsdk/plugins/mavlink_passthrough/CMakeLists.txt
I think I was wrong with #1911.
Closes #1912.
> [Backport v1.4] Revert #1911

- src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h
- src/mavsdk/plugins/telemetry/telemetry.cpp
- src/mavsdk/plugins/telemetry/telemetry_impl.cpp
- src/mavsdk_server/src/generated/telemetry/telemetry.pb.cc
- src/mavsdk_server/src/generated/telemetry/telemetry.pb.h
- src/mavsdk_server/src/plugins/telemetry/telemetry_service_impl.h
Closes [#1928 ](https://github.com/mavlink/MAVSDK/issues/1928)
> Add bottom_clearance to altitude in telemetry

- third_party/CMakeLists.txt
> Move openssl dep to MAVSDK_SERVER only

- docker/README.md
Update deprecated example as Ubuntu18.04 has been removed. Update example to Ubuntu 20.04
> docker: Update README

- src/mavsdk/plugins/server_utility/server_utility_impl.cpp
> server_utility: remove leftover warning

- examples/logfile_download/logfile_download.cpp
- src/mavsdk/plugins/log_files/include/plugins/log_files/log_files.h
- src/mavsdk/plugins/log_files/log_files.cpp
- src/mavsdk/plugins/log_files/log_files_impl.h
- src/mavsdk_server/src/generated/log_files/log_files.grpc.pb.cc
- src/mavsdk_server/src/generated/log_files/log_files.grpc.pb.h
- src/mavsdk_server/src/generated/log_files/log_files.pb.cc
- src/mavsdk_server/src/generated/log_files/log_files.pb.h
- src/mavsdk_server/src/plugins/log_files/log_files_service_impl.h
Follow-up on https://github.com/mavlink/MAVSDK-Proto/pull/304
> fixed log_files proto

- .github/workflows/main.yml
- third_party/mavlink/CMakeLists.txt
Let's try again, from another angle.
> Fix CI for iOS

- tools/fix_style.sh
> fix_style.sh: Show correct docs link

- src/mavsdk/plugins/mission_raw_server/mission_raw_server_impl.cpp
Fixed bug with empty mission upload
> Fixed bug with empty mission upload

- src/mavsdk/plugins/telemetry/telemetry_impl.cpp
> [BACKPORT v1.4] telemetry: fix distance_sensor unit

- src/mavsdk/plugins/mission_raw/mission_raw_impl.cpp
Closes [#1936](https://github.com/mavlink/MAVSDK/issues/1936)
> mission_raw: bug fix in setting current mission item

- src/mavsdk/plugins/calibration/calibration_impl.cpp
> calibration: remove spurious cancel command

- src/mavsdk_server/src/CMakeLists.txt
- src/mavsdk_server/test/CMakeLists.txt
> [BACKPORT v1.4] mavsdk_server: link to dl

- .github/workflows/main.yml
CI is starting to complain about our old actions :blush:
> CI: update checkout action

- src/mavsdk/plugins/mavlink_passthrough/mavlink_passthrough.cpp
This was missing :see_no_evil:
> Fix mavlink_passthrough operator<<

- debian/libmavsdk-dev.install
> Add .pc file (pkg-config) to deb package

- examples/camera_server/CMakeLists.txt
- examples/camera_server/camera_client.cpp
- examples/camera_server/camera_server.cpp
* Add camera client sample for camera server example;
* Remove global using namespace int camera_server.cpp;
* Remove useless include header in camera_server.cpp;
> Add camera client sample code for camera server example

- src/mavsdk/core/system_impl.cpp
Actually I think it is worth making it a bit more consistent, even if that's not a bugfix.
> Minor refactoring in ardupilot flight modes

- examples/offboard/offboard.cpp
- src/mavsdk/plugins/offboard/include/plugins/offboard/offboard.h
- src/mavsdk/plugins/offboard/mocks/offboard_mock.h
- src/mavsdk/plugins/offboard/offboard.cpp
- src/mavsdk/plugins/offboard/offboard_impl.cpp
- src/mavsdk/plugins/offboard/offboard_impl.h
- src/mavsdk_server/src/generated/offboard/offboard.grpc.pb.cc
- src/mavsdk_server/src/generated/offboard/offboard.grpc.pb.h
- src/mavsdk_server/src/generated/offboard/offboard.pb.cc
- src/mavsdk_server/src/generated/offboard/offboard.pb.h
- src/mavsdk_server/src/plugins/offboard/offboard_service_impl.h
hello 
I just closed the last old pull request for this modification.
link:
https://github.com/mavlink/MAVSDK/pull/2049
it seems my branch was back from the main and I am not a git expert and couldn't rebase it.
i created a new branch and did the same steps just like last time on the updated main
everything works except I cannot build the mavsdk
I try to build the mavsdk_server using below command
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DBUILD_MAVSDK_SERVER=ON -Bbuild/default -H.
cmake --build build/default -j8
but I get the following error  when building
In file included from /home/alireza/MAVSDK/src/mavsdk/plugins/param/param.cpp:7:
/home/alireza/MAVSDK/src/mavsdk/plugins/param/param_impl.h:37:58: error: ‘mavsdk::Param::ProtocolVersion’ has not been declared
37 | …
> added set_position_velocity_acceleration_ned offboard function

- src/mavsdk/core/system_impl.cpp
Ardupilot does not listen for these
> core: do not ping ardupilot

- src/mavsdk/core/mavlink_ftp.cpp
This PR addresses the issue as described in #2108
Changed PR to target v1.4 as requested by @julianoes 
Note: As mentioned by @julianoes, this issue is likely addressed #2060 but I agree that this should be included as a bug fix.
> Fix FTP file descriptor leak

- src/mavsdk/plugins/telemetry/telemetry_impl.cpp
- src/mavsdk/plugins/telemetry/telemetry_impl.h
Backport of https://github.com/mavlink/MAVSDK/pull/1794.
> Backport sys status for position health flags

- src/mavsdk/plugins/camera/camera_impl.cpp
Bring https://github.com/mavlink/MAVSDK/pull/2133 to main
> camera: fix conflict between subscribe_status and subscribe_information

- src/mavsdk/plugins/camera/camera_impl.cpp
- src/mavsdk/plugins/camera/camera_impl.h
Bring https://github.com/mavlink/MAVSDK/pull/2150 to main.
> Fix storage type translation (STORAGE_TYPE_OTHER)

- .github/workflows/main.yml
GitHub complains about deprecations.
> [v1.4] update ci actions

- examples/gimbal_device_tester/gimbal_device_tester.cpp
Various gimbal_device_test fixes as they are discovered.
> gimbal device test fixes

- tools/ios.toolchain.cmake
This updates the iOS toolchain from:
https://github.com/leetal/ios-cmake/blob/master/ios.toolchain.cmake as of [d1aacfec](https://github.com/leetal/ios-cmake/commit/d1aacfec52c5db69866ce8dfe0d07de63c6dceca) (2023-11-19).
Alternative to #2176.
> tools: Update iOS toolchain

- .github/workflows/main.yml
This worked for me locally, so let's try CI.
> CI: update to latest alpine

- src/system_tests/system_tests_runner.cpp
- third_party/cpptrace/CMakeLists.txt
- third_party/curl/CMakeLists.txt
- third_party/jsoncpp/CMakeLists.txt
> Update some more dependencies

- src/mavsdk/plugins/action/action_impl.cpp
This needs to be floored, not rounded, otherwise actuators above 3 won't work for PX4.
> action: fix set actuator index

- src/mavsdk/plugins/action/action.cpp
- src/mavsdk/plugins/action/action_impl.cpp
- src/mavsdk/plugins/action/action_impl.h
- src/mavsdk/plugins/action/include/plugins/action/action.h
- src/mavsdk/plugins/action/mocks/action_mock.h
- src/mavsdk_server/src/generated/action/action.grpc.pb.cc
- src/mavsdk_server/src/generated/action/action.grpc.pb.h
- src/mavsdk_server/src/generated/action/action.pb.cc
- src/mavsdk_server/src/generated/action/action.pb.h
- src/mavsdk_server/src/plugins/action/action_service_impl.h
This is for bench things.
Depends on https://github.com/mavlink/MAVSDK-Proto/pull/337.
> action: add option to force arming

- src/mavsdk/core/system_impl.cpp
- src/mavsdk/core/system_impl.h
- src/mavsdk/plugins/camera/camera_impl.cpp
- src/mavsdk/plugins/camera/camera_impl.h
- src/mavsdk/plugins/info/info_impl.cpp
- src/mavsdk/plugins/info/info_impl.h
> Info fixups

- src/integration_tests/info.cpp
- src/mavsdk/plugins/info/include/plugins/info/info.h
- src/mavsdk/plugins/info/info.cpp
- src/mavsdk/plugins/info/info_impl.cpp
- src/mavsdk/plugins/info/info_impl.h
- src/mavsdk/plugins/info/mocks/info_mock.h
- src/mavsdk_server/src/generated/info/info.grpc.pb.cc
- src/mavsdk_server/src/generated/info/info.grpc.pb.h
- src/mavsdk_server/src/generated/info/info.pb.cc
- src/mavsdk_server/src/generated/info/info.pb.h
- src/mavsdk_server/src/plugins/info/info_service_impl.h
That's better than having to call get once a second.
> info: add flight information subscription

- src/mavsdk/core/mavlink_command_sender.cpp
- src/mavsdk/core/system_impl.cpp
- src/mavsdk/core/system_impl.h
- src/mavsdk/core/timeout_handler.cpp
- src/mavsdk/core/timeout_handler.h
- src/mavsdk/plugins/gimbal/gimbal_impl.cpp
> TimeoutHandler fixes

- src/mavsdk/core/inflate_lzma.cpp
- src/mavsdk/core/mavlink_ftp_client.h
Trying to get a green checkmark :heavy_check_mark:...
> Sonarcloud warnings

- .github/workflows/main.yml
> CI: fix arm64 lib getting overwritten

- .github/workflows/main.yml
- README.md
- third_party/absl/CMakeLists.txt
Let me try on my side :innocent:
> Fix absl CI

- examples/follow_me/follow_me.cpp
Fix Follow Me example by explicitly setting absolute_altitude_m in target_location.
> Fix Follow Me example

- examples/battery/battery.cpp
> examples: fix sysid/compid of battery example

- .github/workflows/main.yml
- examples/logfile_download/logfile_download.cpp
- src/mavsdk/core/mavlink_message_handler.cpp
> CI: a few fixes and adding newer compilers

- src/mavsdk/core/mavlink_command_receiver.cpp
- src/mavsdk/core/mavsdk_impl.cpp
- src/mavsdk/core/mavsdk_impl.h
This is to find an odd bug where sometimes we seem to parse random system's messages, and we're not sure where they come from.
> Add some system debugging

- src/mavsdk/core/mavlink_command_receiver.cpp
- src/mavsdk/core/mavsdk_impl.cpp
- src/mavsdk/core/mavsdk_impl.h
> [v2.12 BACKPORT] Add some system debugging

- src/mavsdk/plugins/component_metadata_server/CMakeLists.txt
> plugins: fix install path

- src/mavsdk/core/mavsdk_impl.h
I must have broken this in a previous refactor.
Fixes #2420.
> core: fix timeout

- src/mavsdk/plugins/camera_server/camera_server_impl.cpp
It turns out we were sending the ack and message for storage information as well as capture status twice, once directly in the request handler callback, and once the MAVSDK user would call the respond function.
We should only call it in the respond function, not in the callback.
> camera_server: prevent double ack+message

- src/mavsdk/plugins/camera_server/camera_server_impl.cpp
> [BACKPORT v2.12] camera_server: set zoom flag

- src/mavsdk/plugins/camera_server/camera_server_impl.cpp
> camera_server: set zoom flag

- src/mavsdk/core/serial_connection.cpp
> core: fix Windows build

- src/mavsdk/core/ardupilot_custom_mode.h
Corrected "Arudpilot" to "Ardupilot"
> Update ardupilot_custom_mode.h misspelled name

- .github/workflows/main.yml
We changed the path for the build but not package generation.
> CI: fix package generation

- docs/en/cpp/api_reference/classmavsdk_1_1_telemetry.md
- docs/en/cpp/api_reference/structmavsdk_1_1_telemetry_1_1_wind.md
- examples/CMakeLists.txt
- examples/wind/CMakeLists.txt
- examples/wind/wind.cpp
- src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h
- src/mavsdk/plugins/telemetry/mocks/telemetry_mock.h
- src/mavsdk/plugins/telemetry/telemetry.cpp
- src/mavsdk/plugins/telemetry/telemetry_impl.cpp
- src/mavsdk/plugins/telemetry/telemetry_impl.h
- src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.cc
- src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.h
- src/mavsdk_server/src/generated/telemetry/telemetry.pb.cc
- src/mavsdk_server/src/generated/telemetry/telemetry.pb.h
- src/mavsdk_server/src/plugins/telemetry/telemetry_service_impl.h
Feature subscribe wind data via MAVSDK
[Proto PR](https://github.com/mavlink/MAVSDK-Proto/pull/371)
Add Example for subscribe wind `wind.cpp`
> Add mavlink wind

- src/mavsdk/core/mavlink_request_message.cpp
- src/mavsdk/core/mavlink_request_message.h
> core: Disable request message warnings

- src/mavsdk/core/mavlink_parameter_subscription.cpp
- src/mavsdk/core/mavlink_parameter_subscription.h
This should fix a system test abort that we often see with macOS in CI.
> core: fix mutex lock failed

- .github/workflows/main.yml
These runners are no longer available.
> CI: remove Ubuntu 20.04

- .github/workflows/main.yml
- src/CMakeLists.txt
- src/mavsdk/core/mavlink_component_metadata.h
- src/mavsdk/plugins/camera/camera_impl.cpp
- src/mavsdk/plugins/camera/camera_impl.h
- src/unit_tests/CMakeLists.txt
> Fix build without curl

- .github/workflows/main.yml
To prevent CI failing:
https://github.com/mavlink/MAVSDK/actions/runs/14854566885/job/41704705741
> CI: save some disk space

- .github/workflows/windows.yml
It really shouldn't be that hard. It's ridiculous.
> CI: hard-code Windows to 4 threads

- CMakeLists.txt
- docs/en/cpp/guide/build.md
- examples/CMakeLists.txt
- examples/camera_server/camera_server.cpp
- examples/fly_multiple_drones/fly_multiple_drones.cpp
- examples/log_streaming/log_streaming.cpp
- examples/offboard/CMakeLists.txt
- src/MAVSDKConfig.cmake.in
- third_party/liblzma/CMakeLists.txt
Various fixes regarding #2575.
I still want to properly split up the docs into build for Linux, macOS, Windows, etc.
> Windows fixes

- .github/workflows/linux.yml
Hopefully, this fixes the issue where the docker build happens every time instead of only when the docker directory actually changes.
> CI: only rebuild docker when directory changed

- .github/workflows/docker-pr-cleanup.yml
- tools/cleanup_dockerhub.py
In pull requests we upload docker images with tag pr-* (rather than latest). Every week, we should clean these up.
> CI: add way to cleanup docker images tagged with pr-*

- src/mavsdk/core/http_loader.cpp
This fixes a regression which caused the HttpLoader thread busy loop on the work queue lock.
Fixes https://github.com/julianoes/rtk-sender-example/issues/4.
Introduced in #2599 with v3.7.0.
> core: fix 100% CPU usage in HttpLoader

- src/mavsdk/plugins/camera_server/camera_server_impl.cpp
- src/mavsdk/plugins/camera_server/camera_server_impl.h
This is mostly around sending CaptureStatus more regularly.
> CameraServer improvements

- .github/workflows/linux.yml
This didn't actually seem to work.
> CI: actually set CC and CXX vars

- docs/en/cpp/api_reference/classmavsdk_1_1_telemetry.md
- src/mavsdk/plugins/telemetry/include/plugins/telemetry/telemetry.h
- src/mavsdk_server/src/generated/telemetry/telemetry.grpc.pb.h
Contains https://github.com/mavlink/MAVSDK-Proto/pull/382.
> proto: update to get comment regardig GPS fix

- src/mavsdk/core/libmav_receiver.cpp
- src/mavsdk/plugins/mavlink_direct/mavlink_direct_impl.cpp
- src/system_tests/mavlink_direct.cpp
JSON doesn't support NaN, so we need to use null instead.
Also, we need to assume arrays have all the same types, and not check the type of each array field. This way we can correctly use 0 for int and null for float/double.
> mavlink_direct: handle NaN correctly
